### ISSUE TITLE
New screenshots to get better table header colors

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#10]
Now that the table header colors match the color theme, it would be good to get another set of screenshots for windows that have headers like tables and trees.  Just like the coloring of the Tabs really helped the overall look, so will these new header colors.

**Comment by Aboghazala** [comment]
I already updated the screenshots of the table window and it looks a way much better than mono-color old one, nice work :))

also  updated its link in the readme file, 

![downloads_reds_2](https://user-images.githubusercontent.com/37757246/71382973-fca91f00-25e2-11ea-8079-e4efa50e5b32.PNG)

**Comment by PySimpleGUI** [comment]
Oooooooo.... that's nice!

Your application is crazy complex but yet you make it look easy and simple.

I contacted the "Awesome Python Applications" GitHub owner and told him of the name change as well as you being over 100 commits, a threshold they mentioned in the previous reply.  You've made a lot of good progress since the initial contact with them.  Congrats on the hard work.

**Comment by Aboghazala** [comment]
Thanks a lot 👍

**Comment by PySimpleGUI** [comment]
Be sure and get the main one too

![image](https://user-images.githubusercontent.com/46163555/71417741-f5aafc80-2634-11ea-9167-70b961829d45.png)


I originally coded the theme stuff so that scrollbars would also be colored, but those changes don't seemed to have worked.  I'll see if they look good now that I've got everything else matching.

**Comment by Aboghazala** [comment]
just edited the image with new table headers

![multi-3](https://user-images.githubusercontent.com/37757246/71418363-c0250400-2672-11ea-8559-cc8965757e90.png)

let me know once scrollbars coloring  works out to update other screenshots

**Comment by PySimpleGUI** [comment]
THANK YOU!

What do you think about the idea of coloring the scrollbars?

**Comment by Aboghazala** [comment]
> What do you think about the idea of coloring the scrollbars?

i think it would be great 👍

**Comment by PySimpleGUI** [comment]
Now that I'm trying, again, to add it, I'm remembering a bit more why it won't work :-)  at least not with tkinter.  Tkinter's scrollbars and colors are provided by Windows.  There's a chance with Qt that this can be done.  BUMMER for sure but i'm not giving up just yet.

**Comment by PySimpleGUI** [comment]
Damnit, as I suspected, it works on Linux, but not windows.

![image](https://user-images.githubusercontent.com/46163555/71418843-b41d5000-263a-11ea-898b-e51822f7d78e.png)

**Comment by Aboghazala** [comment]
:)) Getting so close, i think you will figure it out for windows, very nice work !!

**Comment by PySimpleGUI** [comment]
Here's a change to the Tree Element .... it looks a lot  better, BUT...


![image](https://user-images.githubusercontent.com/46163555/71419104-d499da00-263b-11ea-81bb-8af15c27f7b6.png)

I've got it figured out, sorta, on Linux, but I sadly won't be able to do it on Windows.

tkinter is simply unable to get to those settings even though the exact same code is used for both my windows tests and my linux tests.

It leaves the question of whether I do this just for the Linux (and maybe Mac?) users.  It's a terrible thing in the end not being able to have consistent windows.  No doubt people will complain that it works on Linux but not windows.

**Comment by PySimpleGUI** [comment]
This tkinter documentation states it plainly... this is for tk in general, not even just the Python port but rather all ports.

Command-Line Name: -troughcolor
Database Name: troughColor
Database Class: Background
Specifies the color to use for the rectangular trough areas in widgets such as scrollbars and scales. This option is ignored for scrollbars on Windows (native widget does not recognize this option).

**Comment by Aboghazala** [comment]
if this is a limitation for windows i think better to dump this idea and keep scrollbars without coloring, 

consistency is much important,  so your windows will look the same on any platform "just my opinion"

**Comment by PySimpleGUI** [comment]
Yea, excellent point!  

Simple + Consistent == Better
