### ISSUE TITLE
uGet performs higher downloading speed than PyIDM.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#100]
Hi,

I try to compare the performance between uGet using the curl as the backend and PyIDM. It seems uGet gives higher downloading speed than PyIDM for my case on Ubuntu 20.04.

To be more specific, the former gives a mean downloading speed around 38 MB/s, while the latter only about 28 MB/s.

The former is written in c, while the latter is based on python, I don't know whether this is the bottleneck for PyIDM observed by me. Or maybe some job can be done in the downloading algorithm to enhance the performance of PyIDM.

Regards

**Comment by pyIDM** [comment]
Not a python problem, i just slow it down because some streaming sites will throttle or block connections temporarily if you didn’t wait enough between connections 

Still you can tweak it
If you check file brain.py and change value at line number 104 

limited_connections = 1  
To 
limited_connections = 100

And line 222
time.sleep(0.1)
To 
time.sleep(0.01)

And  give it a try, 
you might also play with connections number or segment size

**Comment by hongyi-zhao** [comment]
> Not a python problem, i just slow it down because some streaming sites will throttle or block connections temporarily if you didn’t wait enough between connections

You shouldn't impose these limitations for all, instead you can only apply it for stream media.

> 
> Still you can tweak it
> If you check file brain.py and change value at line number 104
> 
> limited_connections = 1
> To
> limited_connections = 100
> 
> And line 222
> time.sleep(0.1)
> To
> time.sleep(0.01)
> 
> And give it a try,

Thanks. I'll try it.

> you might also play with connections number or segment size

These settings should be done in real-time, segment size adjustable manner, just as we have discussed [in this thread](https://github.com/pyIDM/PyIDM/issues/97#issuecomment-635770628). And I think it should be done in this tool's inner algorithm instead of relying on user's trial and error.

**Comment by pyIDM** [comment]
> Tried with the above changes, but no significant speed increasement observed for the downloading process.

I think changing segment size dynamically might be the key to improve speed

> Based on my current experience, the rank of performance are as follows:
> IDM ( running within Wine ) > uGet > PyIDM

I did some tests before PyIDM vs IDM as a benchmark and difference in speed was very close and one of the tests PyIDM was faster than IDM
Still the fact that old man (IDM) is the king of speed.

**Comment by hongyi-zhao** [comment]
> > Tried with the above changes, but no significant speed increasement observed for the downloading process.
> 
> I think changing segment size dynamically might be the key to improve speed
> 
> > Based on my current experience, the rank of performance are as follows:
> > IDM ( running within Wine ) > uGet > PyIDM
> 
> I did some tests before PyIDM vs IDM as a benchmark and difference in speed was very close and one of the tests PyIDM was faster than IDM
> Still the fact that old man (IDM) is the king of speed.

IMO, there IDM maybe used many private technical algorithms to keep the highest speed during the whole downloading procedure. Say, tcp-session re-using, segment-size and connection-number adaptive adjustment, CDN-based optimized server mirrors finding for one downloading source, and so on.

**Comment by pyIDM** [comment]
As an update on this issue
After implementing dynamic file segmentation, does uGet still perform higher than PyIDM?

**Comment by hongyi-zhao** [comment]
I discarded the comparison between PyIDM and uGet. As you can see, the benchmark I'm used now is IDM. Basically to say, IDM and PyIDM evenly defeated by each other.

**Comment by pyIDM** [comment]
> I discarded the comparison between PyIDM and uGet. As you can see, the benchmark I'm using now is IDM. Basically to say, IDM and PyIDM ended in a draw based on my testing and observation currently.

Great, that we achieved this speed enhancement
thanks for your valuable suggestions
i will close this issue and mark it as done

**Comment by hongyi-zhao** [comment]
You are welcome.
