### ISSUE TITLE
The Python dbus package is needed but not listed in requirements.txt.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#101]
I noted the following info:

```
/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/plyer/platforms/linux/notification.py:68: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
```
It seems that  the Python dbus package is needed but not listed in requirements.txt.

Regards

**Comment by pyIDM** [comment]
This message from plyer library which is handling clipboard, 
it will look for xclip or xsel, then if not found will try to use dbus  or Qt, I already added a note on this topic in readme file here https://github.com/pyIDM/PyIDM#note-for-pyperclip-

if you don't have these on your system the application will continue to work with no problem 
PyIDM uses clipboard for:
- watch for any copied url "you can disable this in option"
- check if previous instant of PyIDM is running, and prevent running multi-instances of same application

so, it is not practical to put all this as a requirements, especially heavy thing like Qt for just an optional feature

**Comment by pyIDM** [comment]
Sorry, totally mixed plyer "for notification" and pyperclip

apparently plyer require dbus, which is not available in your virtual env
maybe this is related to this topic https://stackoverflow.com/questions/13365697/install-python-dbus-in-virtualenv

Anyhow, you won't lose much, plyer used to notify user with a message at systray area when a file finished downloading

I will close this issue, as this is an optional feature
