### ISSUE TITLE
Feature request: Automatically best mirror site finding. 

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#104]
Hi,

I noted the following interesting job done by IDM: it can automatically find best mirror site for specified URL based on the user's geolocation. Say, for the following file: `http://mirrors.ctan.org/systems/texlive/Images/texlive2020-20200406.iso`, IDM will automatically replace it with the following one for my case: `https://mirror.bjtu.edu.cn/CTAN/systems/texlive/Images/texlive2020-20200406.iso`. As a result, the downloading speed will be very high.

It should be another wonderful feature the potential users expected from PyIDM.

Regards

**Comment by pyIDM** [comment]
I think this is a server redirection and IDM has no control on this, I might be wrong, but let's verify this
try to paste this link in PyIDM http://mirrors.ctan.org/systems/texlive/Images/texlive2020-20200406.iso
when it finished loading click on the wooden board as shown below

![image](https://user-images.githubusercontent.com/58998813/83333814-c6af4b80-a2a2-11ea-8ef4-b91fd68eec74.png)

it will show a properties window with direct link, 
please check if this Direct url is the same as given by IDM in your location, 
in my location this is a different link

![image](https://user-images.githubusercontent.com/58998813/83333992-d4190580-a2a3-11ea-82f4-9cef2b184dd9.png)

**Comment by hongyi-zhao** [comment]
For my case, the URL still as the same after loading stage finished. I noted the following log info:

```
------------------------------------------- PyIDM --------------------------------------------------
>> Starting PyIDM version: 2020.5.25 Non-Frozen
>> operating system: Linux-5.4.0-33-generic-x86_64-with-glibc2.2.5 - x86_64
>> current working directory: /home/werner/Public/repo/github.com/pyIDM/PyIDM.git/pyidm
>> Load Application setting from /home/werner/Public/repo/github.com/pyIDM/PyIDM.git/pyidm
>> Load previous download items from /home/werner/Public/repo/github.com/pyIDM/PyIDM.git/pyidm
>> youtube-dl load_time= 1 seconds
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> looking for video streams ... Please wait
>> youtube_func()> processing: http://mirrors.ctan.org/systems/texlive/Images/texlive2020-20200406.iso
>> {'ignoreerrors': True, 'logger': youtube-dl Logger, 'writesubtitles': True, 'writeautomaticsub': True}
>> [generic] texlive2020-20200406: Requesting header
>> [redirect] Following redirect to http://iso.mirrors.ustc.edu.cn/CTAN/systems/texlive/Images/texlive2020-20200406.iso
>> [generic] texlive2020-20200406: Requesting header
>> Falling back on generic information extractor.
>> [generic] texlive2020-20200406: Downloading webpage
>> [generic] texlive2020-20200406: Extracting information
>> [0;31mERROR:[0m Unsupported URL: http://iso.mirrors.ustc.edu.cn/CTAN/systems/texlive/Images/texlive2020-20200406.iso
>> youtube_func()> No streams found

```

It seems PyIDM try to redirect to [here](http://iso.mirrors.ustc.edu.cn/CTAN/systems/texlive/Images/texlive2020-20200406.iso). Furthermore, when I try to open this URL in Firefox, I obtained the following info:

`You failed to pass our validation. Please use a normal browser or command line to download files. We expect your ip is 161.117.186.180 but we got 209.58.184.110 `

**Comment by pyIDM** [comment]
I am not sure how to fetch a list of mirrors from a website/load balancer
what actually done is a simple get request and server reply with headers, Libcurl will follow redirection "maybe a mirror website" if found in headers

if you know any technique to get get all mirror-list of remote server will re-open this issue

**Comment by hongyi-zhao** [comment]
I've tried with curl for several times and it seems the target URL is redirected to a random one:

```
werner@X10DAi-01:~/Desktop$ curl -sv --head http://mirrors.ctan.org/systems/texlive/Images/texlive2020-20200406.iso |& grep ^Location:
Location: http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/Images/texlive2020-20200406.iso
werner@X10DAi-01:~/Desktop$ curl -sv --head http://mirrors.ctan.org/systems/texlive/Images/texlive2020-20200406.iso |& grep ^Location:
Location: http://mirrors.hit.edu.cn/CTAN/systems/texlive/Images/texlive2020-20200406.iso
werner@X10DAi-01:~/Desktop$ curl -sv --head http://mirrors.ctan.org/systems/texlive/Images/texlive2020-20200406.iso |& grep ^Location:
Location: http://mirrors.nju.edu.cn/CTAN/systems/texlive/Images/texlive2020-20200406.iso

```

I'm also unsure whether libcurl has the capbility for obtaining all the mirror's URLs. 

Furthermore, even we have obtained the full list of the potential URLs, how can you test on them to find the best one?

**Comment by hongyi-zhao** [comment]
I posted the following issue on <curl-library@cool.haxx.se>

`Let libcurl return the full list of mirror's URLs for a downloading file.`

**Comment by pyIDM** [comment]
> I posted the following issue on curl-library@cool.haxx.se

Well let’s see if they have something

**Comment by hongyi-zhao** [comment]
Some of my ideas for doing the trick:

1. During the whole downloading process, let different workers try to re-establish the connection to the URL and get the redirected target URL. 
2. Based on the speed of the different target URL, kill the low-speed workers and reuse the URL which behaves high-speed.

**Comment by pyIDM** [comment]
This is too much difference in speed, almost 10x
The current implementation is as follows:
PyIDM will send a head request to website 
Website will reply with headers and in most cases will send target url “effective url”
The effective url will be used by all workers for downloading process

your suggestion is doable but need time to implement and test to see if it will increase connection time for every worker and the re-use of open tcp connections

**Comment by hongyi-zhao** [comment]
It seems the people on <curl-library@cool.haxx.se> don't interest on this issue considering that in essential it's a behavior of web server. The idea I suggested above and its algorithm implementation don't have much matter with libcurl itself, instead, it's It is a trick of network transmission just like the dynamic file segmentation technology.
