### ISSUE TITLE
Some ideas for enhancement of the current dynamic file segmentation algorithm.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#107]
Hi,

I suggest the following method for further enhancement the dynamic segmentation algorithm.

Log the avg. speed of all segments and then kill the segment which has much lower speed than the observed avg. speed of them and restart new workers or reuse the TCP session which has the highest speed. Repeat the above procedure till all the segments is completed.

Simply to say, kill the low-speed segments adaptively instead of relying on the predefined speed threshold and always try to use TCP connection which has the highest transfer speed without re-establishing the TCP sessions. Just some preliminary ideas. Sorry if I'm wrong.

I believe that libcurl, hence pycurl, is the No. 1 network library. Keep up your great and wonderful work. The PyIDM's performance is constantly approaching what IDM shows based on my observations and testings. To be more specific, IDM gives a max. 33MB/s speed, while PyIDM 29MB/s for my case. IMO, this is amazing progress compared to PyIDM's previous versions.

PyIDM comes. I expect that I will see, in the foreseeable near future, IDM been conquered. Long live open source.

Regards,
HY

**Comment by pyIDM** [comment]
I suspect that ThreadPoolExecutor might be the bottleneck
i will try to use normal threads and see if you can get to 33 MB/sec limit

**Comment by pyIDM** [comment]
@hongyi-zhao 
I just modified thread manager to use individual threads instead of ThreadPoolExecutor
please clone PyIDM and test if we are getting any more speed

**Comment by hongyi-zhao** [comment]
I tried with my office computer, the performances of IDM and PyIDM are as follows:

```
IDM: 12MB/s
PyIDM: 11MB/s 
```
It seems PyIDM's performance has been improved again. Wonderful job.

**Comment by pyIDM** [comment]
@hongyi-zhao 
Thanks for testing, still not sure where is the other bottlenecks
we need to make sure this is not a limitation of LibCurl itself
is it possible to test 
- IDM
- PyIDM
- Curl if installed
three with the same file and use maximum one connection in both IDM and PyIDM 
it will help a lot 
my connection is not fast enough for these tests

**Comment by hongyi-zhao** [comment]
The following testings are based on this [file](http://mirrors.tuna.tsinghua.edu.cn/ctan/systems/texlive/Images/texlive2020-20200406.iso). All with one connection and single thread. For curl, itself don't support multithread, so the direct use will be OK for this purpose.

```
IDM: 4.3 MB/s
curl: 4039KB/s ~= 4039/1024MB/s = 3.9443359375 MB/s
PyIDM: ~3.9MB/s
```

**Comment by pyIDM** [comment]
@hongyi-zhao 
This is interesting results, it shows our limit comes from LibCurl itself

Curl is a very strong and fast library written in “C”, with hundreds of active developers and IDM written in C++, 
Still don’t know how IDM is faster or
Do you think IDM might report “fake speed”?

**Comment by hongyi-zhao** [comment]
> @hongyi-zhao
> This is interesting results, it shows our limit comes from LibCurl itself
> 
> Curl is a very strong and fast library written in “C”, with hundreds of active developers and IDM written in C++,
> Still don’t know how IDM is faster or
> Do you think IDM might report “fake speed”?

If so, we can test the directly received data packages on the network interface for checking it. But I don't think IDM will do that meaningless thing.

**Comment by pyIDM** [comment]
> as a commercial technique company, this will damage its reputation without any added benefit.

i believe so, they won't do it

**Comment by hongyi-zhao** [comment]
> The following testings are based on the direct downloading for this [file](http://mirrors.tuna.tsinghua.edu.cn/ctan/systems/texlive/Images/texlive2020-20200406.iso) from my location. All with one connection and single thread. Curl, in itself, don't support multithread, so the direct use should appropriate for this purpose.
> 
> ```
> IDM: 4.3 MB/s
> curl: 4039KB/s ~= 4039/1024MB/s = 3.9443359375 MB/s
> PyIDM: ~3.9MB/s
> ```

I'll try to discuss this problem on the (lib)curl's list.

**Comment by pyIDM** [comment]
> I'll try to discuss this problem on the (lib)curl's list.

Sounds great 👍

**Comment by hongyi-zhao** [comment]
> The following testings are based on the direct downloading for this [file](http://mirrors.tuna.tsinghua.edu.cn/ctan/systems/texlive/Images/texlive2020-20200406.iso) from my location. All with one connection and single thread. Curl, in itself, don't support multithread, so the direct use should appropriate for this purpose.
> 
> ```
> IDM: 4.3 MB/s
> curl: 4039KB/s ~= 4039/1024MB/s = 3.9443359375 MB/s
> PyIDM: ~3.9MB/s
> ```

It seems that the tested website mentioned above has speed limit for single thread, so it's very appropriate for doing such comparisons.

**Comment by pyIDM** [comment]
> It seems that the website mentioned above has speed limit for single thread and the connection to it won't be redirected to different mirror URLs, so it should be very appropriate for doing such comparisons.

Agree, In this case we don’t have to worry about network or isp speed as an affecting factor

**Comment by hongyi-zhao** [comment]
Another simple method is construct a local HTTP site and then using it for testings.

**Comment by pyIDM** [comment]
> Another simple method is building a local HTTP site and then using it for testings. This is basically benchmarks for protocol and algorithms which are the things we can control and tune on.

I am already using a very simple local server, which serve files from local folder, i use time.sleep as a speed limit "for every connection"


```
from flask import Flask, request, Response, abort
import time, os


app = Flask(__name__)


@app.route('/headers')
def echo_headers():
    buffer = ''
    for k, v in request.headers.items():
        buffer += f'{k}: {v} <br />'
    return buffer


def limit_speed(speed):
    """limit speed in kb/sec by simply sleep"""
    delay = 1/speed
    time.sleep(delay)


def chunker(file, chunk_range):
    """read byte range from target file, it will send a small packets "1 KB size" 
    with a delay between them to limit speed"""
    chunk_range = chunk_range.split('=')[-1].split('-')  # [0, 100]
    chunk_range = [int(x) for x in chunk_range]
    chunk_size = chunk_range[1] - chunk_range[0] + 1
    
    with open(file, 'rb') as f:
        f.seek(chunk_range[0])
        buf = f.read(chunk_size)

        buf_list = []
        packet_size = min(1024, chunk_size)  # 1 KB
        packet_numbers = chunk_size // packet_size
        remainder = chunk_size % packet_size

        for i in range(packet_numbers):
            start = i * packet_size
            end = (start + packet_size - 1) if i < packet_numbers-1 else (start + packet_size + remainder - 1) 
            buf_list.append(buf[start:end + 1])            

        for data in buf_list:
            limit_speed(1024)  # approximate speed limit in KB/s for every connection

            yield data
    

@app.route('/<file>')
def download(file):
    try:
        # file size 
        size = os.path.getsize(file)

        # get range ex: Range: bytes=0-100
        chunk_range = request.headers.get('Range', f'{0}-{size-1}')
            
        return Response(chunker(file, chunk_range), headers={'content-length':size, 'content-type': 'unknown', 'accept-ranges': 'true'})
    except Exception as e:
        abort(404)  # not found response
        print(e)
        


if __name__ == "__main__":
    app.run(debug=True, port=8000, threaded=True)

```

**Comment by hongyi-zhao** [comment]
Have you used the above codes for testing the performance of PyIDM?

A side-note, I think if we compare the performance of the PyIDM and IDM, we should do the tests with one connection, single-thread downloading with pycurl/libcurl and IDM considering that PyIDM is based on pycurl.

**Comment by pyIDM** [comment]
> Have you used the above codes for testing the performance of PyIDM?
> 
> A side-note, I think if we compare the performance of the PyIDM and IDM, considering that PyIDM is based on pycurl, we should do the tests with one connection, single-thread downloading for both pycurl/libcurl and IDM.

I used local server when i was fixing file downloading corruption and automatic file segmentation 
Didn’t use it for performance testing 

You are right, the comparison should be Curl vs IDM and you already done a test and IDM shows faster speed 
Maybe curl needs some tweaking - not sure yet -

**Comment by hongyi-zhao** [comment]
> def limit_speed(speed):
>     """limit speed in kb/sec by simply sleep"""
>     delay = 1/speed
>     time.sleep(delay)

Why define delay like this instead of using an absolute value?

**Comment by pyIDM** [comment]
I think it is easier this way, say i want to limit speed to `50 KB/sec` i will write `limit_speed(50)`

i wrote this code in hurry because i wanted something to test file download, for sure it is buggy, but it works somehow
i changed some lines to serve files in subfolders and fixed the size in response headers

here it is after mods

```
from flask import Flask, request, Response, abort
import time, os

current_path = os.path.realpath(os.path.abspath(__file__))
current_path = os.path.dirname(current_path)

app = Flask(__name__)

@app.route('/headers')
def echo_headers():
    buffer = ''
    for k, v in request.headers.items():
        buffer += f'{k}: {v} <br />'
    return buffer


def limit_speed(speed):
    """limit speed in kb/sec by simply sleep"""
    delay = 1/speed
    time.sleep(delay)


def chunker(file, chunk_range):
    """read byte range from target file, it will send a small packets "1 KB size" 
    with a delay between them to limit speed"""
    chunk_size = chunk_range[1] - chunk_range[0] + 1
    
    with open(file, 'rb') as f:
        f.seek(chunk_range[0])
        buf = f.read(chunk_size)

        if len(buf) <= 1024:
            return buf

        buf_list = []
        packet_size = min(1024, chunk_size)  # 1 KB
        packet_numbers = chunk_size // packet_size
        remainder = chunk_size % packet_size

        for i in range(packet_numbers):
            start = i * packet_size
            end = (start + packet_size - 1) if i < packet_numbers-1 else (start + packet_size + remainder - 1) 
            buf_list.append(buf[start:end + 1])            

        for data in buf_list:
            limit_speed(1024)  # approximate speed limit in KB/s (around 1 MB)

            yield data
    

@app.route('/<path:file>')
def download(file):
    try:
        file = os.path.join(current_path, file)
        # print(file)
        # file size 
        size = os.path.getsize(file)

        # get range ex: Range: bytes=0-100
        chunk_range = request.headers.get('Range', f'{0}-{size-1}')

        chunk_range = chunk_range.split('=')[-1].split('-')  # [0, 100]
        chunk_range = [int(x) for x in chunk_range]
        chunk_size = chunk_range[1] - chunk_range[0] + 1
            
        return Response(chunker(file, chunk_range), headers={'file':file, 'content-length':chunk_size, 'content-type': 'unknown', 'accept-ranges': 'true'})
    except Exception as e:
        abort(404)  # not found response
        


if __name__ == "__main__":
    app.run(debug=True, port=8000, threaded=True)

```

**Comment by hongyi-zhao** [comment]
> > I'll try to discuss this problem on the (lib)curl's list.
> 
> Sounds great +1

I've posted the following issue. If you are interest on it, you can give your attention on the replies.

```
发件人： | Hongyi Zhao <hongyi.zhao@gmail.com>
-- | --
收件人： | the curl tool <curl-users@cool.haxx.se>、libcurl development <curl-library@cool.haxx.se>
日期： | 2020年6月14日 下午12:59
主题： | Curl's network performance is slower than IDM.
邮送域： | gmail.com

```

**Comment by pyIDM** [comment]
@hongyi-zhao 
great work
I will follow up on https://curl.haxx.se/mail/lib-2020-06/0038.html

**Comment by hongyi-zhao** [comment]
@pyIDM Have you followed up the discussions about the above thread. 
Daniel Stenberg and me said the following:
> It's not so much a threading issue as multiple TCP connections

Still interesting again. Is there any example for libcurl to establish
multiple TCP connections within one threading? 

Any hints/comments?

Regards,
HY

**Comment by pyIDM** [comment]
Yes I follow up your conversation with Daniel Stenberg the maker of curl

I don’t think you can open multiple tcp connections asking for the same chunk range of data 
For example curl-multi can run multiple easy handles from one thread but still every handle will request different chunk range from server then your application will concatenate these chunks into one file

Otherwise you will get the same data over and over

I believe he meant IDM might use multi-connections silently ignoring your settings 
The only way to make sure it can’t do this is to download a file from a server which doesn’t support “range requests” which the server doesn’t have ‘Accept-Ranges: bytes’ in response headers

You can easily identify this by pasting url in PyIDM and it will show ‘Resumable: No’ 
If i find an example url i will send to you
