### ISSUE TITLE
Incorrect path for ffmpeg when installed using snap

### ISSUE THREAD

**Issue by Hunsu** [pyIDM/PyIDM#120]
pyIDM recognize /usr/bin/snap as the executable for ffmpeg. I installed ffmpeg using snap and `which ffmpeg`is returning `/snap/bin/ffmpeg`but this path is a link to `/usr/bin/snap`.
As a workaround I did `ln -s /snap/bin/ffmpeg /usr/bin/ffmpeg` and it works.

**Comment by pyIDM** [comment]
@Hunsu 
Good job for the workaround 
I am not sure if there is a reliable solution for this problem 
Any suggestions are welcomed
