### ISSUE TITLE
PyIDM review and a few suggestions to make it the best

### ISSUE THREAD

**Issue by mx202** [pyIDM/PyIDM#122]
Hello,

I would like to tell you that the PyIDM program is a wonderful program and I think it has a brilliant future in the popularity of the program and its use by millions of people, and this is through my experience in using different download managers for several years

And I would like to give you some notes, some problems, and ways to develop the program and could make the program much better and perhaps a competitor to the IDM program

1/The download speed is really faster than any open source software I have ever tested, it is almost like IDM but it varies a lot. Som keep that in mind and hope to be fixed soon.

2 / Please create a browser add-on directly linked to the PyIDM program (Directly, but not external native client patch) and this add-on intercept the download links and transfer them directly to the main program when clicking on the download links and also recognize all video formats on all sites (not only Youtube) and send the video download links to the PyIDM program.

both of these two software has an advantage of using this feature:
A. Internet Download Manager (IDM)
B. Xtreme Download Manager (XDM) open source on github
https://github.com/subhra74/xdm

3 / The dialog box should appear above the video on the sites and identify all the qualities available for download.
![2 IDM](https://user-images.githubusercontent.com/66641103/85336654-a3656e00-b4e7-11ea-9eb5-c29d86e2f2d7.jpg)
![3 IDM](https://user-images.githubusercontent.com/66641103/85336657-a4969b00-b4e7-11ea-8a84-bd62ec2f7472.jpg)
![5 XDM](https://user-images.githubusercontent.com/66641103/85336658-a5c7c800-b4e7-11ea-81e2-2ae6872d32c8.jpg)

4 / The program's graphical interface should be redesigned to make it more attractive, modern and easy, like IDM and Flareget and Ariafx
The beautiful design is important for attracting users, is comfortable for the eye and encourages the continued use of the program.

These are screenshots of the mentioned programs
![1 IDM](https://user-images.githubusercontent.com/66641103/85336758-ddcf0b00-b4e7-11ea-8c2b-986c02286d05.jpg)
![4 Flareget](https://user-images.githubusercontent.com/66641103/85336766-e0c9fb80-b4e7-11ea-8ce9-e9664ebcff32.jpg)
![ariafx08](https://user-images.githubusercontent.com/66641103/85341856-e75d7080-b4f1-11ea-934a-f66394eec439.png)

5 / Flatpak version should be created for Linux to make it easy to install which you already promised to do. So, thank you

That's what I would recommend and I'm sure that PyIDM will be the best download manager in the near future

Thank you a lot

Best regard

**Comment by pyIDM** [comment]
Thanks for your feedback
will consider your points of view in future
