### ISSUE TITLE
About the current strategy for reusing the dirty/unfinished segment when resuming job.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#123]
Hi,

I'm still not clear on the current strategy for reusing the dirty/unfinished segment when resuming job. Will it be discarded or truncated to some extent for safe reusing?

Regards,
HY

**Comment by pyIDM** [comment]
To make it simple, say we have a segment with 100 bytes size, and bytes range property [0, 99], and download interrupted/cancelled after downloading 60 bytes only,
When resuming this segment, app. Will check actual segment size on the disk “60 bytes in our example”, and recalculate the new range which will be [60, 99] 
A “GET” request will be sent to the server asking for remainig data with a new calculated chunk range in headers 
Received data will be appended to the segment until actual size on disk match target size, then segment will be marked as downloaded

**Comment by hongyi-zhao** [comment]
> To make it simple, say we have a segment with 100 bytes size, and bytes range property [0, 99], and download interrupted/cancelled after downloading 60 bytes only,
> When resuming this segment, app. Will check actual segment size on the disk “60 bytes in our example”, and recalculate the new range which will be [60, 99]

Still, I'm not very clear on the addressing method used here. In detail, for a huge file downloaded by dynamic file segmentation technology, how to quickly and efficiently anchor at the accurate starting location of this segment?

> A “GET” request will be sent to the server asking for remainig data with a new calculated chunk range in headers
> Received data will be appended to the segment until actual size on disk match target size, then segment will be marked as downloaded

Do you mean there is a log file which is used to store this information?

**Comment by pyIDM** [comment]
To make things simple let’s imagine we need to download a file named xyz.zip and for sake of simplicity will pretend it has a total size of 400 bytes
- once you paste url in pyidm it will send Head request to get headers from server
- say the server sent “content-length: 400” and it accepts range requests 
- assume we set max. 2 workers and start downloading 
- first will prepare segment list, we will have 2 segments “equal to available workers number”, each segment size will be 200 bytes as a target size
To be clear we’ll have: 
    - segment1: size=200 bytes, range=[0, 199]
    - segment2: size=200 bytes, range=[200, 399]

Assume worker1 finished downloading segment1 and worker2 still downloading segment2

Here is the auto-segmentation role comes, will check how much left in segment2, say for example 100 bytes remaining “and 100 bytes downloaded”, we will create new segment and will be as follows:
    - segment3: size=50 bytes, range=[350, 399]

And modify segment2 to be:
    - segment2: size=150 bytes, range=[200, 349]

Note, we will not interrupt worker2, and it will continue receive data from server and terminate connection when segment2 actual size on diske is equal or greater than new size (150 kb)

Will continue repeat this process as long as we have Free workers, and remaining segment size is more than predefined value 

All segments will be saved on disk in a temp folder, also file named progress.txt will be saved in same folder containing segments information for future resume

On other hand there is a file manager which merge any download segment into a temp file in our example will be “_temp_xyz.zip”, every segment will be copied to this file based on its range proerty, to match file structure on remote server

After all done will rename temp file to final name “xyz.zip”, then delete temp folder

Hope I answered your question

**Comment by hongyi-zhao** [comment]
Thanks a lot for your explanation. Based on your above notes, I noticed the following temp directory/files during the downloading of texlive2020-20200406.iso:
```
werner@X10DAi-01:~/Downloads/_temp_texlive2020-20200406.iso_parts_$ ls -la
total 505172
drwxrwxr-x  2 werner werner     4096 Jun 21 21:19 .
drwxr-xr-x 21 werner werner    49152 Jun 23 20:36 ..
-rw-rw-r--  1 werner werner 68489390 Jun 23 20:40 0
-rw-rw-r--  1 werner werner 67504020 Jun 23 20:40 1
-rw-rw-r--  1 werner werner 66253635 Jun 23 20:40 2
-rw-rw-r--  1 werner werner 64850402 Jun 23 20:40 3
-rw-rw-r--  1 werner werner 61843924 Jun 23 20:40 4
-rw-rw-r--  1 werner werner 63777526 Jun 23 20:40 5
-rw-rw-r--  1 werner werner 61727540 Jun 23 20:40 6
-rw-rw-r--  1 werner werner 62736470 Jun 23 20:40 7
-rw-rw-r--  1 werner werner     1563 Jun 21 21:21 progress_info.txt
```
