### ISSUE TITLE
Feature request: Dynamically adjustable total segment numbers for a downloading job.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#126]
Hi,

Based on my understanding for the current segmentation algorithm used by PyIDM, it seems that the total segment numbers stored in the progress_info.txt is unchangeable. How about dynamically adjustable total segment numbers for a downloading job?

This is useful when the server doesn't support too many concurrent connections. OTOH, if the server can support more concurrent connections, we can increase the number of connections in real-time.

**Comment by pyIDM** [comment]
Segments number is totally random and depend on individual connection / worker speed

For example if you have 8 workers you will have 8 segments, and if one worker finished downloading before the others a new segment will be created to use this free worker, there is no limit to how many new segments can be created, as long as there is a free workers  

In case all workers finished simultaneously, the total segments number will equal to workers number, why make new segments if all workers are busy and doing good job

Case when server (for example) support max. 4 connections and you have 8 workers, you will get 404 or 503 error for connections more than 4, the bad thing is not only extra connections will be dropped, but all connections will be droped, 

The good thing is PyIDM can control and limit connections number automatically 
See issue #75

**Comment by hongyi-zhao** [comment]
> Segments number is totally random and depend on individual connection / worker speed
> 
> For example if you have 8 workers you will have 8 segments, and if one worker finished downloading before the others a new segment will be created to use this free worker, there is no limit to how many new segments can be created, as long as there is a free workers
> 
> In case all workers finished simultaneously, the total segments number will equal to workers number, why make new segments if all workers are busy and doing good job
> 
> Case when server (for example) support max. 4 connections and you have 8 workers, you will get 404 or 503 error for connections more than 4, the bad thing is not only extra connections will be dropped, but all connections will be droped,

Is this the http server side's standard behavior?

> 
> The good thing is PyIDM can control and limit connections number automatically
> See issue #75

Thanks a lot for letting me knowing this interesting feature.

**Comment by pyIDM** [comment]
> Is this the http server side's standard behavior?

this is based on observation done during file download testing, some servers will drop all connections once you exceeded their preset max. connections, and other servers will drop only the extra connections and keep the already established connections intact.

**Comment by hongyi-zhao** [comment]
Ok, got it.

A side note, just as I've posted here, if using a socks5 proxy which in itself is a load balancer gateway with many upstream socks5 servers, the max. concurrent connections' problem will be hacked. This is because, in most cases, the server is based on the source address to set the max. concurrent connections number. If we connect to server through a load balancer which enables some round-robin like algorithms, the server will see different source addresses, hence shouldn't set the max. concurrent connections number for each of them.

**Comment by pyIDM** [comment]
> the server will see different source addresses

in this case the server will be fooled and can't see where is the hit is coming from, then server will fail to limit connections

but it is always a mouse vs cat game, for example server can get the original client ip behind the proxy from "X-FORWARD FOR" header, which include source ip and proxy ip

then client can fool server again be edit "X-FORWARD FOR" header and set random  ip with every request

it is a messy game :)

**Comment by hongyi-zhao** [comment]
> > the server will see different source addresses
> 
> in this case the server will be fooled and can't see where is the hit is coming from, then server will fail to limit connections
> 
> but it is always a mouse vs cat game, for example server can get the original client ip behind the proxy from "X-FORWARD FOR" header, which include source ip and proxy ip
> 
> then client can fool server again be edit "X-FORWARD FOR" header and set random ip with every request

If so, even without using the multiple upstream socks5 proxies, still can we cheat the server successfully with this trick?

> 
> it is a messy game :)

**Comment by pyIDM** [comment]
> If so, even without multiple upstream socks5 proxies through as the backend of the really used load balancer socks5 proxy, whether we can still cheat the server with this trick, i.e., sending different faked "X-FORWARD FOR" header for each thread belong to the same downloading job?

I’m not sure if it will work, reading this answer in stackoverflow will give you hints how server can get your ip from different resources 

https://stackoverflow.com/a/15699240

You need to manipulate every resource and you might get a forbidden response from server after all
