### ISSUE TITLE
Screenshots links

### ISSUE THREAD

**Issue by Aboghazala** [pyIDM/pyIDM#13]
This thread will be dedicated to all app. screenshots to keep it away from source code and link it to readme file

![main_reds](https://user-images.githubusercontent.com/37757246/71418544-a20bd380-2673-11ea-903c-ea5ea17e0e26.png)

![downloads_reds_2](https://user-images.githubusercontent.com/37757246/71418538-a0daa680-2673-11ea-82a8-e10e0ca673bd.PNG)

![dwindow](https://user-images.githubusercontent.com/37757246/71418539-a0daa680-2673-11ea-8073-0c217fff7e9a.png)

![setting_reds](https://user-images.githubusercontent.com/37757246/71418549-a2a46a00-2673-11ea-848a-ca5ca82e743b.PNG)

![log_reds](https://user-images.githubusercontent.com/37757246/71418540-a1733d00-2673-11ea-9d6f-fa9daf49e612.PNG)

![multi-3](https://user-images.githubusercontent.com/37757246/71418548-a2a46a00-2673-11ea-8101-c95d29b6a0e4.png)

![main_black](https://user-images.githubusercontent.com/37757246/71418541-a1733d00-2673-11ea-85c3-cd6f6b2d66c1.PNG)

![main_dark2](https://user-images.githubusercontent.com/37757246/71418542-a20bd380-2673-11ea-91d8-c8ebecb48d04.PNG)

![main_kayak](https://user-images.githubusercontent.com/37757246/71418543-a20bd380-2673-11ea-90da-f01b55bd3afd.PNG)

**Comment by pyIDM** [comment]
![playlist_download](https://user-images.githubusercontent.com/58998813/71648887-b35b7c80-2d12-11ea-8bd4-2143337dbc3c.png)

**Comment by pyIDM** [comment]
![stream_menu](https://user-images.githubusercontent.com/58998813/71775067-10f60000-2f83-11ea-9ad4-2bbd3d6916e6.png)

**Comment by pyIDM** [comment]
![playlist2](https://user-images.githubusercontent.com/58998813/71775076-22d7a300-2f83-11ea-8011-b45f2f2605f4.png)

**Comment by pyIDM** [comment]
![image](https://user-images.githubusercontent.com/58998813/74782663-8a844c00-52ac-11ea-9138-59e54058146e.png)

**Comment by pyIDM** [comment]
![Florida_HLS](https://user-images.githubusercontent.com/58998813/74883072-da304980-5378-11ea-81c5-a4a7a22fbb5f.gif)

**Comment by pyIDM** [comment]
aria2c vs pyIDM
  speed test

max. connections = 8, chunk size = 1MB
File: videoplayback.mp4, size: 59.8 MB
url: https://r4---sn-uxaxjv..._W92N525xyw%3D%3D

aria2c -x8 -k1M --dir="d:\test\aria" "https://r4---sn-uxaxjv..._W92N525xyw%3D%3D"


![aria2c_vs_pyidm2](https://user-images.githubusercontent.com/58998813/74982498-ed0c5200-543c-11ea-915d-0c616f6480e0.gif)

**Comment by pyIDM** [comment]
aria2c vs pyIDM
  speed test

max. connections = 8, chunk size = 1MB
File: ubuntu-19.10-desktop-amd64.iso, 
size: 1.98 GB
url:http://mirrors.manchester.m247.com/ubuntu-releases/19.10/ubuntu-19.10-desktop-amd64.iso
area2 cmd: C:\Users\mea\Downloads\1\aria2c\aria2c -x8 -k1M --dir="d:\test\aria" --file-allocation=none "http://mirrors.manchester.m247.com/ubuntu-releases/19.10/ubuntu-19.10-desktop-amd64.iso"

results: pyIDM almost 1.5 times faster than aria2c

![aria2c_vs_pyidm_speed](https://user-images.githubusercontent.com/58998813/74993622-361bd080-5454-11ea-8bda-173bfcf16349.gif)

**Comment by pyIDM** [comment]
HLS stream
![Wild_Florida_HLS](https://user-images.githubusercontent.com/58998813/74996093-4edbb480-545b-11ea-9b3c-a5b12740d21f.gif)

**Comment by pyIDM** [comment]
New GUI design_ Main Tab with thumbnail preview, still in progress

![image](https://user-images.githubusercontent.com/58998813/77215158-56a27d80-6b1b-11ea-8c7f-43abce53f1d3.png)

**Comment by pyIDM** [comment]
version 2020.3.20 screenshots

![main_tab](https://user-images.githubusercontent.com/58998813/77240732-e155ac00-6bf1-11ea-8cd0-edc5facaa46a.PNG)

![downloadWindow2](https://user-images.githubusercontent.com/58998813/77240738-ed416e00-6bf1-11ea-811d-32e5a282de1f.PNG)

![downloads](https://user-images.githubusercontent.com/58998813/77240740-f16d8b80-6bf1-11ea-8579-1705dd750bfd.PNG)

![settingsPart1](https://user-images.githubusercontent.com/58998813/77240742-f9c5c680-6bf1-11ea-860a-a434dcba599e.PNG)

![settingsPart2](https://user-images.githubusercontent.com/58998813/77240744-fdf1e400-6bf1-11ea-92c6-bf2297524a80.PNG)

![log](https://user-images.githubusercontent.com/58998813/77240747-0518f200-6bf2-11ea-905e-ffc0d9985a10.PNG)

**Comment by pyIDM** [comment]
![bigcats4](https://user-images.githubusercontent.com/58998813/77242050-2d5d1c80-6c03-11ea-8151-b85a897ff9fb.gif)

**Comment by pyIDM** [comment]
choose dash audio format manually
![image](https://user-images.githubusercontent.com/58998813/78213884-28765380-74b4-11ea-8f06-57c007f5e217.png)
![image](https://user-images.githubusercontent.com/58998813/78213994-6bd0c200-74b4-11ea-9ba9-144a006d6580.png)

**Comment by pyIDM** [comment]
version 2020.3.31 changes
![settings1of3](https://user-images.githubusercontent.com/58998813/78214405-75a6f500-74b5-11ea-838f-c7ad95b722ed.PNG)
![settings2of3](https://user-images.githubusercontent.com/58998813/78214411-793a7c00-74b5-11ea-9179-68902d5cffff.PNG)
![settings3of3](https://user-images.githubusercontent.com/58998813/78214419-7c356c80-74b5-11ea-869f-1560cf5e2f78.PNG)
![downloads4](https://user-images.githubusercontent.com/58998813/78214514-bb63bd80-74b5-11ea-8d13-e3fce537394d.PNG)

**Comment by pyIDM** [comment]
![image](https://user-images.githubusercontent.com/58998813/79058959-9a008f80-7c74-11ea-82da-8a1ff9f7bc6a.png)

**Comment by pyIDM** [comment]
![image](https://user-images.githubusercontent.com/58998813/81216709-a2ca5400-8fdb-11ea-83a6-f4a09de95198.png)

**Comment by pyIDM** [comment]
![cookies2](https://user-images.githubusercontent.com/58998813/90165536-16c58680-dd99-11ea-99a8-edaec07246e5.png)

**Comment by pyIDM** [comment]
proxy example:
![image](https://user-images.githubusercontent.com/58998813/90170091-cb62a680-dd9f-11ea-8cd2-2356ad1e964f.png)

**Comment by pyIDM** [comment]
New GUI design using tkinter ... coming soon
![image](https://user-images.githubusercontent.com/58998813/92562020-939f2f80-f275-11ea-94ea-fe41c9c72abc.png)
![image](https://user-images.githubusercontent.com/58998813/92562098-b598b200-f275-11ea-9b43-0cc93fb82f31.png)
![image](https://user-images.githubusercontent.com/58998813/92562130-bfbab080-f275-11ea-990d-c869522ecbaa.png)
![image](https://user-images.githubusercontent.com/58998813/92562716-b4b45000-f276-11ea-9810-177f6f69486b.png)

**Comment by pyIDM** [comment]
more screenshots
playlist:
![pl_main](https://user-images.githubusercontent.com/58998813/94432366-f3af3480-0196-11eb-8449-3e35bfb13e5c.png)
![pl_window](https://user-images.githubusercontent.com/58998813/94432385-fb6ed900-0196-11eb-893a-bd79accd9b4a.png)

Audio:
![audio](https://user-images.githubusercontent.com/58998813/94432501-26f1c380-0197-11eb-9d25-59cbef8c2279.png)
![dash audio](https://user-images.githubusercontent.com/58998813/94432513-2b1de100-0197-11eb-86d5-6cd27763fba6.png)

popups:
![overwrite_warning](https://user-images.githubusercontent.com/58998813/94434035-76d18a00-0199-11eb-95a5-18c942e45830.png)

![resume_warning](https://user-images.githubusercontent.com/58998813/94433926-4b4e9f80-0199-11eb-8588-ff07961dc07f.png)

Subtitle download:
![sub_menu](https://user-images.githubusercontent.com/58998813/94432649-5acce900-0197-11eb-98f5-d47221859dae.png)

Theme Editor:
![theme_editor](https://user-images.githubusercontent.com/58998813/94432668-628c8d80-0197-11eb-9276-0f7d778c244f.png)

Settings
![s1](https://user-images.githubusercontent.com/58998813/94432701-6f10e600-0197-11eb-9d5a-397980d8fa57.png)
![s2](https://user-images.githubusercontent.com/58998813/94432706-70421300-0197-11eb-83d3-6be27caf841a.png)
![s3](https://user-images.githubusercontent.com/58998813/94432708-70daa980-0197-11eb-95ee-e89ff05a46b2.png)

**Comment by pyIDM** [comment]
Dark
![image](https://user-images.githubusercontent.com/58998813/105612284-c597d500-5dc3-11eb-9ac7-b973507dd887.png)

**Comment by firedm** [comment]
![image](https://user-images.githubusercontent.com/58998813/134947078-f87ba2e9-35b3-4edf-8acf-c4c3e8c6b46f.png)
