### ISSUE TITLE
Failed to download specific video

### ISSUE THREAD

**Issue by Tox86** [pyIDM/PyIDM#130]
A  mistery...

https://imgur.com/4uiWPC2

Cheers..

**Comment by pyIDM** [comment]
@Tox86 
This bug is affecting all fragmented videos and it is already fixed and will be included  in the coming release 
Will let you know once done

**Comment by pyIDM** [comment]
@Tox86 
just released a new version 2020.6.27 including the fix
windows portable https://github.com/pyIDM/PyIDM/releases/latest
PyPi: https://pypi.org/project/PyIDM/2020.6.27/

**Comment by Tox86** [comment]
Again:
![bug](https://user-images.githubusercontent.com/7013508/86541592-21f4df00-bedc-11ea-8262-4d1a3e92f7c6.PNG)

Video:
https://www.youtube.com/watch?v=Bo67PfE4wxc

**Comment by pyIDM** [comment]
@Tox86 
I tried to download this video multiple times and it works every time without a problem 
did you try again?
does it show any details in log tab, when it fails?

**Comment by Tox86** [comment]
Ok, i'm try delete the pyIDM folder.

**Comment by Tox86** [comment]
`>> start downloading file: "Doja Cat - Say so - Guitar Chords and Impro.mp4", size: ..., to: C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2
>> Thread Manager()> concurrency method: Individual Threads
>> Thread Manager: allowable connections: 2
>> Seg 0 start, size: ... - range: None  - worker 9
>> Seg 1 start, size: ... - range: None  - worker 4
>> downloaded segment:  0 None 741 bytes - worker 9
>> Seg 2 start, size: ... - range: None  - worker 6
>> completed segment:  0
>> downloaded segment:  1 None 1.9 MB - worker 4
>> Thread Manager: allowable connections: 3
>> Seg 3 start, size: ... - range: None  - worker 5
>> Seg 4 start, size: ... - range: None  - worker 2
>> completed segment:  1
>> downloaded segment:  2 None 2.2 MB - worker 6
>> Seg 5 start, size: ... - range: None  - worker 1
>> completed segment:  2
>> Thread Manager: allowable connections: 4
>> Seg 6 start, size: ... - range: None  - worker 3
>> downloaded segment:  4 None 2.3 MB - worker 2
>> Thread Manager: allowable connections: 5
>> Seg 7 start, size: ... - range: None  - worker 0
>> Seg 8 start, size: ... - range: None  - worker 8
>> downloaded segment:  6 None 2.0 MB - worker 3
>> Seg 9 start, size: ... - range: None  - worker 7
>> downloaded segment:  3 None 2.3 MB - worker 5
>> Seg 10 start, size: ... - range: None  - worker 9
>> Thread Manager: allowable connections: 6
>> Seg 11 start, size: ... - range: None  - worker 4
>> completed segment:  3
>> completed segment:  4
>> downloaded segment:  5 None 2.4 MB - worker 1
>> Seg 12 start, size: ... - range: None  - worker 6
>> completed segment:  5
>> completed segment:  6
>> Thread Manager: allowable connections: 7
>> Seg 0_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 5
>> downloaded segment:  0_audio None 632 bytes - worker 5
>> Seg 1_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  7 None 2.2 MB - worker 0
>> downloaded segment:  1_audio None 158 KB - worker 2
>> Seg 2_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 1
>> Seg 3_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 3
>> completed segment:  7
>> downloaded segment:  3_audio None 158 KB - worker 3
>> Thread Manager: allowable connections: 8
>> Seg 4_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 0
>> downloaded segment:  8 None 1.9 MB - worker 8
>> Seg 5_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 5
>> Seg 6_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  2_audio None 158 KB - worker 1
>> Seg 7_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 1
>> completed segment:  8
>> downloaded segment:  4_audio None 158 KB - worker 0
>> downloaded segment:  6_audio None 158 KB - worker 2
>> downloaded segment:  5_audio None 158 KB - worker 5
>> downloaded segment:  7_audio None 74 KB - worker 1
>> downloaded segment:  12 None 1.2 MB - worker 6
>> downloaded segment:  9 None 2.1 MB - worker 7
>> downloaded segment:  11 None 2.0 MB - worker 4
>> completed segment:  9
>> downloaded segment:  10 None 2.2 MB - worker 9
>> completed segment:  10
>> completed segment:  11
>> completed segment:  12
>> completed segment:  0_audio
>> completed segment:  1_audio
>> completed segment:  2_audio
>> completed segment:  3_audio
>> completed segment:  4_audio
>> completed segment:  5_audio
>> completed segment:  6_audio
>> completed segment:  7_audio
>> handling dash videos
>> merging video and audio
>> running command: "C:\Users\fabia\Desktop\PyIDM\ffmpeg.exe" -loglevel error -stats -y -i "C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2\_temp_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4" -i "C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2\audio_for_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4" -c copy "C:\Users\fabia\Desktop\Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2\Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4"
>> C:\Users\fabia\Desktop\Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2\Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4: No such file or directory
>> running command: "C:\Users\fabia\Desktop\PyIDM\ffmpeg.exe" -loglevel error -stats -y -i "C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2\_temp_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4" -i "C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2\audio_for_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4" "C:\Users\fabia\Desktop\Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2\Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4"
>> C:\Users\fabia\Desktop\Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2\Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4: No such file or directory
>> run_command()> cancelled ['C:\\Users\\fabia\\Desktop\\PyIDM\\ffmpeg.exe', '-loglevel', 'error', '-stats', '-y', '-i', 'C:\\Users\\fabia\\Desktop\\Jamey Arent Guitar For Complete Beginners Vol 2\\_temp_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4', '-i', 'C:\\Users\\fabia\\Desktop\\Jamey Arent Guitar For Complete Beginners Vol 2\\audio_for_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4', 'C:\\Users\\fabia\\Desktop\\Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2\\Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4']
>> failed to merge audio for file: 
 Doja Cat - Say so - Guitar Chords and Impro.mp4
>> file_manager 1: quitting
>> brain 1: download error
>> brain 1: quitting
>> ========================================================================================================== 
`

**Comment by Tox86** [comment]
https://pastebin.com/gHX1NbWA

**Comment by pyIDM** [comment]
I moved log here:

```
>> start downloading file: "Doja Cat - Say so - Guitar Chords and Impro.mp4", size: ..., to: C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2
>> Thread Manager()> concurrency method: Individual Threads
>> Thread Manager: allowable connections: 2
>> Seg 0 start, size: ... - range: None  - worker 9
>> Seg 1 start, size: ... - range: None  - worker 4
>> downloaded segment:  0 None 741 bytes - worker 9
>> Seg 2 start, size: ... - range: None  - worker 6
>> completed segment:  0
>> downloaded segment:  1 None 1.9 MB - worker 4
>> Thread Manager: allowable connections: 3
>> Seg 3 start, size: ... - range: None  - worker 5
>> Seg 4 start, size: ... - range: None  - worker 2
>> completed segment:  1
>> downloaded segment:  2 None 2.2 MB - worker 6
>> Seg 5 start, size: ... - range: None  - worker 1
>> completed segment:  2
>> Thread Manager: allowable connections: 4
>> Seg 6 start, size: ... - range: None  - worker 3
>> downloaded segment:  4 None 2.3 MB - worker 2
>> Thread Manager: allowable connections: 5
>> Seg 7 start, size: ... - range: None  - worker 0
>> Seg 8 start, size: ... - range: None  - worker 8
>> downloaded segment:  6 None 2.0 MB - worker 3
>> Seg 9 start, size: ... - range: None  - worker 7
>> downloaded segment:  3 None 2.3 MB - worker 5
>> Seg 10 start, size: ... - range: None  - worker 9
>> Thread Manager: allowable connections: 6
>> Seg 11 start, size: ... - range: None  - worker 4
>> completed segment:  3
>> completed segment:  4
>> downloaded segment:  5 None 2.4 MB - worker 1
>> Seg 12 start, size: ... - range: None  - worker 6
>> completed segment:  5
>> completed segment:  6
>> Thread Manager: allowable connections: 7
>> Seg 0_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 5
>> downloaded segment:  0_audio None 632 bytes - worker 5
>> Seg 1_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  7 None 2.2 MB - worker 0
>> downloaded segment:  1_audio None 158 KB - worker 2
>> Seg 2_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 1
>> Seg 3_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 3
>> completed segment:  7
>> downloaded segment:  3_audio None 158 KB - worker 3
>> Thread Manager: allowable connections: 8
>> Seg 4_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 0
>> downloaded segment:  8 None 1.9 MB - worker 8
>> Seg 5_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 5
>> Seg 6_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  2_audio None 158 KB - worker 1
>> Seg 7_audio start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 1
>> completed segment:  8
>> downloaded segment:  4_audio None 158 KB - worker 0
>> downloaded segment:  6_audio None 158 KB - worker 2
>> downloaded segment:  5_audio None 158 KB - worker 5
>> downloaded segment:  7_audio None 74 KB - worker 1
>> downloaded segment:  12 None 1.2 MB - worker 6
>> downloaded segment:  9 None 2.1 MB - worker 7
>> downloaded segment:  11 None 2.0 MB - worker 4
>> completed segment:  9
>> downloaded segment:  10 None 2.2 MB - worker 9
>> completed segment:  10
>> completed segment:  11
>> completed segment:  12
>> completed segment:  0_audio
>> completed segment:  1_audio
>> completed segment:  2_audio
>> completed segment:  3_audio
>> completed segment:  4_audio
>> completed segment:  5_audio
>> completed segment:  6_audio
>> completed segment:  7_audio
>> handling dash videos
>> merging video and audio
>> running command: "C:\Users\fabia\Desktop\PyIDM\ffmpeg.exe" -loglevel error -stats -y -i "C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2\_temp_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4" -i "C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2\audio_for_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4" -c copy "C:\Users\fabia\Desktop\Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2\Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4"
>> C:\Users\fabia\Desktop\Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2\Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4: No such file or directory
>> running command: "C:\Users\fabia\Desktop\PyIDM\ffmpeg.exe" -loglevel error -stats -y -i "C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2\_temp_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4" -i "C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2\audio_for_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4" "C:\Users\fabia\Desktop\Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2\Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4"
>> C:\Users\fabia\Desktop\Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2\Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4: No such file or directory
>> run_command()> cancelled ['C:\\Users\\fabia\\Desktop\\PyIDM\\ffmpeg.exe', '-loglevel', 'error', '-stats', '-y', '-i', 'C:\\Users\\fabia\\Desktop\\Jamey Arent Guitar For Complete Beginners Vol 2\\_temp_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4', '-i', 'C:\\Users\\fabia\\Desktop\\Jamey Arent Guitar For Complete Beginners Vol 2\\audio_for_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4', 'C:\\Users\\fabia\\Desktop\\Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2\\Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4']
>> failed to merge audio for file: 
 Doja Cat - Say so - Guitar Chords and Impro.mp4
>> file_manager 1: quitting
>> brain 1: download error
>> brain 1: quitting
>> ==========================================================================================================
```

**Comment by pyIDM** [comment]
you should check manually if you have these files on your disk
open folder 
C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2

please check for these files and report its size

_temp_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4

audio_for_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4

**Comment by Tox86** [comment]
> you should check manually if you have these files on your disk
> open folder
> C:\Users\fabia\Desktop\Jamey Arent Guitar For Complete Beginners Vol 2
> 
> please check for these files and report its size
> 
> _temp_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4
> 20.7 MB
> audio_for_Doja_Cat_-_Say_so_-_Guitar_Chords_and_Impro.mp4
>0.99 MB

A gif and capture:
![problem](https://user-images.githubusercontent.com/7013508/86813452-31943500-c04e-11ea-9dae-2ff685859aa4.gif)

![Captura](https://user-images.githubusercontent.com/7013508/86813467-35c05280-c04e-11ea-9346-2f36979f544d.PNG)

**Comment by pyIDM** [comment]
@Tox86 
good job, for detailed info
i found the problem
it is because the download folder have spaces 
for example you tried to save the video at folder "Jamey Arent Guitar For Complete Beginners Vol 2" and PyIDM replace spaces by underscore then it uses "Jamey_Arent_Guitar_For_Complete_Beginners_Vol_2" which is not found

I will fix this issue,
as a temporary fix, select a download folder with no spaces in its name, "I mean the full path shouldn't have a space" 
will let you know once fix it

**Comment by pyIDM** [comment]
> P.D: The log need a copy button :)

you are right :)

**Comment by pyIDM** [comment]
Done, new release 2020.8.13
