### ISSUE TITLE
Feature request: allow delete items other than the downloading one during the downloading progress.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#132]
Hi,

Currently, when I'm downloading a file, all items will unable to be deleted. Why not allow deleting items other than the downloading one during the downloading progress?

**Comment by pyIDM** [comment]
@hongyi-zhao 
just added a fix
i didn't do enough tests for this new feature, hope it didn't break any other functionality

**Comment by hongyi-zhao** [comment]
Based on my testing, it seems the fix does the trick. Thanks a lot.
