### ISSUE TITLE
Segment size clarification needed for pyidm extension

### ISSUE THREAD

**Issue by K3nn3th2** [pyIDM/PyIDM#133]
Hello,

thanks for your great piece of software.
I'm trying to extend pyidm to enable downloading audio streams off a server.
The sent files have every 3rd chunk (2048 byte sized) encrypted.

I am aware how to decrypt the chunks.
can you recommend a way to change the size of the segments pyidm downloads? i believe i need 2048 bytes sized chunks to be able to handle every 3rd one of them.

i tried changing DEFAULT_SEGMENT_SIZE in config.py and monitoring each segments seg.range, but i haven't understood why the seg.range value is not a range of DEFAULT_SEGMENT_SIZE.

any help is largely appreciated.

**Comment by Aboghazala** [comment]
Hello,
The last version was using fixed segment size is 2020.5.18 and starting from version 2020.6.15 started using auto file segmentation and used default segment size in config.py just to determine minimum segment size that can be splitted 

If you want to get fixed ranges/segment size you have to modify a function in utils.py called “get_range_list()” 
Use seg_size=config.DEFAULT_SEGMENT_SIZE
seg_nums = file_size//seg_size

I believe this is all you need to disable auto segmentation
Good luck

Regards,
Mahmoud
