### ISSUE TITLE
Add copy button for log

### ISSUE THREAD

**Issue by pyIDM** [pyIDM/PyIDM#134]
Add copy button for log
and another button for "open log"

**Comment by Tox86** [comment]
or export to .txt

**Comment by pyIDM** [comment]
> 
> 
> or export to .txt

it is already exported to text file automatically

see highlighted file location

![image](https://user-images.githubusercontent.com/58998813/87082749-c43dfb00-c22b-11ea-8696-9d85e46078f6.png)

**Comment by pyIDM** [comment]
Done, new release 2020.8.13, added option to open log file or log folder
