### ISSUE TITLE
if extension on video is left out, pyIDM doesn't like it..

### ISSUE THREAD

**Issue by Ton1A** [pyIDM/PyIDM#137]
Is it possible for pyIDM to automatically recognize the correct extension for the video,incase the user forgets to set it,
when renaming the downloadable file ..
atm, after the download pyIDM says "unknown file format" and skips muxing the completed download.

**Comment by pyIDM** [comment]
@Ton1A 
That's correct PyIDM depend on file name extension to recognize the required muxing format

will work on a fix for this issue

**Comment by pyIDM** [comment]
Done, new release 2020.8.13
