### ISSUE TITLE
Headsup on the newest releasese

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/PyIDM#139]
Hopefully they'll work out well for you, but be aware there are a few things that changed. Some of course you know about since _**you fixed them**_.  Much appreciated.  Very much.

Hope your project continues to do well.

Lots of stuff dealing with printing, tables, windows, Multiline.  Anyway, wanted to give you the heads up in case you see troubles so you guess there's likely here.

**Comment by pyIDM** [comment]
@PySimpleGUI 
Thanks for the heads up
good work

**Comment by PySimpleGUI** [comment]
Have you been able to try 4.28 or any of the newer releases? They have what I consider to be some of the larger (and scarier) features like multi-window.

I started having trouble with pyIDM not showing doing anything when I paste a link after upgrading.  I was going to simply delete and re-install everything.  I had been getting by downloading from GitHub.

**Comment by pyIDM** [comment]
> Have you been able to try 4.28 or any of the newer releases? They have what I consider to be some of the larger (and scarier) features like multi-window.


I follow up the PySimpleGUI's announcement issue and i can see a lot of big things implemented, still didn't get any chance to try it out 
my gui.py file started to get too messy with batches all over the place and it is getting harder to implement new features
i am already started to separate logic from gui and make something like "MVC" design
and already done a base for the controller module to throw all the logic there 
then will make a cleaner gui design

> I started having trouble with pyIDM not showing doing anything when I paste a link after upgrading. I was going to simply delete and re-install everything. I had been getting by downloading from GitHub.

i think it will take 3 seconds after pasting the link before start processing

**Comment by PySimpleGUI** [comment]
Lemme know how that MVC thing works out for you.  The majority of the attacks on Reddit claim that PySimpleGUI won't work with MVC.  I saw one tutorial where someone did what they called an MVC design using PySimpleGUI and I have to say it was a bit of a mess.  I don't know if it was because they were junior.
