### ISSUE TITLE
Getting listed on the popular Vinta Awesome Applications....

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [pyIDM/pyIDM#14]
A very popular, and difficult to get listed on, GitHub is this one:
https://github.com/vinta/awesome-python

It has 77,000 stars and over 5,000 watchers.

With work, PySimpleGUI got listed.

I've created a pull request for you.  If you can get 20 people to vote with a thumbs up, then it gets merged.

I made all kinds of posts and eventually got enough people to up-vote it.  You could slip something into your readme.

https://github.com/vinta/awesome-python/pull/1450

You've got a couple to start with.

It may take a little while, but the more you get listed in places like this, the more people will find how.

**Comment by pyIDM** [comment]
Awesome!!,
thanks Mike for this support, 
i really do appreciate this help :))

**Comment by PySimpleGUI** [comment]
You can vote on your own issue there, so be sure and use the PyIDM account to upvote it too.  Ask friends and family. Do whatever it takes 😏

**Comment by PySimpleGUI** [comment]
You're almost 1/2 way to the number of votes needed.  You've got 9 (screw the downvoters for this exercise).  

One way I got the votes was to open an issue specifically asking users to help.  Users were very responsive and waned to help.  You've got some really solid users.  I'm sure they would help if they knew to.

**Comment by pyIDM** [comment]
well, I will give it a try and make an issue for that
