### ISSUE TITLE
Proxy auth settings in PyIDM.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#142]
Hi,

How to fill out the `Proxy auth` settings in PyIDM?

**Comment by pyIDM** [comment]
hello @hongyi-zhao 
if you hover the mouse over "?" mark at Settings>Network, it will show use cases

![Screenshot_20200724_035600](https://user-images.githubusercontent.com/58998813/88354660-f25e2780-cd61-11ea-9f5f-c6b6b410e289.png)

**Comment by hongyi-zhao** [comment]
Thanks a lot for your clarification.
