### ISSUE TITLE
Can't download playlist/videos of a channel

### ISSUE THREAD

**Issue by Marc248** [pyIDM/PyIDM#146]
It does detect the number of videos and tried to process them but it doens't download them (display an html in the progress indicator). Tried updating as well the Youtube-dl version..

**Comment by pyIDM** [comment]
Hello @Marc248 
please post the playlist link

> (display an html in the progress indicator)

sorry i don't understand this part, it might be helpful if you post log or any screenshot

**Comment by Marc248** [comment]
Sure!
Here's one : https://www.youtube.com/c/MOTORIZADO/videos
and example of the log for it, after it finishes recursing all the playlist links, it starts again form the video 1

```
 [download] Downloading video 1 of 294
>> [youtube] 0P-F433toNo: Downloading webpage
>> video doesn't have subtitles
>> [youtube] 0P-F433toNo: Looking for automatic captions
>> Couldn't find automatic captions for 0P-F433toNo
>> [download] Downloading video 2 of 294
>> [youtube] rszI9rHel-k: Downloading webpage
>> video doesn't have subtitles
>> [youtube] rszI9rHel-k: Looking for automatic captions
>> Couldn't find automatic captions for rszI9rHel-k
```

**Comment by Marc248** [comment]
Sure!
Here's one : https://www.youtube.com/c/MOTORIZADO/videos
and example of the log for it, after it finishes recursing all the playlist links, it starts again form the video 1

```
 [download] Downloading video 1 of 294
>> [youtube] 0P-F433toNo: Downloading webpage
>> video doesn't have subtitles
>> [youtube] 0P-F433toNo: Looking for automatic captions
>> Couldn't find automatic captions for 0P-F433toNo
>> [download] Downloading video 2 of 294
>> [youtube] rszI9rHel-k: Downloading webpage
>> video doesn't have subtitles
>> [youtube] rszI9rHel-k: Looking for automatic captions
>> Couldn't find automatic captions for rszI9rHel-k
```

**Comment by Marc248** [comment]
Sure!
Here's one : https://www.youtube.com/c/MOTORIZADO/videos
and example of the log for it, after it finishes recursing all the playlist links, it starts again form the video 1

```
 [download] Downloading video 1 of 294
>> [youtube] 0P-F433toNo: Downloading webpage
>> video doesn't have subtitles
>> [youtube] 0P-F433toNo: Looking for automatic captions
>> Couldn't find automatic captions for 0P-F433toNo
>> [download] Downloading video 2 of 294
>> [youtube] rszI9rHel-k: Downloading webpage
>> video doesn't have subtitles
>> [youtube] rszI9rHel-k: Looking for automatic captions
>> Couldn't find automatic captions for rszI9rHel-k
```

**Comment by Marc248** [comment]
Sure!
Here's one : https://www.youtube.com/c/MOTORIZADO/videos
and example of the log for it, after it finishes recursing all the playlist links, it starts again form the video 1

 [download] Downloading video 1 of 294
>> [youtube] 0P-F433toNo: Downloading webpage
>> video doesn't have subtitles
>> [youtube] 0P-F433toNo: Looking for automatic captions
>> Couldn't find automatic captions for 0P-F433toNo
>> [download] Downloading video 2 of 294
>> [youtube] rszI9rHel-k: Downloading webpage
>> video doesn't have subtitles
>> [youtube] rszI9rHel-k: Looking for automatic captions
>> Couldn't find automatic captions for rszI9rHel-k

**Comment by pyIDM** [comment]
just tested your link and i can confirm it is a bug
will work on a fix for this issue

**Comment by pyIDM** [comment]
Done fixing this probelm
will close this issue once i make a new release

**Comment by Marc248** [comment]
Great! thank you so much! ;-)

**Comment by pyIDM** [comment]
Done with current release 2020.8.13
