### ISSUE TITLE
Contributors to PyIDM

### ISSUE THREAD

**Issue by pyIDM** [pyIDM/PyIDM#149]
Hello everyone
just added a list of people who help improving this project as an appreciation to their efforts
thanks a lot, without your ideas and participation this project wouldn't improve
please have a look and if possible you can send how you want your name to be written beside your github user name 
example:
John Doe (@jdew)

file link
https://github.com/pyIDM/PyIDM/blob/master/contributors.md

Attention:
@shin-illua
@ryneeverett
@Ton1A
@smaragdus
@hongyi-zhao

i'm sorry if i missed anyone, If you think your name should be included in this list or want to modify your name please comment on this issue or send email to info.pyidm@gmail.com

**Comment by Harshil783** [comment]
I AM NOT HERE?

**Comment by pyIDM** [comment]
Added  Harshil Pandey(@Harshil783 ) to contributers list
