### ISSUE TITLE
python: can't open file 'setup.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Biozxx** [pyIDM/PyIDM#154]
git clone https://github.com/pyIDM/PyIDM.git
fatal: destination path 'PyIDM' already exists and is not an empty directory.

biozxx@biozxx:~$ ls
GetRealDebridToken.zip  fuse-3.9.3.tar.gz   newspost_2.1.1-4_amd64.deb    ngPost_v4.11-x86_64.AppImage.1
GetRealdebridToken.py   fuse-3.9.3.tar.xz   ngPost_v4.11-armhf.AppImage
PyIDM                   libfuse-fuse-3.9.3  ngPost_v4.11-x86_64.AppImage

I am kinda new to linux, I have an ubuntu, what do you think the problem is? 

sudo python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory
biozxx@biozxx:~$

**Comment by Biozxx** [comment]
biozxx@biozxx:/mnt/shared/GitFiles2$ python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory
biozxx@biozxx:/mnt/shared/GitFiles2$ python /mnt/shared/GitFiles2/PyIDM/setup.py install
  File "/mnt/shared/GitFiles2/PyIDM/setup.py", line 19
    with open(f"{current_directory}/pyidm/version.py") as f:
                                                    ^
SyntaxError: invalid syntax
biozxx@biozxx:/mnt/shared/GitFiles2$

**Comment by Biozxx** [comment]
@pyIDM

**Comment by pyIDM** [comment]
@Biozxx 
my guess you didn't use proper python version
i think in ubuntu the command `python` is running python2
just try to repeat your command using `python3`

to make sure, open a terminal window and write the following command
`$ python3 --version`
you should have something like
`Python 3.8.3`

to run pyidm you need to have python with minimum version 3.6

the easiest way is to install using pip "if you have it installed on your system"
`python3 -m pip install pyidm --user`

**Comment by shin-illua** [comment]
@Biozxx you seem to already have `PyIDM` folder to where you're trying to `git clone` the repo, try deleting that folder first by doing `rm -rf PyIDM` first then try to `git clone` again.
