### ISSUE TITLE
Browser Extension

### ISSUE THREAD

**Issue by Harshil783** [pyIDM/PyIDM#155]
Feature Request:
A Browser Extension To Catch Links If a user click on a link and file link is not broken then open PyIDM and pass the download link to it prompt user to download it or not!

**Comment by pyIDM** [comment]
@Harshil783 
if you are willing to work on this feature, it will be a great contribution since a lot of people are asking for this feature

I believe the extension can pass links to pyidm through clipboard, since pyidm monitor clipboard and interact with any copied url

**Comment by Harshil783** [comment]
Ok I Will But It May Take Some Time!

**Comment by pyIDM** [comment]
> Ok I Will But It May Take Some Time!

Great
Take your time, no hurry

**Comment by pyIDM** [comment]
> Ok I Will But It May Take Some Time!

Great
Take your time, no hurry

**Comment by Harshil783** [comment]
@pyIDM 
Please Check The Progress And If You Want Anything Else **Plz Tell ME?**
[pyidm_extension.zip](https://github.com/pyIDM/PyIDM/files/5207112/pyidm_extension.zip)

**Comment by pyIDM** [comment]
@Harshil783 
Beautiful :+1: 
good work, you can go ahead and add clipboard functionality

**Comment by Harshil783** [comment]
Hey! Can You Help I Am Stuck On A Probelm?

**Comment by pyIDM** [comment]
> Hey! Can You Help I Am Stuck On A Probelm?

sure, what is the problem

**Comment by Harshil783** [comment]
I AM NOT Able To GET FINAL URL Of File And FILENAME PLZ HELP IF YOU KNOW HOW TO?
Chrome Api: Download
[PyIDM.zip](https://github.com/pyIDM/PyIDM/files/5207709/PyIDM.zip)

**Comment by pyIDM** [comment]
> I AM NOT Able To GET FINAL URL Of File And FILENAME PLZ HELP IF YOU KNOW HOW TO?

hmm, not sure!
i think we should monitor Network on chrome, i will let you know if i find something

**Comment by Harshil783** [comment]
> hmm, not sure!
> i think we should monitor Network on chrome, i will let you know if i find something
Did You Find?

**Comment by pyIDM** [comment]
I am looking at these https://developer.chrome.com/extensions/webRequest

**Comment by Harshil783** [comment]
did you find something? Well Do you know javascript am not knowing that much!
I Have a zip of app that is able to do same that we want but it is of other software!
Here Is ZIP!!!
[FDM Extension.zip](https://github.com/pyIDM/PyIDM/files/5208852/FDM.Extension.zip)

**Comment by pyIDM** [comment]
>  Well Do you know javascript am not knowing that much!

same here

> FDM Extension.zip

look at netwrkmon.js, i think this is what we're looking for, it uses webRequest  https://developer.chrome.com/extensions/webRequest
line 55 onResponseStarted

**Comment by Harshil783** [comment]
Yeah and i find a github repository whos extension is able to keep the chrome inbuilt download manager back off and can help to start our program

**Comment by pyIDM** [comment]
> Yeah and i find a github repository whos extension is able to keep the chrome inbuilt download manager back off and can help to start our program
> The repository link is i will provide
> Note: the repository is in chinese

Great job :+1:

**Comment by Harshil783** [comment]
Repository link https://github.com/yhl452493373/DownloadManager/

**Comment by Harshil783** [comment]
Okay The Extension Is Not Able To Get Backoff Chrome Inbuild in downloader
and My Progress That I DOne:
`Logic OF Not To Catch Downloads From This Website:
chrome.webRequest.onBeforeRequest.addListener(
        function(details) {
          return {cancel: details.url.indexOf("://www.evil.com/") != -1};
        },
        {urls: ["<all_urls>"]},
        ["blocking"]);
Logic Of Getting Things On CLipBoard:
function copy_Urls() {
  var copyText = //document.getElementById("myInput");
  copyText.select();
  copyText.setSelectionRange(0, 99999)
  document.execCommand("copy");
  alert("Copied the text: " + copyText.value);
}`

**Comment by Harshil783** [comment]
And Get Current Tab URL USING:
`https://ntp.msn.com/edge/ntp?locale=en-US&dsp=0&sp=Google`

**Comment by Harshil783** [comment]
I AM NOT ABLE TO DO!!!
