### ISSUE TITLE
Make a snap for PyIDM

### ISSUE THREAD

**Issue by Aa20475** [pyIDM/PyIDM#156]
Hey!

I'm new to snap but am willing to contribute for this. I already tried making a test snap. I think I still need to configure the parts correctly. 

Some help would be amazing!

**Comment by Harshil783** [comment]
Yeah that's good

**Comment by Harshil783** [comment]
Talk to other

**Comment by Aa20475** [comment]
I actually found it in the TODO file.. Let's see what he thinks so

@pyIDM

**Comment by Harshil783** [comment]
Ok

**Comment by pyIDM** [comment]
@Aa20475 
This would be great, snap or a Flatpak are requested before to make the installation process easier on Linux.

currently, I am almost done with the [new PyIDM GUI](https://github.com/pyIDM/PyIDM/issues/13#issuecomment-689337428), and i will co-operate with you making this snap once i finish.
also, everyone is welcomed to help in this issue too

**Comment by Aa20475** [comment]
Woah! The New UI looks amazing!

I actually started working on one.. How should I share it with you?

**Comment by Harshil783** [comment]
Wow! This is very good or one say a excellent work i wanna have have to learn tkinter from you? If you don't mind?

**Comment by pyIDM** [comment]
Thanks guys :)
@Aa20475 
to share your gui you can create a [new issue](https://github.com/pyIDM/PyIDM/issues/new) with title of "GUI design" and drag and drop screenshots or share your idea in that issue or you can send email to info.pyidm@gmail.com

**Comment by Aa20475** [comment]
Noo! I was talking about snap! 😅😅

**Comment by pyIDM** [comment]
> Wow! This is very good or one say a excellent work i wanna have have to learn tkinter from you? If you don't mind?

thanks :)

**Comment by Aa20475** [comment]
Thid is the error I'm getting now. Just adding it.
![image](https://user-images.githubusercontent.com/35968657/92766558-f39bf000-f3b3-11ea-8bc4-c249f21af5ce.png)

**Comment by pyIDM** [comment]
> We have to find a workaround for this. Snap's file system is read-only.

oh! Let's see what i can do,
PyIDM can't find a place to store settings, i will change this behavior, and let you know to test again

**Comment by pyIDM** [comment]
@Aa20475 
i think the pyidm version you have is not the latest, you should get the latest from github by cloning or downloading 

please check pyidm folder in your hard drive and see if you have the following line in "setting.py" file

at line number 60:
```
except (PermissionError, OSError):

```

because this code should handle the error you already got

**Comment by Aa20475** [comment]
I actually used the tar.gz in PIPI. I guess it's resolved in the latest code. I'll change it

**Comment by pyIDM** [comment]
hello @Aa20475 
did you make any progress

**Comment by Aa20475** [comment]
Hey! No.. I have been a bit busy lately. I'll catch you up asap

**Comment by pyIDM** [comment]
Created an AppImage [a portable linux version]
working version is available at https://github.com/pyIDM/PyIDM/releases/download/2021.1.7/PyIDM-2021.1.7-x86_64.AppImage

currently there is no plan to work on a snap or flatpak, closing issue
