### ISSUE TITLE
Having Support To Git Clone!

### ISSUE THREAD

**Issue by Harshil783** [pyIDM/PyIDM#158]
Hey! @pyIDM I Thought If your App Had A Support For Git Clone!
If you agree i make a pull request and work on it?

**Comment by pyIDM** [comment]
Hello @Harshil783 
do you mean add ability for pyidm to clone any repo on github?

**Comment by Harshil783** [comment]
Yeah

**Comment by pyIDM** [comment]
I believe it won't be a good idea
there is tons of complete tools that can do all git functionality, either gui or command tools
so we're adding no benefit for doing this

pyidm focus on videos and direct link files,
one of requests is to download files from google drive, see if you can help in this issue #144

**Comment by Harshil783** [comment]
Ok i will try to cause having google drive support will be good idea and what about getting funds?

**Comment by Harshil783** [comment]
Hey @pyIDM well i have found somewhat code to download from google drive.
Here is code:
`import requests def download_file_from_google_drive(id, destination): URL = "https://docs.google.com/uc?export=download" session = requests.Session() response = session.get(URL, params = { 'id' : id }, stream = True) token = get_confirm_token(response) if token: params = { 'id' : id, 'confirm' : token } response = session.get(URL, params = params, stream = True) save_response_content(response, destination) def get_confirm_token(response): for key, value in response.cookies.items(): if key.startswith('download_warning'): return value return None def save_response_content(response, destination): CHUNK_SIZE = 32768 with open(destination, "wb") as f: for chunk in response.iter_content(CHUNK_SIZE): if chunk: # filter out keep-alive new chunks f.write(chunk) if __name__ == "__main__": file_id = 'TAKE ID FROM SHAREABLE LINK' destination = 'DESTINATION FILE ON YOUR DISK' download_file_from_google_drive(file_id, destination)`

**Comment by Harshil783** [comment]
Please try this and tell me?

**Comment by pyIDM** [comment]
> Please try this and tell me?

try what?? giving me any random code from google won't help at all

@Harshil783 
if you're willing to contribute, you should clone pyidm and modify the code to add the feature, do your tests and if it works you can pull request and i will merge your changes

keep in mind pyidm uses multithreading libcurl not 'requests'
