### ISSUE TITLE
Startup On Windows

### ISSUE THREAD

**Issue by Harshil783** [pyIDM/PyIDM#159]
Hey! **@pyIDM**  Well I Have Created A Script That Will Automatically Start The PyIDM On Windows Startup!
**Note:** I Don't Have Knowledge For Linux And That's WHy I Don't Created For Linux And Mac.
**If You Like it I Make Some Changes To readme:**

> Purpose to Make Changes:  
- Tell Users To Start This Script If they want to run pyidm on windows startup always!
> Why I AM Not Integrating In PyIDM Because You Are Making A New Ui And I DOn't Know How to use PySimpleGUI
- So, You Need To Integrate YourSelf In Settings Options
> This Script Will Only Work On Windows!
- For Other Platforms I Need To Do Some Research

**Comment by pyIDM** [comment]
@Harshil783 
no problem, we can add this feature for windows only, as a linux user i don't like startup applications but this is normal for some windows users
you can post your script here and i will add it to pyidm code

**Comment by Harshil783** [comment]
Ok @pyIDM let me explain you some of the working of the script well this script uses batch script to add keys into registry using reg add and using the python yo write in the script

**Comment by pyIDM** [comment]
please keep in mind, the script should work both ways
it should have the ability to enable or disable startup

**Comment by Harshil783** [comment]
Ok wait i need to add ability to disable wait let me add then i post whole script here

**Comment by Harshil783** [comment]
Hey! The Script Is Ready With Functions That You Told!!!
Here You GO!!!!!!!!!
```from subprocess import Popen
with open("startup.bat",'w+') as startup:
    file = startup.read()
    pyidm_path = input("Please Specify Full Path Of PyIDM:")
    add_or_remove = input("Do You Want Add The Key Or Remove It (y/n):")
    if add_or_remove == 'y':
        writed = startup.write(f"REG ADD HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run /v PyIDM  /d {pyidm_path}" + " --minimize")
    elif add_or_remove != 'n':
        print("Wrong Input Choose From y/n")
    else:
        writed = startup.write(f"REG DELETE HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run /v PyIDM")
    startup.close()
    p = Popen("startup.bat")
    stdout, stderr = p.communicate()
```

**Comment by Harshil783** [comment]
> **Plz! If you Like My Work?**
- Can you add me in contributers?

**Comment by Harshil783** [comment]
Hmm Hey! @pyIDM Well Can you add some arguments that can help me to run program in sys tray

**Comment by pyIDM** [comment]
@harshil783
Good effort 
Still The script you wrote can be improved 
What we need is just 2 functions

Example:
`def enable_startup():
    #write to registry`

`def disable_startup():
    #write to registry`

No need to get user input thru command line

Also, Instead of writing to a batch file i think we can write directly to registry

Have a look at https://docs.python.org/3/library/winreg.html
and let me know if you can come up with usable script

**Comment by Harshil783** [comment]
Ok! @pyIDM I Try To Improve And Thanks For Suggesting For Functions!
I Improved

**Comment by Harshil783** [comment]
Hmm Hey! @pyIDM using winreg seems me to be pain so i decide to batch scripts easy because and they are one liners winreg requires installation!
And As Your Wish I Created 2 Functions:
```python
from subprocess import Popen
import os

def create_key(pyidm_path):
    with open("startup.bat",'w+') as startup:
        writed = startup.write(f"REG ADD HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run /v PyIDM  /d {pyidm_path}" + " --hidden")
    p = Popen("startup.bat")
    stdout, stderr = p.communicate()
    os.remove(os.path.join(os.getcwd(),"startup_.bat"))

def remove_key(pyidm_path):
    with open("startup.bat",'w+') as startup:
        writed = startup.write(f"REG DELETE HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run /v PyIDM")
    p = Popen("startup.bat")
    stdout, stderr = p.communicate()
    os.remove(os.path.join(os.getcwd(),"startup_.bat"))
```

**Comment by pyIDM** [comment]
> Hmm Hey! @pyIDM using winreg seems me to be pain so i decide to batch scripts easy as they are one liners

Ok, please test your script on windows and see if it works correctly without issues so i can implement it

i am currently running on Linux and can't test it

**Comment by pyIDM** [comment]
By the way I mean by testing your script on windows is to test if your script can add pyidm or any other application to windows startup and also can remove it later
You don’t have to do anything with pyidm code
Just make sure your script is running without errors

**Comment by Harshil783** [comment]
Ok i test but can you tell me some arguments for pyidm that can take pyidm minimized or to sys tray because every time it starts it shows main windows, aren't there ways to minimize by passing some arguments

**Comment by pyIDM** [comment]
Unfortunately There is no current option for pyidm to start minimized in systray

**Comment by Harshil783** [comment]
Hey! @pyIDM Here is your final script and can you add me in contributers

[Startup.zip](https://github.com/pyIDM/PyIDM/files/5223108/Startup.zip)

**Comment by pyIDM** [comment]
> can you add me in contributers

no problem

**Comment by Harshil783** [comment]
Hey! @pyIDM I AM CLOSING THIS ISSUE AND ADD ME IN CONTRIBUTERS PLEASE

**Comment by pyIDM** [comment]
@Harshil783 
good job, just tested your script and it works, just added few tweaks
how you want to write your name in contributer's list? example  Will Smith (@willsmith)

**Comment by Harshil783** [comment]
ok Just Add Harshil Pandey(@Harshil783 )

**Comment by Harshil783** [comment]
This Will Be Good

**Comment by pyIDM** [comment]
just added your name to:
https://github.com/pyIDM/PyIDM/blob/master/contributors.md

thanks for your work

**Comment by pyIDM** [comment]
Cancel adding this code to pyidm project
