### ISSUE TITLE
OMG HOW FAST!!!

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/PyIDM#16]
Wow!

I rarely download stuff.  So tonight when I wanted to download the CentOS8 Linux OS distribution, I gave PyIDM a try.  I think the link was already on my clipboard.  I started it up and off it went, downloading the 7 GB file.

I live in the country and I bond 2 different Internet connections in a desperate attempt at bandwidth that's decent.  It usually sucks.  It's difficult to get sustained throughput but **_PyIDM_** did!

I don't know what kind of magic you put into the "brain" of your software, but whatever you're doing it's magic as far as I'm concerned.  WOW.  I'm so sold on this now. This is every bit as good as any Windows program I've used for downloading, probably better now that I've tried it.

OMG, I just found the right click menu and go the file properties!  HOW did you do that?!  I didn't know that was possible using a table.  What the heck??  This is so good.  You spent a lot of time on the interface and it really shows.

**Comment by pyIDM** [comment]
I can't find a proper words to describe my feeling right now, I am so happy and jumping with joy that you found my project useful,

originally I mad this project for myself, and after releasing it on github for public use, I can tell how much fun and joy when you know you did something even a little useful to others, it is really rewarding.
thanks a million! for these nice words -:))

**Comment by pyIDM** [comment]
> OMG, I just found the right click menu and go the file properties! HOW did you do that?! I didn't know that was possible using a table. What the heck?? This is so good. You spent a lot of time on the interface and it really shows.

Right click menu was very easy and straight forward thanks to pysimpleGUI, and with the help of wonderful documentation [Extending PySimpleGUI](https://pysimplegui.readthedocs.io/en/latest/#extending-pysimplegui)  i did manage to do the following:
- select a row on right click and in same time show right click menu.
- double click and Enter key binding to open the selected file

before when I needed help withPySimpleGUI i just look inside source code but I realized I missed a lot not looking at these documentations, it is a professional piece of art 👍

**Comment by PySimpleGUI** [comment]
Wait until you post about it on Reddit.  A LOT of people will find your code. 

There may be some people that don't like it, but ignore them.  Focus on the people that you ARE making a difference for and you'll keep getting that joyful feeling.  

It's nice huh?  Now you have seen and experienced what fuels my passion for creating this software.  It's great to make a difference by simply posting what you're using yourself and finding it to be useful.  PySimpleGUI was initially package meant for me, not other people.

**Comment by jediafr** [comment]
I've just discovered your project on this [site](https://hackermilk.blogspot.com/2020/01/an-open-source-alternative-to-internet.html) i'm interested as i feel that jdownloader is bloated and i was searching for a lightweighted alternative. I'll try it for a week.

**Comment by pyIDM** [comment]
@jediafr 
great news,
Please report any bugs or issues so i can improve this application 

There is also a pypi release and windows executables available 

By the way that’s a nice article in website you mentioned

**Comment by PySimpleGUI** [comment]
WOW!  Congrats on the post!

I was wondering what the deal was with your pip installs.  They kinda went nuts yesterday
![image](https://user-images.githubusercontent.com/46163555/73380117-7642c580-4291-11ea-8254-1e282e905404.png)

**Comment by pyIDM** [comment]
@PySimpleGUI 
Thanks! :smile: 
pypi release was a good idea

**Comment by PySimpleGUI** [comment]
Would I steer you wrong?

![image](https://user-images.githubusercontent.com/46163555/75262979-51237300-57bb-11ea-912b-315bebaf7427.png)


Have you seen the stats lately??!!

Your latest 7 day download is 1/2 of your 30 day download, which means you're doubling your downloads on a regular basis.  CONGRATS!

![image](https://user-images.githubusercontent.com/46163555/75263032-64ced980-57bb-11ea-9529-3590e85ddcf4.png)


![image](https://user-images.githubusercontent.com/46163555/75263059-71ebc880-57bb-11ea-9929-929245c41c22.png)

**Comment by pyIDM** [comment]
Thanks, it starts to get some momentum and i saw some website started mentioning pyidm 
I will continue add features to enhance it and let it speak for itself
