### ISSUE TITLE
"Open file location" failed to open the correct folder.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#164]
Hi,

On Ubuntu 20.04 with the latest git master version of PyIDM, it seems that the **Open file location** failed to open the correct folder. Say, I downloaded [google-chrome](https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb) and PyIDM puts it at **/home/werner/Downloads**. But when I click on the **Open file location**, it will open the following folder:
```
>> utils> open_folder()>  /home/werner/Public/repo/github.com/idm-pydidm-xdm

(gdebi-gtk:88592): Gtk-WARNING **: 12:05:24.180: ../../../../gtk/gtkwidget.c:8648: widget not within a GtkWindow
>> utils> open_folder()>  /home/werner/Public/repo/github.com/idm-pydidm-xdm
```
Any hints for this problem?

Regards,
HY

**Comment by pyIDM** [comment]
@hongyi-zhao 
confirm a bug in new version, just added a fix, please check latest fix let me know if it works for you

**Comment by hongyi-zhao** [comment]
It does the trick. But the thumbnail logo of the downloading/downloaded file will display as a white box. See the following screenshot for more info:

![image](https://user-images.githubusercontent.com/11155854/94266669-0a724300-ff6d-11ea-8627-10067f75a756.png)

**Comment by pyIDM** [comment]
can you try to partially download any new video with a thumbnail "just pause it once it start" then restart application and see if thumbnail for this video displayed again or not, also check for any message in terminal once application start again

**Comment by hongyi-zhao** [comment]
Do you mean the thumbnail **only** displayed for video files? If so, I must told you that all of the files for my case are not video files at all.

**Comment by pyIDM** [comment]
if it is not a video file it should show extension of the file in thumbnail area, but i see blank names in the list, there should be something wrong
can you copy the terminal output when you run pyidm, i think there is an error message somewhere

**Comment by hongyi-zhao** [comment]
```
werner@X10DAi-01:~$ pyidm 
>> Load Application setting from /home/werner/Public/repo/github.com/idm-pydidm-xdm/PyIDM.git/pyidm
>> Load previous download items from /home/werner/Public/repo/github.com/idm-pydidm-xdm/PyIDM.git/pyidm
>> load_progress_info()> rebuild segments from previous download for: parallel_studio_xe_2020_update1_cluster_edition.tgz
>> youtube-dl version: 2020.06.06, load_time= 0 seconds
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.9.20 Non-Frozen
>> operating system: Linux-5.4.0-48-generic-x86_64-with-glibc2.2.5 - x86_64
>> Python version: 3.8.3 (default, May 25 2020, 15:44:25) 
[GCC 9.3.0]
>> current working directory: /home/werner/Public/repo/github.com/idm-pydidm-xdm/PyIDM.git/pyidm
>> url watchdog active!
>> controller.get_d_list()> sending d_list
Failed to dock icon
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 159, in _update_icon
    self._assert_docked()
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 386, in _assert_docked
    assert self._systray_manager
AssertionError
Failed to dock icon
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 140, in _show
    self._assert_docked()
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 386, in _assert_docked
    assert self._systray_manager
AssertionError


```

**Comment by pyIDM** [comment]
@hongyi-zhao 
please try latest version and you can test download this small file and see if things back to normal
https://www.7-zip.org/a/7z1900-src.7z

**Comment by hongyi-zhao** [comment]
See the screenshot:

![image](https://user-images.githubusercontent.com/11155854/94281450-3bf50980-ff81-11ea-9f57-37776899fc0f.png)

**Comment by pyIDM** [comment]
I believe things are back to normal, all new items will behave normally

maybe the old ones info had been missed up in  "downloads.cfg" file at 
/home/werner/Public/repo/github.com/idm-pydidm-xdm/PyIDM.git/pyidm

**Comment by pyIDM** [comment]
by the way did you restart pyidm and the last item still has thumbnail i.e. "7z" shows up?

**Comment by hongyi-zhao** [comment]
Yes.

**Comment by pyIDM** [comment]
> Yes.

great, then i can say this issue is fixed, you can close this issue
