### ISSUE TITLE
fail downloading hls,m3u8,ts

### ISSUE THREAD

**Issue by p0txky** [pyIDM/PyIDM#167]
file_manager()>  post_process_hls() failed, file:

**Comment by pyIDM** [comment]
@p0txky 
you should provide the download link for testing

**Comment by p0txky** [comment]
sample link https://ms.linksgen.com/v/233800bccfdbfb92737cb436b479e498/720.m3u8

**Comment by pyIDM** [comment]
@p0txky 
just tested the link you provided, however all segments have been downloaded successfully, but it doesn't have a valid video data
in normal situation you should be able to play a single segment normally 
I believe the server adds some proprietary encryption to these segments to protect it from being downloaded

**Comment by p0txky** [comment]
Thanks  @pyIDM
