### ISSUE TITLE
Failed to convert audio streams

### ISSUE THREAD

**Issue by Mr-Personality** [pyIDM/PyIDM#168]
Hi, I love your program but I keep getting an error.

All files download successfully, but they are stuck in the Downloads folder with `_temp_` before the filename, with a folder full of parts.

I also get this error every time:
`file_manager()> convert_audio() failed, file: c:\Users\[…]`

PyIDM ver.2020.9.20
Win7 x64

**Comment by pyIDM** [comment]
@Mr-Personality 
I guess you are trying to download audio only from a video file, and for some reason ffmpeg failed to convert audio
you may send any download link for testing

**Comment by Mr-Personality** [comment]
Yes, you're right. This only happens when downloading audio only.

No point me sending you a link - this happens with every video I've tried!

**Comment by pyIDM** [comment]
@Mr-Personality 
you are right this is a bug, and i will try to fix it

**Comment by Mr-Personality** [comment]
Also, when I download a video it sometimes leaves behind another file with .meta after it.

**Comment by pyIDM** [comment]
> Also, when I download a video it sometimes leaves behind another file with .meta after it.

this is already fixed and will be available with this coming release

**Comment by MJH1000** [comment]
Is there a nightly build with the latest fixes?

**Comment by pyIDM** [comment]
@MJH1000 

> Is there a nightly build with the latest fixes?

unfortunately no, but a new release might be today or tomorrow once finished testing

**Comment by Mr-Personality** [comment]
Thanks again for making this excellent program! Great job! :-)
