### ISSUE TITLE
GUI suggestions

### ISSUE THREAD

**Issue by Mr-Personality** [pyIDM/PyIDM#169]
I love your program - I was looking for an alternative to 4K Video Downloader because they've started limiting downloads. pyIDM is exactly what I needed! :-)

I just have a few suggestions about the GUI:

1. This is my main problem - The button to change the download destination path is TINY! PLEASE can you make this a large button? Every video I download goes to a different folder, so I always want to specify the path every time. I don't think the path should be down there at the bottom, it should be maybe at the top, under the URL bar, with a HUGE button to change the path?

2. It would also be nice if the download path was directly editable, so you can click on it and type a new folder name, etc.

3. When I hit the "Download" button, the GUI always switches to the Downloads tab. I don't want this. It means I have to keep switching back to the 'Home' tab when I'm downloading a bunch of videos.

4. It would be nice if the downloads list could appear on the right side of the 'Home' tab, perhaps with a draggable division?

5. Showing the thumbnail is GREAT. It would be useful if there was a small checkbox saying "Download thumbnail", which downloaded thumbnails along with the video or audio.

6. For playlists, it would be neat if you could select multiple videos on the list. Then under Stream Quality, the options change to say "Preferred resolution:" and "Preferred format:" for video, and "Preferred bitrate:" and "Preferred format:" for audio. One of the options is always "Highest possible".

7. A minor detail, but under Stream Quality, it would be good to have proper columns, with headings, which would make the data easier to read as all the entries would line up.

Most of these are minor, unimportant things, but for me, the bigger 'path' button is the most important.

Thanks!

**Comment by pyIDM** [comment]
@Mr-Personality 
Thanks for your suggestions, will consider these ideas in next releases

**Comment by Ton1A** [comment]
please...
how do i enable the old gui with it's graphics..
sorry but the current default looks horrible.
also.... 
the latest version takes the processor usage of my laptop to 100% and crashes.
i have to revert to the old version.
sorry.

**Comment by pyIDM** [comment]
> please...
> how do i enable the old gui with it's graphics..

if you need the old gui you can use older version of pyidm 

> the latest version takes the processor usage of my laptop to 100% and crashes.

I am aware of this bug and it has been already fixed and will make new release very soon

**Comment by Mr-Personality** [comment]
One more thing…

8. When the program starts, it always defaults to a small window, even though I have stretched it bigger. Please can you make it remember window size,

Also, with all due respect, I think pyIDM is a poor name. I don't know how to pronounce it. It's not memorable. It doesn't describe what it does. It sounds like nonsense. Humbly, I recommend you consider changing the name. You would get a lot more downloads with a more catchy name. VidGrabber, or VidLeecher or something? I dunno. I could make lots of suggestions! I like naming things :-)

**Comment by pyIDM** [comment]
> 1. When the program starts, it always defaults to a small window, even though I have stretched it bigger. Please can you make it remember window size,

this is a good idea and can be added easily

**Comment by pyIDM** [comment]
> Also, with all due respect, I think pyIDM is a poor name. I don't know how to pronounce it. It's not memorable. It doesn't describe what it does. It sounds like nonsense. Humbly, I recommend you consider changing the name. You would get a lot more downloads with a more catchy name. VidGrabber, or VidLeecher or something? I dunno. I could make lots of suggestions! I like naming things :-)

Changing the name is very challenging task, and i agree with you, the combination of these letters makes it difficult to pronounce 
it will take time to come up with a good and unique name

**Comment by Mr-Personality** [comment]
Someone above said he doesn't like the new GUI. I presume he doesn't like the blue and gold colors?

May I suggest these subtle changes?
Blue: #3272f8
Gold: #ffce28

**Comment by pyIDM** [comment]
> 
> 
> Someone above said he doesn't like the new GUI. I presume he doesn't like the blue and gold colors?
> 
> May I suggest these subtle changes?
> Blue: #3b73e1
> Gold: #ffce28

@Mr-Personality 
for sure you can't please everyone, this is life
color choice is a matter of personal preferences, you might love some colors which in same time will be awful for someone else
That's why there is already an option in settings to edit theme colors and everyone can create any number of themes with colors of his choice
here is how to in docs: https://github.com/pyIDM/PyIDM/blob/master/docs/user_guide.md#select-theme

**Comment by Mr-Personality** [comment]
Ah, I didn't know about the theme editor, that's great! :-)

You only have 1 pre-installed 'light' theme. May I suggest adding something like these:

Main background: #f0f0f0
Side frame: #d6cebf
Side button/progress bar: #3e8dd5

Main background: #ffffff
Side frame: #d0eaff
Side button/progress bar: #0092da
