### ISSUE TITLE
PyIDM refuses to close when using the systray icon

### ISSUE THREAD

**Issue by nero-0** [pyIDM/PyIDM#171]
After upgrading to the latest version of PyIDM (2020.10.10), I noticed that if the option "Minimize to systray when closing application window" is checked and try to finish the application using the tray icon (right-click + quit), nothing happens. It keeps running in the background... on the other hand, if this option is unchecked, the application is finished normally.

This is a behavior that did not happen in the previous version.

I'm on Windows 10 x64.

**Comment by pyIDM** [comment]
@nero-0 
Thanks for reporting this bug, will fix it in new release

**Comment by pyIDM** [comment]
Done in today's release 2020.10.11
