### ISSUE TITLE
[Feature Request] Linux Portable Version

### ISSUE THREAD

**Issue by chromer030** [pyIDM/PyIDM#172]
Please add portable version for linux.
Thanks.

**Comment by pyIDM** [comment]
@chromer030 
just posted portable version for linux at https://github.com/pyIDM/PyIDM/releases/download/2020.10.11/PyIDM_linux_2020.10.11.zip

please report if it works for you

**Comment by chromer030** [comment]
Hi , Thank you very much
I tested on Arch Linux and got this error :

`[Arch@Linux PyIDM]$ ./pyidm.bin `
`Traceback (most recent call last):`
`  File "/home/mahmoud/.local/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run`
`  File "/home/mahmoud/.local/lib/python3.8/site-packages/cx_Freeze/initscripts/Console.py", line 33, in run`
`  File "pyidm.py", line 11, in <module>`
`  File "/run/media/mahmoud/Data/python/myProgects/PyIDM/pyidm/PyIDM.py", line 48, in <module>`
`  File "/run/media/mahmoud/Data/python/myProgects/PyIDM/pyidm/controller.py", line 24, in <module>`
`  File "/run/media/mahmoud/Data/python/myProgects/PyIDM/pyidm/update.py", line 27, in <module>`
`  File "/run/media/mahmoud/Data/python/myProgects/PyIDM/pyidm/utils.py", line 27, in <module>`
`  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>`
`ImportError: libimagequant.so.0: cannot open shared object file: No such file or directory`
`[Arch@Linux PyIDM]$ `

**Comment by pyIDM** [comment]
@chromer030 
thanks for reporting this
will do more investigations to troubleshoot this problem

**Comment by elogicuk** [comment]
i want to download and test but this url is broken now

https://github.com/pyIDM/PyIDM/releases/download/2020.10.11/PyIDM_linux_2020.10.11.zip

**Comment by pyIDM** [comment]
> i want to download and test but this url is broken now
https://github.com/pyIDM/PyIDM/releases/download/2020.10.11/PyIDM_linux_2020.10.11.zip

@elogicuk 
there was an issue with this linux release, that's why it has been removed
will submit another release once it is ready

**Comment by chromer030** [comment]
@pyIDM 
Hi , i think packaging this lovely app for Linux as Appimage (https://github.com/AppImage/AppImageKit) will be great , useful and easy. Usable on almost all distros and in future in FreeBSD also.
GitHub Action can help in order to auto generate appimage.
Thank you.

**Comment by pyIDM** [comment]
@chromer030 

> @pyIDM
> Hi , i think packaging this lovely app for Linux as Appimage (https://github.com/AppImage/AppImageKit) will be great , useful and easy. Usable on almost all distros and in future in FreeBSD also.
> GitHub Action can help in order to auto generate appimage.
> Thank you.

Thanks a lot  👍

**Comment by pyIDM** [comment]
Hello @chromer030 
just made an AppImage version, at https://github.com/pyIDM/PyIDM/releases/download/2021.1.7/PyIDM-2021.1.7-x86_64.AppImage

let me know if it works on your system

**Comment by chromer030** [comment]
Hello dear @pyIDM 
Thank you for all your efforts.
Tested on arch linux, kernel 5.10.9, working flawlessly, here is the log, I launched the tool then downloaded this appimage and closed the tool :

```
$ ./PyIDM-2021.1.7-x86_64.AppImage 
>> No enough permission to store setting at local folder: /tmp/.mount_PyIDM-9cDI5R/usr/src/pyidm
>> Global setting folder will be selected: /home/chromer030/.config/PyIDM/
>> Load Application setting from /home/chromer030/.config/PyIDM/
>> setting.cfg not found
>> Load previous download items from /home/chromer030/.config/PyIDM/
>> downloads.dat file not found, looking for legacy "downloads.cfg" file
>> downloads.cfg file not found
>> load_json() > error:  [Errno 2] No such file or directory: '/home/chromer030/.config/PyIDM/user_themes.cfg'
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> youtube_dl version: 2021.01.16, load_time= 0 seconds
>> -------------------- PyIDM --------------------
>> Starting PyIDM version: 2021.1.7 Non-Frozen
>> operating system: Linux-5.10.9-arch1-1-x86_64-with-arch - x86_64
>> Python version: 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]
>> current working directory: /tmp/.mount_PyIDM-9cDI5R/usr/src/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> Tkinter version: 8.6.8
>> AwesomeTkinter version: 2021.1.7
>> Pillow version: 8.1.0
>> PyCUrl version: PycURL/7.43.0.1 libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
>> 
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
>> youtube_dlc version: 2020.11.11-3, load_time= 0 seconds
>> set default extractor engine to: youtube_dl <module 'youtube_dl' from '/tmp/.mount_PyIDM-9cDI5R/usr/lib/python3.6/site-packages/youtube_dl/__init__.py'>
>> controller.get_d_list()> sending d_list
>> controller.get_d_list()> sending d_list
>> controller.get_d_list()> sending d_list
>> controller.get_d_list()> sending d_list
url_watchdog, new url:  https://github.com/pyIDM/PyIDM/releases/download/2021.1.7/PyIDM-2021.1.7-x86_64.AppImage
Gui terminated
Stop all downloads
>> setting saved in: /home/chromer030/.config/PyIDM/setting.cfg
>> downloads items list saved in: /home/chromer030/.config/PyIDM/downloads.dat
```

**Comment by chromer030** [comment]
I think we can now close this issue , thank you again.
