### ISSUE TITLE
python3-pil.imagetk not installed during installation 

### ISSUE THREAD

**Issue by p0txky** [pyIDM/PyIDM#173]
from PIL import Image, ImageTk, ImageColor, ImageDraw, ImageFilter
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

**Comment by pyIDM** [comment]
@p0txky 
Thanks for reporting this issue
not sure why pillow has missing parts, will do more investigation on this issue

**Comment by pyIDM** [comment]
@p0txky 
`python3-pil.imagetk` should be installed by your repo pkg manager

I already added example in readme file to install required packages on ubuntu, e.g:
`sudo apt install python3-pil.imagetk`
