### ISSUE TITLE
[Feature Request] youtube-dlc Support

### ISSUE THREAD

**Issue by fidodkk** [pyIDM/PyIDM#178]
Hello.

I hope youtube-dlc support will be added.

https://github.com/blackjack4494/yt-dlc

**Comment by pyIDM** [comment]
@fidodkk 
Just added youtube-dlc support and set as a default video extractor, also there is an entry in settings to switch between youtube-dl and youtube-dlc

commit https://github.com/pyIDM/PyIDM/commit/3e9fe881c070349cc36cd0294db9ce934b91ed12
