### ISSUE TITLE
Feature request: disable the playlist check for non-streaming media files.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#179]
Hi,

I noticed that for any file to be downloaded by PyIDM, it will first do the  playlist check on it, say, for [this one](https://www.pdfdrive.com/download.pdf?id=184429645&h=da54166f1afede2cb8f723f3c4fd0a8f&u=cache&ext=pdf). This is an unnecessary job and will bring performance penalty.

Could you please kindly disable this checking based on the file type identification? 

Regards,
HY

**Comment by pyIDM** [comment]
@hongyi-zhao 
i just checked the link you gave and PyIDM didn't check for playlist, it will only do so if the file type is an html or text, it will try to extract video or playlist info

here is what i get when trying the link you sent

```
>> get_headers()> getting headers for: https://www.pdfdrive.com/download.pdf?id=184429645&h=da54166f1afede2cb8f723f3c4fd0a8f&u=cache&ext=pdf
>> Segments-introduction to solid state physics ( pdfdrive ).pdf, (1): ['0:None']
```
it will get the headers and build file segments and no checks for playlist
if you have something else in log file please post it, or maybe another test file

**Comment by hongyi-zhao** [comment]
I just noticed that the progress bar under the playlist on the main GUI will take some time for completing the corresponding work.

**Comment by pyIDM** [comment]
> I just noticed that the progress bar under the **Playlist** on the main GUI will take some time for completing the corresponding work.

it is just an indicator to show that pyidm is busy, e.g. making a server request to get headers, and the time consumed is the server response time
