### ISSUE TITLE
[Enhancement] System Tray Support

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/PyIDM#18]
It would be really interesting to have a version of PyIDM that lives in the system tray.

It's possible, and demonstrated I believe to mix PySimpleGUI and PySimpleGUIWx together.  PySimpleGUIWx supplies the system tray functionality, PySimpleGUI supplies the windowing GUI functionality.

You could also use PySimpleGUIQt for the system tray.

The only issue I've had is that WxPython is a little difficult to install sometimes, particularly on Linux.  If you went with PySimpleGUIQt then the install won't be a big deal as PySide2 installs easily on Linux and Macs.

It's only 7 lines of code to have a system tray icon running in your program.
https://github.com/PySimpleGUI/PySimpleGUI/blob/master/PySimpleGUIWx/Demo%20Programs/Wx_System_Tray_Simple.py

I know I've mixed the PySimpleGUI ports a number of times.  For example you'll find a demo of PySimpleGUIQt running the ImWatchingYou debugger which is written using the tkinter version.

Having the system tray using Qt/Wx will also remove the need for another package to show the popup messages in your system tray area like you're doing now.

**Comment by pyIDM** [comment]
Well, i had this functionality before when my application was relying on WxPython, 
this is a good idea to mix 2 ports, i  will consider using qt for systray and see how it goes ,
Thanks Mike

**Comment by pyIDM** [comment]
> Having the system tray using Qt/Wx will also remove the need for another package to show the popup messages in your system tray area like you're doing now.

is it possible to generate a popup messages like balloon messages from systray icon?

**Comment by PySimpleGUI** [comment]
Yes, that is what I was saying... use PySimpleGUI to show the tray message. From the PySimpleGUIQt readme section on System Trays.  You can also detect if the user clicks on the message.

![image](https://user-images.githubusercontent.com/46163555/71587341-47e39600-2aeb-11ea-8fea-cadb2a2d2d5a.png)

**Comment by PySimpleGUI** [comment]
> Well, i had this functionality before when my application was relying on WxPython,
this is a good idea to mix 2 ports,

The WxPython port has the least amount of functionality for windows.  The focus was on the system tray.  Since you can mix these packages together, I recommend using the tkinter port for the windows and either Wx or Qt for the system tray. 

You are using such specific, complex and advanced features of the PySimpleGUI Elements in tktiner that I think you'll have a difficult time getting them all working on the PySimpleGUIQt port.

**Comment by pyIDM** [comment]
![](https://user-images.githubusercontent.com/46163555/71587341-47e39600-2aeb-11ea-8fea-cadb2a2d2d5a.png)

Wow! this is beautiful!!, and `You can also detect if the user clicks on the message.` this what i needed exactly 

> You are using such specific, complex and advanced features of the PySimpleGUI Elements in tktiner that I think you'll have a difficult time getting them all working on the PySimpleGUIQt port.

this what makes me hesitating to migrate from tk port to qt port, as you suggested my best bet for now is to use a mix  PySimpleGUI tkinter port for the windows and Qt for the system tray.

**Comment by PySimpleGUI** [comment]
Before you get too excited, you've got a lot of testing to do with this.  At the moment you're portable, and if you make an EXE with PyInstaller it's likely not enormous.

The moment you add Qt to this project you add a LOT of complexity.  Your EXE will balloon to 200 MB.

For my personal projects, I use Wx for the System Tray.

PySide2 likely pip installs itself on all platforms.  WxPython is maybe not as easy.  I dunno which is why I say you've got a lot ahead of you.

**Comment by pyIDM** [comment]
> Your EXE will balloon to 200 MB.
you're right this is something I need to think about, this huge size will kill  exe release, anyhow I will do some more investigation

**Comment by PySimpleGUI** [comment]
This feature was added to tkinter.  It could be mega cool for you.

It works by placing an icon just above the system tray.  I ended up making mine quite a bit bigger because I find myself using it all day long.  When I double click it, the latest issues list is shown.  Launching discord is as easy as right clicking and choosing it from the menu that's shown.

![image](https://user-images.githubusercontent.com/46163555/78898358-a8b33080-7a41-11ea-8e60-9f7823d8bc58.png)

The coolest thing about it is that the SystemTray code is identical to the one that runs on Wx and Qt.  The same calls work for user code.  

The result on tkinter is a "smart icon" in a way.  Mine changes to a red icon when there are new GitHub issues to check.  It also shows notification windows like the system tray ones, but a little different.  Would be great to popup when there are things that finish (if you've not already done that).

Right click brings up this, which also has realtime stats in the menu itself.

![image](https://user-images.githubusercontent.com/46163555/78898661-270fd280-7a42-11ea-8283-7c850c836c64.png)


I dunno, it could be worth looking at to create yet another unique feature.  I think there's another system tray package for windows that some people are using.  If you already are, sorry about that.  This won't change your EXE size either.

**Comment by smaragdus** [comment]
Support for system tray is a common feature for download managers and if it hadn't been demanded already I would have suggested it myself. Usually I run many programs and my task bar gets easily cluttered so I prefer to be able to minimize those programs which are not immediately needed to system tray. With programs which do not have support for system tray I use a special tool- [SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu), which adds additional commands to title bar, screen:

![PyIDM 2020 03 31 - 2020-04-09 - 002](https://user-images.githubusercontent.com/9025757/78902648-b937cb00-7a82-11ea-8cc4-3cd3bdac9c84.png)

so using this portable tool I can send [pyIDM](https://github.com/pyIDM/pyIDM) to tray, screen:

![PyIDM 2020 03 31 - 2020-04-09 - 007](https://user-images.githubusercontent.com/9025757/78902901-1469bd80-7a83-11ea-9274-b03878429f53.png)

but of course native support for system tray would be better. If system tray this is implemented in the future I would like to show an example of good system tray settings- [Transmission Remote GUI](https://github.com/transmission-remote-gui/transgui), screen:

![Transmission Remote GUI 5 18 0 - 2020-04-09 - 002](https://user-images.githubusercontent.com/9025757/78903383-b8ebff80-7a83-11ea-9342-36fc72e652aa.png)

My desired settings are:

- Tray icon always visible
- Close to tray

as I prefer to minimize to task bar and close to system tray.

If system tray support is implemented in future releases of [pyIDM](https://github.com/pyIDM/pyIDM) I suppose that there should be some tray commands, for example:

- Open
- Resume All
- Stop All
- Exit

Although support for system tray is not vital it would give [pyIDM](https://github.com/pyIDM/pyIDM) a finished look.

**Comment by PySimpleGUI** [comment]
Yea, I too use a taskbar enhancement tool to minimize stuff to the tray.  The last one I was using was 4T Tray Minimizer.  I had some compatibility issues so I stopped using it.

The original suggestion for a PySimpleGUI implementation was to enable you to show tray messages when things completed, change icon colors when a problem happens or some event happens, and the kind of menu you suggested.  Do the things you already know fit your program.  You've already got the design in your head that go beyond the simple minimization.

This followup was just to let you know the option is there now.  Not saying it's right for your project, just that it's a capability requiring a few lines of code..  I need to add a Recipe for the feature so perhaps a good Recipe name would be "Minimize to desktop icon" or something along those lines versus "Minimize to tray" for the tkinter version.

Here's the basic code to add an icon with a menu and process the menu choices if you ever get to the point it makes sense for ya.

```python
import PySimpleGUI as sg
menu_def = ['UNUSED', ['My', 'Simple', '---', 'Menu', 'Exit']]
tray = sg.SystemTray(menu=menu_def, data_base64=sg.DEFAULT_BASE64_ICON)
tray.show_message('Starting', 'Now Starting the application')

while True:
    event = tray.read()
    if event == 'Exit':
        break
    elif event == 'Menu':       # add your checks here
        pass
    tray.show_message('Event', '{}'.format(event))
```

**Comment by smaragdus** [comment]
@PySimpleGUI 

> Yea, I too use a taskbar enhancement tool to minimize stuff to the tray. The last one I was using was 4T Tray Minimizer. I had some compatibility issues so I stopped using it.

If you don't mind using .NET programs you may have a look at [SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu), it is stable, light, resides in system tray and offers many commands (as visible in the first screen).

**Comment by PySimpleGUI** [comment]
@pyIDM 
Sorry, I mistook the response as your's. I glanced up, say the pyIDM icon and assumed it was you but the icon I saw was in the window, not net to the comment.  Doh!
@smaragdus 
Thanks for the tips.

**Comment by pyIDM** [comment]
@PySimpleGUI 

> Here's the basic code to add an icon with a menu and process the menu choices if you ever get to the point it makes sense for ya.

This is very cool short piece of code, and the floating notification messages are nice, well done

**Comment by pyIDM** [comment]
@smaragdus 

> My desired settings are:
    - Tray icon always visible
    - Close to tray

The close to tray option is my favorite, I don't like applications to run in background if not in use.

**Comment by PySimpleGUI** [comment]
> This is very cool short piece of code,

It's the PySimpleGUI way.  Short, easy, logical.  Why make it difficult when simple works?  

It could be kinda fun to see how it would look with pyIDM.  But it'll require you to run your event loops, including this system tray one, with a timeout because they all have to be part of the mainloop and not in a thread 🙁  I don't recall if you're doing that already to achieve all those MANY windows (I love this project for it's complexity and send a lot of people here as a result)  It's got to be the most complex multi-windowed PySimpleGUI program that exists.

**Comment by pyIDM** [comment]
@PySimpleGUI 
i use "timeout reading" for all windows, this is how i managed to show any number of windows simultaneously, and this will be applied to systray loop too

**Comment by smaragdus** [comment]
@PySimpleGUI 

Thank you very much for version [2020.5.3](https://github.com/pyIDM/pyIDM/releases/tag/2020.5.3) and for implementing tray support!

I prefer this option:

![PyIDM 2020 05 03 - 2020-05-03 - 001](https://user-images.githubusercontent.com/9025757/80917606-c89bf280-8d68-11ea-9ab7-0b379f78fbcf.png)

I also like that the program is maximized from tray via double click as it eliminates chances for misclicks which often happen with programs which are restored from tray with single click.

The tray commands, screen:

![PyIDM 2020 05 03 - 2020-05-03 - 003](https://user-images.githubusercontent.com/9025757/80918266-be7bf300-8d6c-11ea-8edd-5d185f00c662.png)

work just fine.

Yet I think that for a second a ghost tray icon appears:

![PyIDM 2020 05 03 - 2020-05-03 - error - 005](https://user-images.githubusercontent.com/9025757/80918047-9cce3c00-8d6b-11ea-9913-4237f24ca92b.png)

which shows this message:

`PyIDM still running in background`

but as seen from the screen above it does not come from **PyIDM** proper tray icon but from a ghost tray icon that disappears after a second or two. Can you confirm that there appears a ghost tray icon?

Regards

**Comment by PySimpleGUI** [comment]
What did you end up using for your system tray support? 

Was it one of the PySimpleGUI ports or another package?  If another package, I'm interested in learning more for sure as integrating with another package that provides a system tray would be great since tkinter doesn't have support for one.

**Comment by pyIDM** [comment]
@smaragdus 
Thanks for your testing and as always a helpful findings

>  Can you confirm that there appears a ghost tray icon?


yes, the notification still coming from old notification system, 
there is a room for improvement and this notification should come from systray icon itself

**Comment by pyIDM** [comment]
> 
> 
> What did you end up using for your system tray support?
> 
> Was it one of the PySimpleGUI ports or another package? If another package, I'm interested in learning more for sure as integrating with another package that provides a system tray would be great since tkinter doesn't have support for one.

@PySimpleGUI 
I was looking for something lightweight and using other PySimpleGUI wx port or pyqt port will add extra dependency and big windows executable size

I used infi.systray package, just embedde the file in project 
this is the file in my project
https://github.com/pyIDM/pyIDM/blob/master/pyidm/wintray.py

source of package
source code: https://github.com/Infinidat/infi.systray

> Copyright (c) 2017 INFINIDAT
This module is adapted from an implementation by Simon Brunning,
which in turn was adapted from Mark Hammond's win32gui_taskbar.py and win32gui_menu.py demos from PyWin32.

**Comment by PySimpleGUI** [comment]
Awesome!!  Thank you!

I was thinking that Wx and Qt would be adding way too much.  I'm glad you found another path.

Can you say a few words sometime about what your experience has been?  Was it hard to add to the code?  How long did it take you to add the basic feature?

**Comment by PySimpleGUI** [comment]
Sorry I'm still absorbing what you said.

Did you get this feature by including this one file with your project?
https://github.com/pyIDM/pyIDM/blob/master/pyidm/wintray.py

You don't require the user to install anything in order to get this (no pip installs).  Your application is all that is needed?

**Comment by pyIDM** [comment]
First it took me a time to find a proper package, the one i wanted to use first was "[pystray](https://github.com/moses-palmer/pystray)" because it works on windows, linux, and mac. however it needs to be run from main thread as a blocking loop and your entire program runs from another thread, a thing that tkinter will cry about.
then looking at "infi.systray" it states it runs happily from any thread no need to be in main thread

[infi.systray](https://github.com/Infinidat/infi.systray) works on windows only, i will continue looking for something else to work with linux too

once decided to use infi.systray it took no effort to start showing systray and use events callbacks
Then overrided "x" close button for tkinter window, with my callback method to hide or close window depending on user settings, and it works well for hiding window "when press x button it will hide window instead of close it", but when i tried to call self.window.close() it didn't go well, since i need to tell pysimplegui window.read() that i'm done, as a woraround i used 
`self.window._AutoCloseAlarmCallback()`

**Comment by pyIDM** [comment]
> 
> 
> Sorry I'm still absorbing what you said.
> 
> Did you get this feature by including this one file with your project?
> https://github.com/pyIDM/pyIDM/blob/master/pyidm/wintray.py
> 
> You don't require the user to install anything in order to get this (no pip installs). Your application is all that is needed?

yes this is awesome!!!
 it uses python builtin ctypes module for windows, nothing needed, but as i mentioned it is a windows only solution, still same thing can be done on linux and mac without extra libraries, 
have a look at [pystray ](https://github.com/moses-palmer/pystray)package

**Comment by PySimpleGUI** [comment]
Oh wow

This could be a big step forward.  I could have a second option for people to use for the system tray.

**Comment by smaragdus** [comment]
@pyIDM 

I did a very brief test of version [2020.5.4](https://github.com/pyIDM/PyIDM/releases/tag/2020.5.4) and I would like to report something about system tray icon- when I close the program to tray a second tray icon appears again- this time it is iconized, screen:

![PyIDM 2020 05 04 - 2020-05-04 - 007](https://user-images.githubusercontent.com/9025757/80961983-c7280400-8e14-11ea-8fff-3b35ccb39578.png)

One more thing- off-topic but I think it is not worth opening a new issue- in this release ([2020.5.4](https://github.com/pyIDM/PyIDM/releases/tag/2020.5.4)) **FFmpeg** executable is renamed from **ffmpeg.exe** to **ffmpeg2.exe** which causes a console window to appear for a second. When I rename the executable from **ffmpeg2.exe** to **ffmpeg.exe** the console window no longer appears.

**Comment by pyIDM** [comment]
@smaragdus 
The ghost notification still the same i just changed its icon, still need to be improved
for ffmpeg, I changed the name to "ffmpeg2.exe" as a part of test, and forget to turn it back to normal "ffmpeg.exe", 
thats why you found that console window appeared which is an attempt from application to find ffmpeg.exe on your system, because it couldn't recognize the one in PyIDM folder

thanks again for pointing this out

**Comment by pyIDM** [comment]
@PySimpleGUI 
Now I use "pystray" for systray icon, i run it from a thread now, which works on windows and Linux, "but mac will require running from main thread", 
also the author just added notification recently, and i will be able to get native notification from application icon instead of using "plyer" with ghost notification side effect.
still Notification works only on windows, tested on windows 10, hope the author can support linux notification too.
but I still couldn't run it on windows 8-32 bit, I am not sure if the problem at my end or not, anyway i opened issue at https://github.com/moses-palmer/pystray/issues/50

**Comment by PySimpleGUI** [comment]
Thank you SO much for all this help.

I have hired a consultant to create code that is part of user programs, but has the same PySimpleGUI APIs so that the code is portable to all ports of PySimpleGUI.  Trying to unify the System Tray so that tkinter users can enjoy it with the same simple PySimpleGUI SystemTray APIs.  I hope it's possible!  You've given me hope that it is and a bit of a roadme.

He's working now on displaying the menus based on the PySimpleGUI menu data structure (which is weird, but want to keep it so that it can be used across all ports).

It's great to have your code as an example.  Thank you for the info about notifications and limitations on other platforms.  At this point, I would take Windows only happily.... it's not ideal, but heck, it's something!

Without your inspiration, I wouldn't be trying this at all, so thank you.
