### ISSUE TITLE
You're getting close on Vinta!

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/PyIDM#181]
![image](https://user-images.githubusercontent.com/46163555/97152376-2b35e000-1747-11eb-831b-10a90c0ae1a0.png)

I got an alert that the pull request I did way back has been approved.  But, when I checked the readme, it's not been merged.  It appears there's a conflict.

You might want to keep an eye on it so it can be nudged forward.  It'll be great visibility if you get listed, not that you need it at this point :-)

Here's a link to the pull request:
https://github.com/vinta/awesome-python/pull/1450

**Comment by pyIDM** [comment]
Thanks Mike and wish you the best
