### ISSUE TITLE
"Nothing to download" trying to download a youtube link

### ISSUE THREAD

**Issue by pietracorvo** [pyIDM/PyIDM#183]
Hi,

I stumbled across your cool app and instantaneously had to install it on my Ubuntu 18.04 LTS. The GUI runs fine, but when I am trying to download a youtube link (like one you use in your user guide) a windows pops up with the notification 'Nothing to download' .

You can see the situation here:
 ![screenshot](https://user-images.githubusercontent.com/30528134/97751872-588ddf80-1af3-11eb-97e0-baf07c98e6e8.png)

On the console from which I started the app with `python3 -m pyidm` it prints the [following stuff](https://github.com/pyIDM/PyIDM/files/5467398/console_output.txt).

Do you have an idea what is going on here?
(And sorry if the problem is obvious, I am not a professional developer :-) )

Btw.: M python version is `Python 3.6.9`

Best
alexander

**Comment by pyIDM** [comment]
@pietracorvo 
thanks for your feedback
this problem due to an obsolete option value in "libcurl", as in your log:
`pycurl.error: (43, 'CURLOPT_SSL_VERIFYHOST no longer supports 1 as value!')`
i will fix this problem and let you know once i make a new release

**Comment by pyIDM** [comment]
@pietracorvo 
just added a pypi release 
please try to install it by running:
`python -m pip install pyidm --upgrade --no-cache`
and see if the problem solved

**Comment by pietracorvo** [comment]
Hi,

thanks for the help, now it works like a charm :+1:
