### ISSUE TITLE
[Feature Request] New youtube-dl Support

### ISSUE THREAD

**Issue by fidodkk** [pyIDM/PyIDM#184]
Hello.

I hope support for the new version of youtube-dl will be added and support for youtube-dlc will remain.

https://gitlab.com/dstftw/youtube-dl/

**Comment by pyIDM** [comment]
@fidodkk 
Thanks for following up with youtube-dl status
youtube-dl and youtube-dlc are supported in PyIDM and you can switch between them from Settings

![image](https://user-images.githubusercontent.com/58998813/97811351-f0b1d300-1c71-11eb-9ec3-0f0b78867dfc.png)

however i still need to fix youtube_dl update in "windows exe release"

**Comment by fidodkk** [comment]
Thanks for info.
