### ISSUE TITLE
[Enhancement] PyPI release?

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#19]
I've seen some interesting PyPI releases for applications like HowDoI that create a real program from a pip install.  In other words, I pip installed HowDoI (and other programs that I don't think required an EXE) and the result was I was able to run it was a program by typing the name at the command prompt.

A PyPI release gives you another distribution channel and also opens up a lot of statistics.  I think it's worth a look.  I released a couple of "applications" this way that were not done right, but they work.  This EXE maker is one 
https://github.com/PySimpleGUI/PySimpleGUI/tree/master/exemaker

While not well advertised to say the least, this program still got 100 downloads this past week
![image](https://user-images.githubusercontent.com/46163555/71585499-c6890500-2ae4-11ea-8847-79f1e1949b44.png)

Once on PyPI a number of sites exist that will help you see what's happening.

https://pypistats.org/packages/pysimplegui

**Comment by pyIDM** [comment]
This is nice, especially the stats, I will give it a try, thanks for suggestion :+1:

**Comment by PySimpleGUI** [comment]
After seeing what my `ptoaster` package has done in the first few days, I recommend releasing via PyPI even more.  People are **lazy**!

Think about what it takes for someone to install via github versus pip.  pip is a single line command you type into a shell window.  "Installing" via github means navigating to the GitHub site, then either downloading a ZIP or opening in a GitHub desktop program.  Then there's the matter of placing the code someone on your path so that it's found.  pip took care of all of that.

Check this out... my GitHub page for ptoaster has had only 35 total visitors.

![image](https://user-images.githubusercontent.com/46163555/72919574-b647fc80-3d15-11ea-84ae-673988531e18.png)


But I got 341 downloads via pip installs

![image](https://user-images.githubusercontent.com/46163555/72919659-dc6d9c80-3d15-11ea-9d3e-24275d3ede21.png)

**Comment by pyIDM** [comment]
I’m totally agree with you it will be much easier to pip than github clone
will give myself a push to use PyPI for release distribution, I think i am the lazy one here 😂

**Comment by pyIDM** [comment]
Done pypi release at https://pypi.org/project/pyIDM/ 
Thanks Mike for the suggestion 👍

**Comment by PySimpleGUI** [comment]
VERY nice!

Now you can sit back and watch the stats more easily too.
https://pypistats.org/packages/pyidm
https://pepy.tech/project/pyidm

They say 669 pip installs already.  Nice

I'm guessing that's a few more than came to your GutHub to download it

![image](https://user-images.githubusercontent.com/46163555/73143901-5632bc80-406d-11ea-846a-ee77d6900722.png)

**Comment by pyIDM** [comment]
WoW!! these statics are beautiful, thanks a lot
