### ISSUE TITLE
I can't change file name. Can you please check?

### ISSUE THREAD

**Issue by phongchot** [pyIDM/PyIDM#191]
Thank you so much.

**Comment by pyIDM** [comment]
@phongchot 

follow screenshots below and press on 3 dots on front of the name and popup will show to change the name, let me know if you have another problem 

![image](https://user-images.githubusercontent.com/58998813/99299162-81340a00-2853-11eb-810f-34dfb30775f0.png)

![image](https://user-images.githubusercontent.com/58998813/99299187-898c4500-2853-11eb-948a-40eb2049e90a.png)


![image](https://user-images.githubusercontent.com/58998813/99299220-9741ca80-2853-11eb-8cf7-ec63cbdf1d9d.png)

![image](https://user-images.githubusercontent.com/58998813/99299254-a294f600-2853-11eb-88bb-370c775f5df2.png)

**Comment by phongchot** [comment]
I did the same. But the downloaded file doesn't change its name.

**Comment by pyIDM** [comment]
@phongchot 
Found This as a bug, and will work on a fix for it
