### ISSUE TITLE
Feature Request: option to set a custom user agent

### ISSUE THREAD

**Issue by nero-0** [pyIDM/PyIDM#199]
Hi!
I'd like to see an option to set a custom user agent in PyIDM (i.e. --user-agent), in some cases it is necessary in order to grab the links.

Kind regards

**Comment by pyIDM** [comment]
@nero-0 
is it http-headers or just user-agent? please submit an example of a user agent you want to include

for your info:
currently youtube-dl will automatically create http-headers with a random user agent every time to avoid blocking by any website
these same headers will be used by "PyIDM".

**Comment by nero-0** [comment]
@pyIDM 
I'll say a situation in which it is useful for me.

For the Funimation website, due to some problem in the extractor, when trying to capture the links I get a failure in the certificate verification `[SSL: CERTIFICATE_VERIFY_FAILED]`, so I use --no-check-certificate, which makes the extractor start, but fails when trying to extract the information returning a json error `Failed to parse JSON No JSON object could be decoded`. Then, as a workaround, I use cookies and a custom user agent, e.g. `Mozilla / 5.0 (X11; Linux x86_64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 80.0.3987.132 Safari / 537.36`, which generally makes it work, if not, it is necessary to try others.

**Comment by nero-0** [comment]
@pyIDM
I'll say a situation in which it is useful for me.

For the Funimation website, due to some problem in the extractor, when trying to capture the links I get a failure in the certificate verification `[SSL: CERTIFICATE_VERIFY_FAILED]`, so I use --no-check-certificate, which makes the extractor start, but fails when trying to extract the information returning a json error `Failed to parse JSON No JSON object could be decoded`. Then, as a workaround, I use cookies and a custom user agent, e.g. `Mozilla / 5.0 (X11; Linux x86_64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 80.0.3987.132 Safari / 537.36`, which generally makes it work, if not, it's necessary to try others.

**Comment by nero-0** [comment]
@pyIDM
I'll say a situation in which it is useful for me.

For the Funimation website, due to some problem in the extractor, when trying to capture the links I get a failure in the certificate verification `[SSL: CERTIFICATE_VERIFY_FAILED]`, so I use --no-check-certificate, which makes the extractor start, but fails when trying to extract the information and returns me a json error `Failed to parse JSON No JSON object could be decoded`. Then, as a workaround, I use cookies and a custom user agent, e.g. `Mozilla / 5.0 (X11; Linux x86_64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 80.0.3987.132 Safari / 537.36`, which generally makes it work, if not, it's necessary to try others.

**Comment by pyIDM** [comment]
@nero-0 
no problem will add this option

**Comment by nero-0** [comment]
Thanks! Glad to hear that.

**Comment by pyIDM** [comment]
Hello @nero-0 
feature already implemented in new version 2020.12.25
you can update thru PyIDM's Settings>update and press "Manually check for update" button
