### ISSUE TITLE
Embedding icons

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#20]
I just noticed you've got an icons folder.  I'm wondering why you ended up going that route versus using base64 versions of them.  They are the only files you need to distribute with your application and represent the only thing that can truly go wrong.  

If you made them into Base64 strings then you'll end up with an applications that is entirely self-contained as a single .py file.  That would be a nice thing as you can distribute your application super easy.... even by emailing the single file to someone would work.

**Comment by pyIDM** [comment]
It's already in my todo list, I've already ditched all button icons and the turn now on these icons, will get into it very soon :+1:

**Comment by PySimpleGUI** [comment]
[converted_icons.py.txt](https://github.com/pyIDM/pyIDM/files/4011732/converted_icons.py.txt)

I added the `icon` to the main part and it ran with no problems.  Was a 1-line change.  Nice.  I dunno what the other 2 will require.  Here they are if you want what you've got converted.  You may want to shrink down the .ico file a ways as it's 48K which is pretty hefty for a base64 string.  At least it's at the end.  Dunno how you'll structure it but I try to make it so these are at the end if possible.

You're kicking ass on this project.  I suggested it in a post on reddit tonight as someone else posted simple front-end downloader and other people were listing what they did.

He got 400 upvotes already.... for something so trivial looking.  I just know you're going to go through the roof.

https://www.reddit.com/r/Python/comments/ehmekl/tkinter_youtube_downloader_project_ive_been/fclq5x8/?context=3

**Comment by pyIDM** [comment]
Thanks Mike for all these suggestions, and thanks for mentioning my project on reddit :+1:

**Comment by PySimpleGUI** [comment]
I think you should DEFINITELY post this project to Reddit yourself as a topic!

It WILL go nuts when people hear about how automated you've made it.  The use of the clipboard, etc.

You're doing SO much more than the posted programs I saw in the Reddit post and deserve to get noticed more.

**Comment by pyIDM** [comment]
This looks promising, thanks Mike for all this positive energy 😄 , I think I will post about it in reddit within next couple of days

**Comment by pyIDM** [comment]
Done ... commit 2d929b32e7e5c95ed38c01750bf0e55db4384768
Thanks for your great help
