### ISSUE TITLE
Add font dependencies to requirements

### ISSUE THREAD

**Issue by mirekphd** [pyIDM/PyIDM#200]
I've installed all suggested dependencies on my Ubuntu 18.04, yet could not process even a single mp3 extraction.

The error I was consistently getting was: "X Error of failed request:  BadLength (poly request too large or internal Xlib length error)".

Then I found [this Issue](https://github.com/LukeSmithxyz/voidrice/issues/284#issue-436209964) and installed the following fonts:

```
sudo apt update && sudo apt install fonts-symbola fonts-linuxlibertine fonts-inconsolata fonts-emojione
```

... and that solved the problem for me. Perhaps it is therefore advisable to add them to requirements?

**Comment by pyIDM** [comment]
@mirekphd 
Thanks for sharing your issue and the fix :+1:

**Comment by pyIDM** [comment]
Added fonts requirements to readme file under "known Issues" section
