### ISSUE TITLE
Youtube links are getting recognized as html files

### ISSUE THREAD

**Issue by SP-XD** [pyIDM/PyIDM#202]
I am on Kubuntu(focal fossa). And I have tried reinstalling pyidm and have tried various video links for downloading, and it is not getting recognised for some reason.

>> Load Application setting from /usr/local/lib/python3.8/dist-packages/pyidm
>> setting.cfg not found
>> Load previous download items from /usr/local/lib/python3.8/dist-packages/pyidm
>> downloads.dat file not found, looking for legacy "downloads.cfg" file
>> downloads.cfg file not found
>> load_json() > error:  [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyidm/user_themes.cfg'
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> youtube_dl version: 2020.03.24, load_time= 0 seconds
>> youtube_dlc version: 2020.11.11-3, load_time= 0 seconds
>> set default extractor engine to: youtube_dl <module 'youtube_dl' from '/usr/lib/python3/dist-packages/youtube_dl/__init__.py'>
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.12.25 Non-Frozen
>> operating system: Linux-5.4.0-58-generic-x86_64-with-glibc2.29 - x86_64
>> Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]
>> current working directory: /usr/local/lib/python3.8/dist-packages/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
url_watchdog, new url:  https://www.youtube.com/watch?v=l1EssrLxt7E&list=PLfqMhTWNBTe3H6c9OGXb5_6wcc1Mca52n&index=1
playlist here
>> start create video playlist
>> [youtube:playlist] Downloading playlist PLfqMhTWNBTe3H6c9OGXb5_6wcc1Mca52n - add --no-playlist to just download video l1EssrLxt7E
-------------------- start download page
>> [youtube:playlist] PLfqMhTWNBTe3H6c9OGXb5_6wcc1Mca52n: Downloading webpage
-------------------- start download page
>> [youtube] l1EssrLxt7E: Downloading webpage
>> ERROR: l1EssrLxt7E: YouTube said: Unable to extract video data
>> controller._create_video_playlist: argument of type 'NoneType' is not iterable
url_watchdog, new url:  https://www.youtube.com/watch?v=BYB9DYlzJ-w
playlist here
>> start create video playlist
-------------------- start download page
>> [youtube] BYB9DYlzJ-w: Downloading webpage
>> ERROR: BYB9DYlzJ-w: YouTube said: Unable to extract video data
>> controller._create_video_playlist()> No streams found

**Comment by pyIDM** [comment]
@SP-XD 
looking at your attached log, found youtube-dl version is very old "youtube_dl version: 2020.03.24", 

you can go to Settings>update section and click "Manually Check for update" button and follow instructions

or

you can try this in terminal:
python3 -m pip install youtube-dl --upgrade

then restart PyIDM and see if this works

**Comment by SP-XD** [comment]
> @SP-XD
> looking at your attached log, found youtube-dl version is very old "youtube_dl version: 2020.03.24",
> 
> you can go to Settings>update section and click "Manually Check for update" button and follow instructions
> 
> or
> 
> you can try this in terminal:
> python3 -m pip install youtube-dl --upgrade
> 
> then restart PyIDM and see if this works

Ok thank you very much, updating youtube-dl and awsometkinter to latest version solved the issue.
