### ISSUE TITLE
Download with server timestamp

### ISSUE THREAD

**Issue by ZorinArch** [pyIDM/PyIDM#204]
Hi,

PyIDM change server timestamp when you download a file. i need to download files with server timestamp.

Thanks,

**Comment by pyIDM** [comment]
@ZorinArch 
pyidm will try to figure out the timestamp of the remote file by looking at "last-modified" key in server response headers, and if available will write this timestamp to the local file

note:
 this will not change file creation time, only "last modified" time will be updated to match server timestamp.
