### ISSUE TITLE
Feature request: Option to add numbers to playlist titles

### ISSUE THREAD

**Issue by Mr-Personality** [pyIDM/PyIDM#209]
**Problem:**
I just downloaded a playlist and found that all the tracks were jumbled up because no number had been added. To add to the confusion, the main window places numbers before the titles, making it look as though numbers will be included.

**Solution:**
I think the Playlist Download Window should have a new option: "Add track numbers", next to the "Select all" option.

**Comment by pyIDM** [comment]
@Mr-Personality 

> I think the Playlist Download Window should have a new option: "Add track numbers", next to the "Select all" option.

Agree :+1:

**Comment by pyIDM** [comment]
done, feature will be available with coming release
