### ISSUE TITLE
Add a copyright and license

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#21]
In the very least, add a copyright to the top of your source file.  It wouldn't be a bad idea to add your license info in there too.  You've got everything in one nice little package.... a single file.  I would add a little bit of protection.

**Comment by pyIDM** [comment]
I really don't understand much about these all types of licenses "GPL, LGPL, MIT, .......", I think i need to do some research, googling, and with some patience I might understand something :smile:

**Comment by pyIDM** [comment]
Done .. Added license "GNU LGPLv3"  file to main repo. and copyright notice to pyIDM.py file
