### ISSUE TITLE
Login Suggestion

### ISSUE THREAD

**Issue by oOMelhor** [pyIDM/PyIDM#212]
Hi.
Some sites require authentication to download, for example udemy.com.
It would be interesting to have an option to add the username and password to certain addresses, for PyIDM to send the credentials to youtube_dl

**Comment by pyIDM** [comment]
@oOMelhor 
This is already implemented in PyIDM, user credentials will be passed to libcurl and youtube-dl 
note: user/password will not be saved on disk, which means you have to enter these info again if you restarted PyIDM

Login:
![image](https://user-images.githubusercontent.com/58998813/105399013-b3832e80-5c2b-11eb-9ddc-5ad01beec1bd.png)
