### ISSUE TITLE
Feature Request: Dropdown on the Folder menu for frequently used download folders

### ISSUE THREAD

**Issue by FaithfulObserver** [pyIDM/PyIDM#214]
Problem:
Switching between several frequently used download folder paths takes too much effort to browse.

Solution:
Add a dropdown containing frequently used folder history on the Folder menu (maybe for a maximum of 5 folders?)

**Comment by pyIDM** [comment]
@FaithfulObserver 
good idea, will be added soon

**Comment by pyIDM** [comment]
done, 
latest release at https://github.com/pyIDM/PyIDM/releases/latest
