### ISSUE TITLE
The downloaded file uses the modified date from the server, not the same as the date created locally

### ISSUE THREAD

**Issue by FaithfulObserver** [pyIDM/PyIDM#215]
First, thank you for the new frequently used download folders dropdown menu. That's very handy.

Second, I found the downloaded file uses the modified date from the server, not the same as the date created locally. This will be a problem if there are a lot of files in one folder and you don't know which ones were recently downloaded when sorted by date in Windows Explorer. For me, if you really need to know when the file was created for the first time from the server, just look at the metafile data instead of the date modified file attribute.

Maybe need an option to disable this behavior?

**Comment by pyIDM** [comment]
@FaithfulObserver 

> Maybe need an option to disable this behavior?

Agree, an option should be added to control this feature.

**Comment by pyIDM** [comment]
done, feature will be available with coming release
