### ISSUE TITLE
Add ability to schedule downloads

### ISSUE THREAD

**Issue by raelb** [pyIDM/pyIDM#22]
Hi, what I had in mind was the ability to schedule the "Resume All" function.

e.g. Resume All at 9:00 PM.

Thanks

**Comment by pyIDM** [comment]
@raelb 
This is a good idea, I will work on it,
feel free to submit any other ideas. more ides == more improvement to this application :)

**Comment by pyIDM** [comment]
Added ability to schedule downloads, you can right click any video and choose to schedule or cancel schedule
Also added a "Schedule All" button

exe release available at https://github.com/pyIDM/pyIDM/releases/latest

![image](https://user-images.githubusercontent.com/58998813/71861322-a073ee00-30fe-11ea-9718-1e8fb3b20776.png)

**Comment by raelb** [comment]
Great, thanks
