### ISSUE TITLE
Download format progress bar is not complete after load playlist

### ISSUE THREAD

**Issue by raelb** [pyIDM/pyIDM#24]
Hi,
Is this a bug? After loading a playlist, the format progress bar is not complete:

https://www.youtube.com/playlist?list=PLillGF-RfqbYhQsN5WMXy6VsDMKGadrJ-

![image](https://user-images.githubusercontent.com/13108198/71633847-942ff280-2c1f-11ea-9e56-d6c9ae167d58.png)

**Comment by pyIDM** [comment]
yes, I believe this is a bug, thanks for reporting :+1:

**Comment by PySimpleGUI** [comment]
Perhaps add 1 to your "current count" when you call `update_bar`?

**Comment by pyIDM** [comment]
I recalled i fixed this issue before, but I need to check what happened, because I use threads to fetch streams info, and one of the threads might not update the progress bar

i did add one before as a quick fix as you suggested but found a problem in one thread, so I should investigate the main cause of the problem

**Comment by PySimpleGUI** [comment]
I just happened to have a Reddit Scraper I did up on the screen at the time is why I commented :-)

```python
            num_submissions = int(values['-LIMIT-'])
            for num, submission in enumerate(submissions):
                window['-PROG-'].update_bar(100*(num+1)//num_submissions)
```

I'm not sure I do this normally or not, but it's what I did for this program.

**Comment by pyIDM** [comment]
@PySimpleGUI 
I did some investigation and found threads add up progress bar value correctly untill it reaches a value 96 and everything was ok until the next addup was 104 the progress bar ignored the value

here is an example code to show my point:
```
import PySimpleGUI as sg
window = sg.Window('', [[sg.ProgressBar(max_value=100, key='-PROG-', size=(50, 10))]], finalize=True)
window['-PROG-'].update_bar(90) # update successfully since 90 < max_value
window['-PROG-'].update_bar(104) # it won't update

window()
```

I believe the progress bar accept only integer, but I tried to give it a float number and it didn't complain
This is my work around in my app for calculating the progress bar increment
changed this line `bar_incr = 100 // len(pl_info) + 1` to `bar_incr = 100 / len(pl_info)` which gives a float sometimes but it works
I don't know if this is the right thing to do or not?

**Comment by pyIDM** [comment]
This is the output of 13 threads updating the progress bar value, it shows all threads finished correctly and set progress bar value

```
>> MainWindow.get_video:> num=4 - self.s_bar=8 - s_bar_incr=8
>> MainWindow.get_video:> num=8 - self.s_bar=16 - s_bar_incr=8
>> MainWindow.get_video:> num=1 - self.s_bar=24 - s_bar_incr=8
>> MainWindow.get_video:> num=9 - self.s_bar=32 - s_bar_incr=8
>> MainWindow.get_video:> num=11 - self.s_bar=40 - s_bar_incr=8
>> MainWindow.get_video:> num=6 - self.s_bar=48 - s_bar_incr=8
>> MainWindow.get_video:> num=7 - self.s_bar=56 - s_bar_incr=8
>> MainWindow.get_video:> num=2 - self.s_bar=64 - s_bar_incr=8
>> MainWindow.get_video:> num=5 - self.s_bar=72 - s_bar_incr=8
>> MainWindow.get_video:> num=12 - self.s_bar=80 - s_bar_incr=8
>> MainWindow.get_video:> num=0 - self.s_bar=88 - s_bar_incr=8
>> MainWindow.get_video:> num=3 - self.s_bar=96 - s_bar_incr=8
>> MainWindow.get_video:> num=10 - self.s_bar=104 - s_bar_incr=8 # it ignores the value
```

**Comment by PySimpleGUI** [comment]
Yea, PySimpleGUI isn't handling the > case as it assumed that the max count value will eventually be hit prior to turning >.

**Comment by pyIDM** [comment]
Thanks a lot, this is great

**Comment by PySimpleGUI** [comment]
Done... try the version 4.14.1.5 that's on GitHub now.

**Comment by pyIDM** [comment]
Just tested now, it works flawlessly, thanks a lot :+1:

**Comment by pyIDM** [comment]
@raelb 
I will mark this issue as done and the fix will be included in the next exe release, but i will delay the release time shortly untill i decrease the exe build size to be under 15MB  instead of 35MB 

Thanks for your valuable suggestions and ides :100: , waiting for more :)

**Comment by pyIDM** [comment]
@raelb 
a new exe release with progress bar issue fixed available on https://github.com/pyIDM/pyIDM/releases/latest
the exe file size is now under 15 MB
