### ISSUE TITLE
برنامج ممتاز

### ISSUE THREAD

**Issue by haseeb2** [pyIDM/pyIDM#26]
ممكن تزودنا بالدورات التى اعتمدت عليها للتعلم البايثون

**Comment by pyIDM** [comment]
الحقيقة لم اتعلم البايثون من خلال اى دورات ولكن بدأت من موقع بايثون مثل
[The Python Tutorial](https://docs.python.org/3.7/tutorial/index.html)
ثم بعد ذلك بدأت فى عمل هذا البرنامج وكلما عجزت عن القيام بشئ ابحث عنها فى جوجل وافضل الاجابات اجدها فى موقع 
[stackoverflow](https://stackoverflow.com/)


شكرا جزيلا
ولا تتردد فى طلب اى مساعدة
