### ISSUE TITLE
Suggestion: Split up code into multiple files

### ISSUE THREAD

**Issue by raelb** [pyIDM/pyIDM#27]
Hi there,
This is just a suggestion. I was interested to look into the code and I was surprised to see the entire app is just 1 single file.
I thought it would be easier for an outsider to understand, and perhaps easier for you to maintain, if the code is split up a bit into separate files.

**Comment by pyIDM** [comment]
Hello raelb,
I use pycharm and I marked regions in the file, this is how it looks like when I press "ctr  shift -" it will fold all regions and it is organized and very handy to get things
I don't know if it will be more easier if splitted, 

right now it is all in one independent file, the only exception is icon files, which I am trying to replace them by base64 string but have an issue of bad image quality when convert them to strings

![Screenshot_20200105_181547](https://user-images.githubusercontent.com/58998813/71782849-6bc14300-2fe7-11ea-851c-31393bc18344.png)

anyhow I will think about it again, 
thanks a lot for your valuable suggestions

**Comment by PySimpleGUI** [comment]
There shouldn't be any difference in the quality of the image if it's base64 encoded.  Did you use the utility supplied in the PySimpleGUI demos?

**Comment by pyIDM** [comment]
@PySimpleGUI 
I used python module `base64` with both `base64.b64encode` and `base64.b64decode`, and it gave me a bad quality,  I looked into one of PySimpleGUI [demos](https://github.com/PySimpleGUI/PySimpleGUI/blob/master/DemoPrograms/Demo_Base64_Image_Encoder.py) and it used the same library, maybe I am missing something, I will check your other demos and see how it goes

**Comment by PySimpleGUI** [comment]
You should be able to make 2 image elements right next to each other and do a side by side compare.

Why are you decoding at all?  PySimpleGUI takes base64 strings directly in addition to file names.

**Comment by PySimpleGUI** [comment]
I thought I posted a file with them already encoded for you earlier?

**Comment by pyIDM** [comment]
ok I will try again and see how it goes

**Comment by PySimpleGUI** [comment]
Did I give this to you already?  

I could swear I modified your code and swapped them out with no problem.

[converted_icons.py.txt](https://github.com/pyIDM/pyIDM/files/4024029/converted_icons.py.txt)

**Comment by PySimpleGUI** [comment]
I must have only tried it locally.  What I did was copy the `icon` variable from the converted_icons.py file and added it to the end of your file just before this code:

```python
    # icon = app_icon #image_file_to_bytes(app_icon, (50, 50))
    print('starting application')
    if singleApp():
        Thread(target=import_ytdl, daemon=True).start()
        Thread(target=clipboard_listener, daemon=True).start()
        main_window = MainWindow()
        main_window.run()
```

**Comment by PySimpleGUI** [comment]
There shouldn't be a quality hit as I converted your PNG file into a .ICO file and left it HUGE.  It's a 47K .ico file which is why the string is so long.  It's way too big of an image for an icon.  It's being shrunk way down prior to being displayed so the extra quality is being tossed anyway.  I suggest shrinking it prior to encoding it.

**Comment by pyIDM** [comment]
yes I just tried now the one you sent, I see no difference in quality on linux, I will try it on windows too, if its ok, then it will be a good hit
just moments and will let you know once testing on windows

**Comment by PySimpleGUI** [comment]
Oooops... I didn't convert it into an ico file, you did :-)

**Comment by PySimpleGUI** [comment]
![58998813](https://user-images.githubusercontent.com/46163555/71786288-c81c6680-2fd7-11ea-925d-f8ce4c4e26b5.png)

I downloaded your avatar from this issue and it's only 8K.  Maybe try converting it if the other one is too big to include in the file.

**Comment by pyIDM** [comment]
I tried on windows and base64 seems a little pixelated
![image](https://user-images.githubusercontent.com/58998813/71786482-68907c00-3014-11ea-9cdb-fcb73cd6c94c.png)

I am not sure if it worth the difference, I like to get base64 to be more simple

**Comment by PySimpleGUI** [comment]
Yea, I see what you mean.  That's really really weird as both are being supplied by tkinter.

I see from my code that you can specify a bytes object for icon as well as pngbase64.  I think that means the `icon` parameter can be both a filename and base64 string.

Either way it's all tkinter's fault 😉

```python
    # ------------------------- SetIcon - set the window's fav icon ------------------------- #
    def SetIcon(self, icon=None, pngbase64=None):
        """
        Sets the icon that is shown on the title bar and on the task bar.  Can pass in:
        * a filename which must be a .ICO icon file for windows
        * a bytes object
        * a BASE64 encoded file held in a variable

        :param icon: (str) Filename or bytes object
        :param pngbase64: (str) Base64 encoded GIF or PNG file
        """
        if type(icon) is bytes or pngbase64 is not None:
            wicon = tkinter.PhotoImage(data=icon if icon is not None else pngbase64)
            try:
                self.TKroot.tk.call('wm', 'iconphoto', self.TKroot._w, wicon)
            except:
                wicon = tkinter.PhotoImage(data=DEFAULT_BASE64_ICON)
                try:
                    self.TKroot.tk.call('wm', 'iconphoto', self.TKroot._w, wicon)
                except:
                    pass
            self.WindowIcon = wicon
            return

        wicon = icon
        try:
            self.TKroot.iconbitmap(icon)
        except:
            try:
                wicon = tkinter.PhotoImage(file=icon)
                self.TKroot.tk.call('wm', 'iconphoto', self.TKroot._w, wicon)
            except:
                try:
                    wicon = tkinter.PhotoImage(data=DEFAULT_BASE64_ICON)
                    try:
                        self.TKroot.tk.call('wm', 'iconphoto', self.TKroot._w, wicon)
                    except:
                        pass
                except:
                    pass
        self.WindowIcon = wicon
```

**Comment by pyIDM** [comment]
I will try this code and see how it goes

**Comment by pyIDM** [comment]
oh! I miss understood, this is the internal implementation of pysimpleGUI

**Comment by pyIDM** [comment]
yes, the base64 string work on both windows and linux, but if i want to use icon file i have to keep 2 file formats, .png for linux and .ico  file for windows, i will try if i can make base64 quality better on windows

**Comment by PySimpleGUI** [comment]
I use a single file for both windows and linux and it's embedded in my PySimpleGUI file.  You don't need 2.

**Comment by PySimpleGUI** [comment]
Oooppss... I see you said FILE now... yea, if it's a file you have to use ICO for windows.  But for base64 it can be either.

**Comment by pyIDM** [comment]
Found it!
I resized the .png file from 256pixels-31Kb  to 16pixels-889bytes and the result is very close


![image](https://user-images.githubusercontent.com/58998813/71787074-8ca38b80-301b-11ea-887b-903b5304b275.png)

I think I will go ahead with this results

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/71787157-644b6b00-2fe2-11ea-969d-a09462d9bcd7.png)

Right, don't make tkinter resize it.  Here's my results from a tiny 32x32 pixel GIF.  The artifacts are from the tkinter resize.

**Comment by PySimpleGUI** [comment]
![icon_gif](https://user-images.githubusercontent.com/46163555/71787179-a83e7000-2fe2-11ea-843d-b433fb545c9c.gif)

Here's the GIF I used for the icon.

**Comment by pyIDM** [comment]
This is what i used almost same as yours but less size, I kept both of your version and mine to test on linux
```python
icon16 = b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAGKgAABioBRGS1VAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAL2SURBVDiNfZNfaFN3FMc/9yb33sSYmzWmrcvIam7a4B+KG6WbPiyYaUFFusFwexjrhJbpHgQ3hCL40LfpQ/GlxWI7tpm9zbEtlg07N7E4ZhUphlJsu6TBuLDZgM3d7y7LvTXZw1SCwg6ct+/5wjnf85F4puqdus5APM7uUIhNAKUS+cVFLpsmEyDNNaqlhkFN1znT28vhRAK5WCxRKJQBiEQChMMhpqd5mE4zZpp8DJLdYFDXDIMf+vtJZrNZbqRmeNVZoIVVbBTyNDOrdJDs245hxBgf5+d8nn0g2RKArtfPDg5y5MrULYyrFznG59i4sfAg8CLw8AA/X/Imrl3dvN7zMqdPM2Ka0lEX1DsPHmTcNLNS8NsLDHKO6romfH3vsLZhI6W7FlbNSwWNTeSZzQdQo37a24NdmczQ17KuM5BIIN9IzfARnyHwsfHcKWITQ2weO8FLX5xEEMDCj8DPTmaYPH+HRAKXrtMvd3Swp1gs8YqzgI2bivYcf166xTfyPu5f/42KqGGhI9AR+Kmi0uSYFIsl4nF65OZmXiwUyjzPKhYezKqbpdQ11id3En33NX4d/oWKEkRpi2DhQ+BDY41CoUwoRJsbqAP8g4LAi4UXwTr8rS3Ua3X2pt6npbMVkDgSGsb626aK8iR798oKhR07AlsztDy6+n+duZDB3vAdFdtFpebijU+S/LXmRiBRxkskEuD2be66l5b4MRwObU0pMfY7fhxULBSEI3Nl5DoCH4FtLxCezLFqy5goCNVHOBxicZEpV7U6dC8Q4HB7lyZPz2q0kX+0igeBhkDlj5UqD0SN7LLJEpt561CMXC748OZNPpBBmkunGTOMGPKubr7iAGU0BBIWYFFHANM//c4CW9iebMUwYqTTjII0//iV1WiU7wcG2J3LZZk8f4egU0alRhU3ZTwIdT1vvxfFMGJMTHB5eZn9IDmNMKm6znBvLx8mErj+B6ZR0+Q4SM5TND4x2qbr9Mfj9DyF85Rp8ilI843qfwHY3i91Cg2YCQAAAABJRU5ErkJggg=='
```

**Comment by barhouum7** [comment]
Good job guys!
This result will be nicer than the first one👏

**Comment by wanisramdani** [comment]
Is there a reason for writing the code in one independent file other than getting the benefit of using pycharm regions structere feature,
If not its better to split them into multiple files so people can easily contribute, not having to mention that there are who don't use pycharm
If there is no reason for it I volunteer to splitting them
