### ISSUE TITLE
Use consistent package version

### ISSUE THREAD

**Issue by yochananmarqos** [pyIDM/pyIDM#29]
The GitHub version is 4.3.0 yet the PyPI version is 2020.1.20.

**Comment by pyIDM** [comment]
This is a good catch,
Actually there is a Plan to use a time based version instead of current version scheme,
the github version and releases will be updated soon
Thanks for pointing this out,

**Comment by pyIDM** [comment]
All updated to version 2020.1.27
- Github source code
- latest windows executable release
- pypi release

**Comment by yochananmarqos** [comment]
GitHub version is 2020.01.27 and PyPI is 2020.1.27.

**Comment by pyIDM** [comment]
> 2020.01.27

that's correct :+1:

**Comment by yochananmarqos** [comment]
...okay. That's on purpose, then?

**Comment by pyIDM** [comment]
yes version scheme will be based on date, which is more practical, the version number will tell you how old is your release

> 2020.01.27

means 27th of Jan. 2020

**Comment by yochananmarqos** [comment]
No, no, no. Look again:
GitHub: 2020.**01**.27
PyPI: 2020.**1**.27

**Comment by pyIDM** [comment]
oh! sorry I didn't understand your point
it's definitely a mistake, I will check my setup file it should load version automatically from version.py file

**Comment by pyIDM** [comment]
I found out this is done automatically by setuptools "version normalizing"
here is a warning message I didn't notice before
`UserWarning: Normalizing '2020.01.27' to '2020.1.27'`

and found out an open issue here https://github.com/pypa/setuptools/issues/308

I will check for a solution or workaround

**Comment by yochananmarqos** [comment]
Yeah, I was going to mention that as well but I forgot.
