### ISSUE TITLE
You MUST get listed in the directory of "Python Applications"

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#3]
I started playing with the code today to see exactly what it does and I'm STUNNED!

There is SO MUCH CODE and so much complexity to what you're doing.  It's an amazing piece of work.  I was shocked when I copied a link and before I could even paste it the download information collecting had begun.  How the heck did you do some of these things??!!!

This may be one of the most complex PySimpleGUI programs ever written, yet you're all casual about it.  It should be out there for people to see.  I'm going to be requesting it be added to  few different lists if that's OK with you.  

People need to see code like yours to understand what it takes to make a "real" end-user application.  

I love the little pop-up thing you did using I forget which package to do it.

You've got me really excited about this program now!  It's mega-cool.  Congratulations on completing what I think is an epic piece of software!

**Comment by PySimpleGUI** [comment]
Your application has been added to the list of Awesome Python Applications, but in the "Revisit list".  As explained, they're looking for 100 commits so they're convinced the project is active and being maintained or improved.  As long as there are changes shown on a regular basis on the GitHub, this application will eventually get added to the permanent list.... I'm sure of this as it's just too awesome of an app.

It would also be helpful to "get the word out" about your application.  These days, it's no longer good enough to build something really really cool in order to be noticed.  GitHub stars are one measurement of being noticed that is commonly used.

Have you posted on Reddit about this AMAZING application?  I see people going bonkers over MUCH simpler apps that are posted in r/Python. Your application is by FAR the most complex multi-windowed PySimpleGUI application I've ever seen.  It's a little scary to be honest seeing how much of the package you've utilized in your application.  Really impressive and I'm sure a GIF included in a Reddit post would get you a good amount of traffic, just from one post.  It would be cool for you to receive the proper amount of praise from the Python community for what you've built!!  

I would like to send out a tweet when/if you post.  The last time I tweeted a Reddit post on Reddit, it jumped way up in upvotes to a number > 100.  I was really shocked.  Maybe it was dumb luck, or could be the Twitter universe is paying attention.  Regardless, your post would be one I would jump on Tweeting :-)  It's simply too good not to share.  I use your screenshot as an example of the "possibilities" of what can be done with PySimpleGUI.  One screenshot from you speaks volumes!

Here was my addition request:

https://github.com/mahmoud/awesome-python-applications/issues/102

Quoting from that issue:

> Hi @PySimpleGUI! I've added Hanash to the revisit list, which mostly consists of projects which are "young", i.e., with some combination of fewer than 100 commits or low committer count. It does look like a useful tool, keep those suggestions coming!

It seem like they want to add you, so let's maybe get some exposure to your project if you're OK with that step.

**Comment by Aboghazala** [comment]
Hello Mike, 
I was surprised to see your comments and your words are really encouraging, i am sorry for late reply as I was busy last month and i couldn't check issues on github,

> It seem like they want to add you, so let's maybe get some exposure to your project if you're OK with that step.

sure i will be happy to see everyone benefit from this application and to be used as a guide for someone to make a similar applications in python

Thanks again and wish you the best :), 

@PySimpleGUI
