### ISSUE TITLE
title=Merge Error

### ISSUE THREAD

**Issue by vdgrty** [pyIDM/pyIDM#35]
I keep getting the error 
"title=Merge Error"
"Failed to merge audio_for_[youtube video name].mp4

I have FFmpeg installed on my Path in "C:\FFmpeg\bin"

**Comment by pyIDM** [comment]
@vdgrty 
please mention the application version and how you installed it "from pip, open source, or windows executable"?

**Comment by vdgrty** [comment]
> @vdgrty
> which pyIDM version number you use and how you installed it "from pip, open source, or windows executable"?

I've downloaded "pyIDM_2020.1.30_win32_win64_cx.zip" from the latest version, and just run pyIDM.exe

**Comment by pyIDM** [comment]
does pyIDM shows a popup message once it starts and asks for ffmpeg?
also can you open the folder where you downloaded the last video and check if both files exists, example if video name is football.mp4 you should see something like _temp_football.mp4 and audio_for_football.mp4.

the last thing, can you use ffmpeg from command line to try to merge the video and audio file manually , may be ffmpeg is the problem

**Comment by pyIDM** [comment]
also can you send me the video url you tried so i can test it?

**Comment by vdgrty** [comment]
When I open it, it doesn't ask for FFmpeg, and in the log is says "ffmpeg checked ok!"
This is a video I've tried:
https://www.youtube.com/watch?v=QAUzWtLMnU0
Titled: Full HD Test 1080p

When I download it, I get the error message, and the files I end up with are:
Full HD Test 1080p.mp4
audio_for_Full HD Test 1080p.mp4

**Comment by vdgrty** [comment]
How do I try to manually merge the two files from command line?

**Comment by pyIDM** [comment]
you open command prompt at the location where you have the 2 files "video and audio" and in your example you write : 

`ffmpeg -i Full HD Test 1080p.mp4 -i audio_for_Full HD Test 1080p.mp4 -c copy out.mp4`

to open a command window at your download folder you can:

press shift and right click on any empty area close to the files and choose open command prompt here

or write in address bar cmd and press enter

**Comment by pyIDM** [comment]
![image](https://user-images.githubusercontent.com/58998813/73781823-9e528d00-4799-11ea-93de-393849b1bd6e.png)

**Comment by pyIDM** [comment]
![image](https://user-images.githubusercontent.com/58998813/73781890-bfb37900-4799-11ea-8a75-61c0136078c3.png)

**Comment by vdgrty** [comment]
This is what I get:


ffmpeg -i Full HD Test 1080p.mp4 -i audio_for_Full HD Test 1080p.mp4 -c copy out.mp4
ffmpeg version git-2020-02-03-1c15111 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 38.100 / 56. 38.100
  libavcodec     58. 67.100 / 58. 67.100
  libavformat    58. 37.100 / 58. 37.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 73.100 /  7. 73.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Full: No such file or directory

**Comment by pyIDM** [comment]
can you get me the output of this command `dir` to see if these files in current folder

**Comment by vdgrty** [comment]
04/02/2020  19:49    <DIR>          .
04/02/2020  19:49    <DIR>          ..
04/02/2020  19:49         2,197,949 audio_for_Full HD Test 1080p.mp4
04/02/2020  19:49        64,344,128 Full HD Test 1080p.mp4

**Comment by pyIDM** [comment]
oh!
can you try this command, probably the spaces in names made a problem

`ffmpeg -i "Full HD Test 1080p.mp4" -i "audio_for_Full HD Test 1080p.mp4" -c copy out.mp4`

**Comment by vdgrty** [comment]
> oh!
> can you try this command, probably the spaces in names made a problem
> 
> `ffmpeg -i "Full HD Test 1080p.mp4" -i "audio_for_Full HD Test 1080p.mp4" -c copy out.mp4`

I now have a video called "out.mp4" with sound

**Comment by pyIDM** [comment]
ok, i believe there is a bug, and i will fix it and make another release 
give me a while and i will let you know once ready

**Comment by vdgrty** [comment]
Thank you

**Comment by pyIDM** [comment]
@vdgrty 
i just tested again but couldn't get the error on my windows
can you please try this link again but choose   "›  mp4 - 480 - 16.7 MB" quality and after done copy the log and post it here 
https://www.youtube.com/watch?v=QAUzWtLMnU0

**Comment by vdgrty** [comment]
> @vdgrty
> i just tested again but couldn't get the error on my windows
> can you please try this link again but choose "› mp4 - 480 - 16.7 MB" quality and after done copy the log and post it here
> https://www.youtube.com/watch?v=QAUzWtLMnU0

I just got the same error when selecting 480p output.

**Comment by pyIDM** [comment]
can you show me the output of log tab

**Comment by vdgrty** [comment]
>> brain 1: received downloading
>> brain 1: received completed
>> start downloading  audio_for_Full HD Test 1080p.mp4
>> brain 1_audio: received downloading
>> brain 1_audio: received completed
>> done downloading audio_for_Full HD Test 1080p.mp4
>> start merging video and audio files
>> running command: C:\FFmpeg\bin\ffmpeg.exe

 -i "C:\Users\Lenovo\Downloads\Full HD Test 1080p.mp4" -i "C:\Users\Lenovo\Downloads\audio_for_Full HD Test 1080p.mp4" -c copy "C:\Users\Lenovo\Downloads\out_Full HD Test 1080p.mp4"
>> cmd: 'C : \ F F m p e g \ b i n \ f f m p e g . e x e 
 
   - i   " C : \ U s e r s \ L e n o v o \ D o w n l o a d s \ F u l l   H D   T e s t   1 0 8 0 p . m p 4 "   - i   " C : \ U s e r s \ L e n o v o \ D o w n l o a d s \ a u d i o _ f o r _ F u l l   H D   T e s t   1 0 8 0 p . m p 4 "   - c   c o p y   " C : \ U s e r s \ L e n o v o \ D o w n l o a d s \ o u t _ F u l l   H D   T e s t   1 0 8 0 p . m p 4 "' - output: 'ffmpeg version git-2020-02-03-1c15111 Copyright (c) 2000-2020 the FFmpeg developers

  built with gcc 9.2.1 (GCC) 20200122

  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-f
>> Failed to merge audio_for_Full HD Test 1080p.mp4 
 ffmpeg version git-2020-02-03-1c15111 Copyright (c) 2000-2020 the FFmpeg developers

  built with gcc 9.2.1 (GCC) 20200122

  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf

  libavutil      56. 38.100 / 56. 38.100

  libavcodec     58. 67.100 / 58. 67.100

  libavformat    58. 37.100 / 58. 37.100

  libavdevice    58.  9.103 / 58.  9.103

  libavfilter     7. 73.100 /  7. 73.100

  libswscale      5.  6.100 /  5.  6.100

  libswresample   3.  6.100 /  3.  6.100

  libpostproc    55.  6.100 / 55.  6.100

Hyper fast Audio and Video encoder

usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...



Use -h to get full help or, even better, run 'man ffmpeg'

**Comment by pyIDM** [comment]
thanks, will investigate
by the way are you running windows 10 64bit?

**Comment by vdgrty** [comment]
Yeah, 64 bit windows 10.

**Comment by pyIDM** [comment]
@vdgrty 
please download this test version at https://github.com/pyIDM/pyIDM/releases/download/extra/pyidm_test.zip and let me know if your problem is fixed

**Comment by vdgrty** [comment]
@pyIDM
Unfortunately I still get the same problem. It works with 720p however, just not 1080p.

**Comment by vdgrty** [comment]
The log is:

>> looking for video streams ... Please wait
>> [youtube] QAUzWtLMnU0: Downloading webpage
>> [youtube] QAUzWtLMnU0: Downloading video info webpage
>> Dash video detected
>> check ffmpeg availability?
>> ffmpeg checked ok!
>> config.ffmpeg_actual_path =  C:\FFmpeg\bin\ffmpeg.exe


>> thread_manager 1: quitting
>> running command: C:\FFmpeg\bin\ffmpeg.exe

 -i C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4 -i C:\Users\Lenovo\Downloads\audio_for_Full_HD_Test_1080p.mp4 -c copy C:\Users\Lenovo\Downloads\Full_HD_Test_1080p.mp4
>> cmd: 'C : \ F F m p e g \ b i n \ f f m p e g . e x e 
 
   - i   C : \ U s e r s \ L e n o v o \ D o w n l o a d s \ _ t e m p _ F u l l _ H D _ T e s t _ 1 0 8 0 p . m p 4   - i   C : \ U s e r s \ L e n o v o \ D o w n l o a d s \ a u d i o _ f o r _ F u l l _ H D _ T e s t _ 1 0 8 0 p . m p 4   - c   c o p y   C : \ U s e r s \ L e n o v o \ D o w n l o a d s \ F u l l _ H D _ T e s t _ 1 0 8 0 p . m p 4' - output: 'ffmpeg version git-2020-02-03-1c15111 Copyright (c) 2000-2020 the FFmpeg developers

  built with gcc 9.2.1 (GCC) 20200122

  configurat
>> deleted folder: C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_
>> deleted folder: C:\Users\Lenovo\Downloads\audio_for_Full_HD_Test_1080p.mp4_parts_
>> file_manager 1: quitting
>> brain 1: removed item from active downloads
>> brain 1: quitting

**Comment by pyIDM** [comment]
The last thing we can check is to use another version of ffmpeg

you can change the name of your installed ffmpeg.exe file to  old.exe which located at C:\FFmpeg\bin\ffmpeg.exe, 

then download ffmpeg from here https://github.com/pyIDM/pyIDM/releases/download/extra/ffmpeg.zip and unzip it and copy ffmpeg.exe into pyIDM folder 

then try again to download 480P quality for  https://www.youtube.com/watch?v=QAUzWtLMnU0

**Comment by vdgrty** [comment]
Hi, replaced FFmpeg, and tried 480p, still the same unfortunately:

>> starting application
>> current working directory: C:\Users\Lenovo\Desktop\pyidm_test\pyIDM
>> Load Application setting from C:\Users\Lenovo\AppData\Roaming\.pyIDM
>> Load previous download items from C:\Users\Lenovo\AppData\Roaming\.pyIDM
>> check ffmpeg availability?
>> ffmpeg checked ok!
>> config.ffmpeg_actual_path =  C:\FFmpeg\bin\ffmpeg.exe


>> youtube-dl load_time= 3.7072575092315674
>> download(): done downloading
>> download(): done downloading
>> check_for_update() --> App. is up-to-date, server version= 2020.1.30
>> looking for video streams ... Please wait
>> [youtube] QAUzWtLMnU0: Downloading webpage
>> [youtube] QAUzWtLMnU0: Downloading video info webpage
>> Dash video detected
>> check ffmpeg availability?
>> ffmpeg checked ok!
>> config.ffmpeg_actual_path =  C:\FFmpeg\bin\ffmpeg.exe


>> thread_manager 1: quitting
>> running command: C:\FFmpeg\bin\ffmpeg.exe

 -i C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4 -i C:\Users\Lenovo\Downloads\audio_for_Full_HD_Test_1080p.mp4 -c copy C:\Users\Lenovo\Downloads\Full_HD_Test_1080p.mp4
>> cmd: 'C : \ F F m p e g \ b i n \ f f m p e g . e x e 
 
   - i   C : \ U s e r s \ L e n o v o \ D o w n l o a d s \ _ t e m p _ F u l l _ H D _ T e s t _ 1 0 8 0 p . m p 4   - i   C : \ U s e r s \ L e n o v o \ D o w n l o a d s \ a u d i o _ f o r _ F u l l _ H D _ T e s t _ 1 0 8 0 p . m p 4   - c   c o p y   C : \ U s e r s \ L e n o v o \ D o w n l o a d s \ F u l l _ H D _ T e s t _ 1 0 8 0 p . m p 4' - output: 'ffmpeg version git-2019-12-15-9fe0790 Copyright (c) 2000-2019 the FFmpeg developers

  built with gcc 9.2.1 (GCC) 20191125

  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enab
>> deleted folder: C:\Users\Lenovo\Downloads\audio_for_Full_HD_Test_1080p.mp4_parts_
>> file_manager 1: quitting
>> brain 1: removed item from active downloads
>> brain 1: quitting

**Comment by pyIDM** [comment]
> Hi, replaced FFmpeg, and tried 480p, still the same unfortunately:

this is weird, I just tested the application on windows 10 64bit and it works, also tested on windows8 32bit, and Manjaro arch Linux with no problems

anyhow, i will make another test version including different methods and will let you know once ready

**Comment by vdgrty** [comment]
If it helps, I also get an error when trying to download 1080p .mp4 using Youtube-DL-GUI - ( https://mrs0m30n3.github.io/youtube-dl-gui/ )

**Comment by pyIDM** [comment]
> If it helps, I also get an error when trying to download 1080p .mp4 using Youtube-DL-GUI - ( https://mrs0m30n3.github.io/youtube-dl-gui/ )

well, maybe something in your windows installation, 

but before we hit the wall, this is a new test version, hope it works
https://github.com/pyIDM/pyIDM/releases/download/extra/pyidm_test2.zip

**Comment by vdgrty** [comment]
Hm, strange. I don't get an error, but it stalls on 100% and the log goes on forever:

C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_\53477376-54525951
worker 2 completed C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_\51380224-52428799
worker 5 completed C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_\59768832-60817407
start worker 1 seg 46 range: 48234496-49283071 SL= 0
worker 3 completed C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_\50331648-51380223
worker 0 completed C:\Users\Lenovo\Downloads\_temp_Full_HD_Testart worker 1 seg 38 range: 39845888-40894463 SL= 0
worker 2 completed C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_\47185920-48234495
worker 3 completed C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_\46137344-47185919
start worker 0 seg 37 range: 38797312-39845887 SL= 0
start worker 2 seg 36 range: 37748736-38797311 SL= 0
start worker 3 seg 35 range: 36700160-37748735 SL= 0
start worker 8 seg 34 range: 35651584-36700159 SL= 0
worker 1 completed C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_\39845888-40894463
worker 0 completed C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_\38797312-39845887
worker 5 completed C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_\42991616-44040191
worker 7 completed C:\Users\Lenovo\Downloads\_temp_Full_HD_Test_1080p.mp4_parts_\44040192-45088767
start worker 1 seg 33 range: 34603008-35651583 SL= 0


-It just keeps going, this is just a snippet.

**Comment by pyIDM** [comment]
just cancel, and try to download the link again but change download folder

**Comment by vdgrty** [comment]
Same problem. It definitely looks like there's something wrong on my end.

**Comment by pyIDM** [comment]
This is a different one, just a moment, i will upload another test version

**Comment by pyIDM** [comment]
here it is 
https://github.com/pyIDM/pyIDM/releases/download/extra/pyidm_test3.zip

**Comment by vdgrty** [comment]
This one gets stuck at 99%

**Comment by pyIDM** [comment]
@vdgrty 
i just made a stable release at https://github.com/pyIDM/pyIDM/releases/latest
please check and see if your problem got fixed
