### ISSUE TITLE
FIX: Getting an error when clicking on an empty table on the downloads tab. Possible FIx. 

### ISSUE THREAD

**Issue by shin-illua** [pyIDM/pyIDM#37]
I was clicking on the Table unders the `Downloads` Tab and this error is raised in the console: 
![image](https://user-images.githubusercontent.com/44135157/73999517-ee02a580-499f-11ea-83bc-b23c7b1e0c49.png)

Possible fix would be (Updated line 394): 
![image](https://user-images.githubusercontent.com/44135157/73999603-3d48d600-49a0-11ea-9922-8d642d70e1f0.png)

Could have done a pull request but I think I should consult here first.

**Comment by pyIDM** [comment]
@shin-illua 
Nice catch, please make a pull request to merge this fix
