### ISSUE TITLE
Duble click on emptied download list opens last item selected before "delete all".

### ISSUE THREAD

**Issue by 7aman** [pyIDM/pyIDM#40]
Hi.

OS: Windows10 64 bit
cloned and run manually from source code.

I downloaded one file and then deleted from list. When I double click on empty table it will open this deleted file.
I think the "self.selected_d" variable must be reset after "delete" and "delete all'.

**Comment by pyIDM** [comment]
Fixed the problem, commit 2364dc005a80c03c7e0db69f5beb6710fbb2e81e
now selected_d will be None if no rows selected
thanks for reporting
