### ISSUE TITLE
Selected theme is saved after a successful exit but is not applied on the next run.

### ISSUE THREAD

**Issue by 7aman** [pyIDM/pyIDM#41]
Hi.

OS: Windows10 64bis
Cloned and run manually from source.
Python 3.7.4

In setting tab, selecting a theme reloads the gui correctly. If you close the app, on the next run it has default theme and in setting tab under select drop-down, it shows previous selected theme.

![theme](https://user-images.githubusercontent.com/33965922/74510868-e4d28500-4f19-11ea-8377-983b5f362302.png)

**Comment by pyIDM** [comment]
Thanks for pointing this out, i moved ChangeLookAndFeel() to MainWindow.setup() method instead of top of gui module

fixed commit 5ae27bb7475e02390b444d6295e8bdf6a0aad3dc

**Comment by 7aman** [comment]
I checked "setting.cfg" and noticed these items are intended to be saved for next runs. But same as theme they are not applied.
- monitor
- max_concurrent_downloads

Also "ffmpeg_installation_folder" value is incorrect. It is pointing to ".pyIDM" folder.

And it would be nice if all of items in setting tab could be saved and applied for next run.

**Comment by pyIDM** [comment]
@7aman 
yes I can see there is some setting values is not saved or loaded correctly, will work on this, also will check for ffmpeg_installation_folder
thanks for reporting :+1:

**Comment by pyIDM** [comment]
@7aman 
- fixed all setting parameters can be stored and reloaded properly.
commit e063634
