### ISSUE TITLE
Youtube playlists dowload problem - All downloaded files have same content.

### ISSUE THREAD

**Issue by Alice999999** [pyIDM/pyIDM#46]
Hi Mahmoud,

Many thanks for your great open source program pyIDM.
I’m using it since yesterday and I love it !!! 
Downloading videos files from Youtube is running perfectly excepted when downloading playlists.

When I download a playlist everything looks Ok; pyIDM download and create all the files of the playlist with their respective names, but when I open the video created files, all have exactly the same content .... the content of the last file of the playlist downloaded ??? 

I’ve tried with many playlists and the results are always the same.

I’m using version 2020.2.21 for pyIDM and version 2020.02.16 for youtube-dl.

Am I using pyIDM not correctly?
Have you an idea about this problem?

Thanks for your answer.
Regards.

Alice

**Comment by pyIDM** [comment]
Thanks for your feedback
I tested playlist option and it has a bug, I will let you know as soon as i fix it.

**Comment by pyIDM** [comment]
@Alice999999 
Just Fixed the problem, please check latest release and see if it works for you

if you run on windows, download windows portable at: https://github.com/pyIDM/pyIDM/releases/download/2020.2.22/pyIDM_2020.2.22.zip

or if you use pypi, you can update from:
`pip install pyidm --upgrade`

**Comment by Alice999999** [comment]
Many thanks for your reactivity.
pyIDM is just working perfectly now.

Alice

**Comment by pyIDM** [comment]
Great!
