### ISSUE TITLE
Merge Error

### ISSUE THREAD

**Issue by smaragdus** [pyIDM/pyIDM#47]
I tried to download a couple of YouTube videos but I couldn't complete the downloads as I always got merge error, screens:

**error message:**

![pyIDM 2020 2 22 - 2020-02-28_045710 - error - 001](https://user-images.githubusercontent.com/9025757/75506943-308c3080-59e8-11ea-80ac-fed1fb3e13b1.png)

**download window:**

![pyIDM 2020 2 22 - 2020-02-28_045710 - error - 002](https://user-images.githubusercontent.com/9025757/75506954-44d02d80-59e8-11ea-8b02-3838bbdab051.png)

I am using [pyIDM](https://github.com/pyIDM/pyIDM) version [2020.2.22](https://github.com/pyIDM/pyIDM/releases/tag/2020.2.22) on Windows 8 x64.

**Comment by pyIDM** [comment]
Would you please try to to download again and after the error save the log and attach it here

![7D0770E4-3B82-4434-9393-E2D5A3EBFB0B](https://user-images.githubusercontent.com/58998813/75526429-6fd37500-5a1a-11ea-9b77-bbf525233223.gif)

**Comment by smaragdus** [comment]
@pyIDM 

I did another attempt to download a video from YouTube and again I encountered the same merge error, screens:

**error message:**

![pyIDM 2020 2 22 - 2020-02-29 - error - 001](https://user-images.githubusercontent.com/9025757/75594524-ae584680-5a91-11ea-814d-66f6adec6e80.png)

**download window:**

![pyIDM 2020 2 22 - 2020-02-29 - error - 007](https://user-images.githubusercontent.com/9025757/75594569-cfb93280-5a91-11ea-80d2-56d599f812b5.png)

**main window:**

![pyIDM 2020 2 22 - 2020-02-29 - error - 009](https://user-images.githubusercontent.com/9025757/75594592-e2336c00-5a91-11ea-9f4c-c2a5394568f5.png)

Interestingly the program failed to save log file showing the following error:

`>> failed to save log file:  'charmap' codec can't encode character '\xe1' in position 1194: character maps to <undefined>`

So I copied the text manually and saved it as `log.txt`, I will attach it below:

[log.txt](https://github.com/pyIDM/pyIDM/files/4269572/log.txt)

I hope this will help for revealing what is causing the merging problem on my system.

**Comment by pyIDM** [comment]
That's very helpful making the log.txt
from the log, i can see the weird line: `"C:\\Program Files\\VDownloader\\ffmpeg.exe\r\n"` 
the path to ffmpeg.exe has `\r\n`  which needs to be fixed

for the time being, we need to make sure this is the actual problem, so can you please copy `ffmpeg.exe` file from  `"C:\Program Files\VDownloader\ffmpeg.exe"` and paste it in PyIDM folder in `"C:\Temporary\Tests\pyIDM\pyIDM 2020.2.22\pyIDM"` 

and then try again and see if it works or we still have another problem

**Comment by smaragdus** [comment]
@pyIDM 

Thank you for the very quick and helpful response!

I have many instances of [FFmpeg](https://ffmpeg.zeranoe.com/builds/) and I have no idea why [pyIDM](https://github.com/pyIDM/pyIDM) used the one from [VDownloader](https://vdownloader.com/) folder. Anyway, I put a more recent version of **FFmpeg** and this time there was no merge error- the video was downloaded successfully.

I should say that I did not know that I should put **ffmpeg.exe** in **pyIDM** folder, after I put it there **pyIDM** works just fine.

I also have many instances of [youtube-dl](https://github.com/ytdl-org/youtube-dl) and i do not know which one **pyIDM** is using. Would it be better if I also put **youtube-dl.exe** in **pyIDM** folder?

As the problem is resolved I will close this issue.

Thanks for your help.

**Comment by pyIDM** [comment]
> I have many instances of FFmpeg and I have no idea why pyIDM used the one from VDownloader folder

That's because "VDownloader " added its location to your windows path
PyIDM will look for ffmpeg in its folder and if it doesn't exist it will look for the one exist in the system, which happened to be in VDownloader  folder,
it suppose to work without having to put it in PyIDM folder, I will fix this bug anyhow.

> I also have many instances of youtube-dl and i do not know which one pyIDM is using. Would it be better if I also put youtube-dl.exe in pyIDM folder?

No need, since PyIDM is using embedded library of youtube-dl

**Comment by smaragdus** [comment]
@pyIDM 

Thanks for the detailed explanation. Have a nice week-end.

**Comment by pyIDM** [comment]
Done
