### ISSUE TITLE
Maybe get some ideas from this project?

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#50]
https://github.com/axcore/tartube

I saw a post on Reddit and took a look.  I like thumbnails.  Could be difficult to do unless you're making your own tables from scratch which would give you immensely more options than using the standard Table Element.

Maybe there's a feature or two you can lift from them.

**Comment by pyIDM** [comment]
Well, Tkineter does allow using images / thumbnail in the first column of the table, 
2 weeks ago i was planning to open enhancement issue on PySimpleGUI but I got busy working on the application performance, a lot has been done, but its the time to give more work to GUI design

**Comment by PySimpleGUI** [comment]
Right, you will not be able to have a column in a table that are images.  Tkinter doesn't support it so opening an enhancement won't help. I'm good, but I can't work miracles.  Even if it did, the mess of trying to create a SIMPLE API that would provide access to mixed media tables would be more than currently possible given my time constraints.

What I was suggesting is that you ditch Tables entirely and make your own custom tables so that you can put anything and everything in them.  A table is nothing more that a row of elements.  In the Table Element, the end result resembles a bunch of text elements that you cannot select nor change using a mouse.

I would approach it as a layout you build a row at a time.  I've done this several times on projects where I needed a multitude of element types to be the same for several rows.  I could mock something up if I'm not descriptive enough. Just tell me what you would like to see on  row in a table.

When I look at the window of the other project and it's "Table", I don't see a table at all.

![image](https://user-images.githubusercontent.com/46163555/75780241-f9d85200-5d28-11ea-955e-dffbf222df9c.png)

I see a series of Column elements with many other Elements embedded inside.  Right?

In that image's "table", there are text widgets. There are clickable text widgets.  There are 2 images, one on the left.  The other being the checkbox in the upper right corner.

Let's look at the checkbox in the upper right corner as an example of a custom Element.  The way to code that up is to use an Image element with events enabled. When someone clicks it, you change the image that's shown from unchecked to checked and vice versa.  

Making your own table will open up all kinds of things that the GUI frameworks and PySimpleGUI itself stop you from being able to do.  You're limited by the features provided by Table elements in each PySimpleGUI port.


-------------------------


ALL this said, you've got a hot product at the moment.  I don't think you have to go overboard on the UI for it to continue to be good and grow your user base.  It's more a matter of making sure it works well and then marketing the heck outa it.   

You've clearly struck a nerve and found a need.  Projects don't just popup with 78 stars on them without something special in the project that speaks to users.

![image](https://user-images.githubusercontent.com/46163555/75780832-1759eb80-5d2a-11ea-97ff-3a02f39f7ddf.png)

**Comment by pyIDM** [comment]
> Making your own table will open up all kinds of things that the GUI frameworks and PySimpleGUI itself stop you from being able to do. You're limited by the features provided by Table elements in each PySimpleGUI port.

I agree, it will open up a lot of options

> Right, you will not be able to have a column in a table that are images. Tkinter doesn't support it 

No wait, I found a tkinter code long time ago that can do it, plus this option is a straight forward to apply in wxpython "I did it before", not sure about pyqt,
anyhow, i will open an enhancement issue and include the code source and screenshot, please note that i have zero knowledge in  how to use tkinter, so it is upto you if you want to implement this feature or not

**Comment by PySimpleGUI** [comment]
Trying to give you a hint in the direction I'm going and what I'm capable of doing.  Using Table widgets as containers is not going to be a winning strategy regardless of examples you can dig up.

**Comment by pyIDM** [comment]
I think you are right, table is very limited, even if we add thumbnail to first cell, still i need to add progress bar to another cell too, i did that before in wxpython, but i think it is not easy in tkinter,

I should give it a try and use another route with costume column design, and see how it goes

**Comment by PySimpleGUI** [comment]
Keep in mind HOW PySimpleGUI is fundamentally different than the other frameworks.  In tkinter, Qt, WxPython and others, you cannot create a GUI using a list comprehension.  It's TRIVIAL (and this you know) to create a "row" in your layout.  What it as table?  It's a bunch of rows.  So, you could say that PySimpleGUI was MADE to create tables.

There was also an addition made last year so that you can "extend" layouts.  This means being able to append new rows to your "table" as you need them.  You can't do that with a table element.

The first thing I think about with new features like this one is "how is thing going to be presented to the programming using the same simple PySimpleGUI structure?"  The answer I come up with for Tables with other things embedded in them is that it's ugly.  It will likely require "helper classes" like the Tree element has where you must build this other thing first and then use that to create you table.  It's a multi-stepped, multi-class, not elegant and easy process.  This is why you see the pushback from me over and over about it.  

In many ways, it does not matter that the underlying GUIs are capable of doing it.  What matter is what is presented to the PySimpleGUI programmer.  Knowing "you can do it "using tkinter or anything else means little in these features.

I hope this makes sense.  It's not that I don't want to grow PySimpleGUI and add features.  I do that almost every day.  I don't want to complex up things needlessly.  

Just because there is a Table  element doesn't mean it must be used any time you want to make something that displays rows of data.  If you need to be able to adjust the column sizes using a mouse and the data is all strings, then sure, a Table element is great.  But if you want an image, a progress bar, data input, etc, then a Table simply cannot do that.  

The way to go about making something like the example I posted is to break things down into rows, in a recursive manner.  At the top level, I see each row as a column.  In each column I see an image with a column next to it.

![image](https://user-images.githubusercontent.com/46163555/75906840-4f8a2880-5e15-11ea-90e4-60549896e54f.png)


The beauty and the power of PySimpleGUI is that elements are single objects and that they can be assembled trivially.  It's like building molecules from atoms.  There are fundamental building blocks that you build using a combination of elements and containers.  With that combination you can build just about anything.  Think "tinkertoys" or "erector set".  They don't upgrade their parts very often yet countless cool things have been built with them.

**Comment by PySimpleGUI** [comment]
What I'm trying to describe is that I have defined as "user created elements" or "compound elements".  These are functions that you place into a layout as if they are elements when they are in fact functions that _**return elements**_.  

In this way you can make a layout looks like a bunch of rows of your download table entries:

```python
def DownloadEntry(p1, p2, p3, p4):
    return sg.Col([[sg.T(p1), sg.T(p2), sg.T(p3), sg.T(p4)]])

layout = [[ DownloadEntry('a', 'b', 'c', 'd') ],
          [ DownloadEntry(1,2,3,4) ],
          [ DownloadEntry(5,6,7,8) ]]

sg.Window('Table but not a Table', layout).read()
```

![image](https://user-images.githubusercontent.com/46163555/75907912-2e2a3c00-5e17-11ea-85d4-6d97961a3ad2.png)
