### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [pyIDM/pyIDM#51]
# Preamble #

I have plenty of video downloaders (several commercial ones and many free ones) and most of them work fine. Yet [pyIDM](https://github.com/pyIDM/pyIDM) caught my attention because of its pleasant and colourful GUI and the abundance of themes (140 is really an impressive number- I have not already tested all of them despite my enthusiasm)- I am totally bored of the bland and dull 'modern' trend of monochrome interfaces. I also like the fact that **pyIDM** does not require .NET and Electron (for me the latter is an absolute monstrosity and has no place on desktop).

On [Releases](https://github.com/ytdl-org/youtube-dl/releases) page it is stated that **pyIDM** is portable but this is not true as truly portable programs do not save data and settings outside their program folders while **pyIDM** saves its configuration files (<code>downloads.cfg</code> and <code>setting.cfg</code>) in AppData:

<code>C:\Users\User\AppData\Roaming\.pyIDM</code>

I prefer portable programs (or programs which offer option to run in portable mode).

# Request #

I would like to suggest an option data and settings to be saved in program folder (next to the executable- **pyIDM.exe**) in stead of in AppData which will mean that **pyIDM** is really portable. Portability can be implemented in a variety of ways, below I will provide several examples  which may be appropriate to to be implemented in **pyIDM**:

1. **command-line argument** - if the executable (**pyIDM.exe**) is started with a specific parameter, for example <code>pyIDM.exe -portable</code>, data and settings files are saved in program folder;
2. **portable flag** - specific file in program folder (for example <code>portable</code> without extension or <code>portable.txt</code>) triggers portable mode, when **pyIDM** starts it checks program folder for such file and if it is there data and settings files are saved in program folder;
3. **configuration files** - when **pyIDM** starts it checks program folder for configuration files (<code>downloads.cfg</code> and <code>setting.cfg</code>) and if they are in program folder the program uses them;
4. **special sub-folder** - when **pyIDM** starts it checks program folder for a special sub-folder (for example <code>Data</code> or <code>Settings</code> or <code>.pyIDM</code>) and if it is there the program saves configuration files in this sub-folder;
5. **option in settings** - new check box- <code>Portable mode</code>, which, if selected, forces the program to save configuration files in program folder;

There are other ways of triggering portable mode but I suppose the ones I suggested above are appropriate for **pyIDM**. I prefer methods **2**, **3**, **4** and **5** (as **1** is not that handy to use) but any of them would do if **pyIDM** can save configuration files in program folder in stead of in AppData.

# Advantage #

In my opinion portable programs (or programs running in portable mode) have several advantages:

- **portability** - portable programs can be easily transferred from machine to machine with all their data and settings;
- **backup** - portable programs are easy to back up to external drives or to cloud services (in case one needs to re-install OS);
- **testing** - portable programs facilitate testing- one can test different versions (stable, alpha, beta) with different settings or even use the same version with different setting;

I will be glad if you consider implementing portable mode for **pyIDM** in future releases. I believe that if **pyIDM** can run in portable mode this would add more flexibility to the already quite promising program.

**Comment by pyIDM** [comment]
> Yet pyIDM caught my attention because of its pleasant and colourful GUI and the abundance of themes (140 is really an impressive numbe

Thanks a lot for your nice words, these 140 themes are one of strength points of the GUI framework i used, thanks to @PySimpleGUI for this effort

PORTABLE:
I totally agree with you, I don't like applications to store hidden data in my computer,
I believe I kept setting in separate folder for 2 reasons:
- first, if you want to use updated version of PyIDM you will still have your setting and download info available, I mean you don't have to copy both files "setting.cfg and downloads.cfg" to the new PyIDM folder.
- second reason because PyIDM was an msi installer before it becomes a portable version, which made it hard to store setting in local PyIDM folder "at Program Files" which needed admin privillage

Now since you raise this issue and PyIDM becomes portable only, it is reasonable move to put all setting files in same folder with PyIDM files as a default action and give user an option to store setting in different folder if he likes to do so.

so, I will implement this action in the next release.

Thanks for your valuable notes.

**Comment by smaragdus** [comment]
@pyIDM 

Thanks for your very quick response! I am glad that you work on pyIDM with dedication and passion!

Actually I do not mind if the default location for configuration files is AppData if there is a ways to make pyIDM save configuration files in program folder. Perhaps you may choose to keep AppData as default location because many users have no idea of privileges, admin rights and protected folders and just copy folders to program files which may cause issues.

By the way [pyIDM](https://github.com/pyIDM/pyIDM) version [2020.3.3](https://github.com/pyIDM/pyIDM/releases/tag/2020.3.3) comes packaged with [youtube-dl](https://github.com/ytdl-org/youtube-dl) version [2020.02.16](https://github.com/ytdl-org/youtube-dl/releases/tag/2020.02.16) while the latest version is [2020.03.01](https://github.com/ytdl-org/youtube-dl/releases/tag/2020.03.01).

In the [ChangeLog](https://github.com/pyIDM/pyIDM/blob/master/ChangeLog.txt) I read that:

> **2020.3.2:**
>  - Ability to use youtube-dl native downloader as an alternative option.

Is there any advantage to use youtube-dl native downloader?

I may also open some very cosmetic and insignificant GUI issues.

Thank you for your excellent work!

**Comment by pyIDM** [comment]
> Is there any advantage to use youtube-dl native downloader?

I just put this option in case PyIDM downloader fails to download some links, example: older stream formats like flv and also life streams are not supported yet in PyIDM

> By the way pyIDM version 2020.3.3 comes packaged with youtube-dl version 2020.02.16 while the latest version is 2020.03.01.

oh! I forgot to include the latest, anyhow this youtube-dl.exe only for native youtube downloader, but the info extractor is embedded youtube-dl library and it is uptodate 

![image](https://user-images.githubusercontent.com/58998813/75839137-b76a5000-5dd0-11ea-9ce7-9aeaad4a6f59.png)

**Comment by pyIDM** [comment]
Done.. new release 2020.3.13

**Comment by smaragdus** [comment]
Thanks for natural sorting order of themes, excellent!

**Comment by smaragdus** [comment]
@pyIDM 

Thank you for implementing portable mode!

Choosing 'Local' for 'Setting Folder' really makes pyIDM portable, great!

Two things:

- My mother tongue is not English but yet I think that `Settings Folder` looks and sounds better than `Setting Folder`.
- When 'Local' is selected for 'Setting Folder' configuration and data files (`setting.cfg`, `downloads.cfg` and `log.txt`) are really saved in program folder but the folder in AppData (`.PyIDM`)n is alwats recreated any time pyIDM starts. I think that if 'Local' is select for 'Setting Folder' the folder in AppData should not be recreated.

I appreciate your work very much!

Regards

**Comment by pyIDM** [comment]
> Settings Folder looks and sounds better than Setting Folder

yes I agree :)

> the folder in AppData (.PyIDM)n is alwats recreated any time pyIDM starts.

well, thanks for the note, I forgot about it, and this issue will be fixed in next release
