### ISSUE TITLE
Themes Sorting

### ISSUE THREAD

**Issue by smaragdus** [pyIDM/pyIDM#52]
In my opinion themes are not sorted in the right way, examples:

**desirable sorting:**

1. DarkBlue1
2. DarkBlue2
3. DarkBlue3
4. ..
5. DarkBlue9
6. DarkBlue10
7. DarkBlue11

**current sorting:**

1. DarkBlue1,
2. DarkBlue10
3. DarkBlue11
4. ..
5. DarkBlue2
6. DarkBlue3
7. DarkBlue4

**screen:**

![pyIDM 2020 03 03 - 2020-03-04 - error - 003](https://user-images.githubusercontent.com/9025757/75838948-15e2fe80-5dd0-11ea-83c5-3e9d16904294.png)

**desirable sorting:**

1. LightGreen1
2. LightGreen2
3. LightGreen3
4. ..
5. LightGreen9
6. LightGreen10
7. LightGreen11

**current sorting:**

1. LightGreen1,
2. LightGreen10
3. LightGreen11
4. ..
5. LightGreen2
6. LightGreen3
7. LightGreen4

**screen:**

![pyIDM 2020 03 03 - 2020-03-04 - error - 004](https://user-images.githubusercontent.com/9025757/75839287-2d6eb700-5dd1-11ea-9f3b-d10db6197158.png)

I am not a programmer and I do not know whether this is fixable and whether this is a Python limitation. This is not of great importance, it just happened that I noticed it. If changing the sorting pattern is not doable please feel free to close this issue as it is really very insignificant.

**Comment by PySimpleGUI** [comment]
Sorting in a strict numerical manner is not how strings sort in any language that I'm aware of.  They sort exactly like is shown.   If you want a true sort by numerical rank then zero padding has to be used.

**Comment by pyIDM** [comment]
Yes, I agree natural sorting is not an easy task, there is tons of possibilities when it comes to sorting in a human way
for example if i have a list of values like: `["blue car", "white bus", "red car", "green bus"]`

any programing language built in sorting algorithm will give us this ugly thing:
`["blue car", "green bus", "red car", "white bus" ]`

but anyone will disagree with this sorting and a logic thing is to keep cars together and buses together: `["blue car", "red car", "green bus", "white bus" ]`

however in some tasks we can make our custom sorting function that can do the job,
for themes sorting to work it has to have zero padding i.e "DarkBlue2" should be "DarkBlue02", or to use a custom sorting

i tried this simple code using regex and it does work as expected,
```
def natural_sort(my_list):
    convert = lambda text: int(text) if text.isdigit() else text
    alphanum_key = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
    return sorted(my_list, key=alphanum_key)

# in gui.py will implement this function
config.all_themes = natural_sort(sg.ListOfLookAndFeelValues())
```
This how it looks like
I believe I will add it to next release of PyIDM 
![image](https://user-images.githubusercontent.com/58998813/75937535-d975d800-5e8d-11ea-98a0-5230a004f3d3.png)

**Comment by smaragdus** [comment]
@PySimpleGUI 
Thanks for the explanation.

@pyIDM 
Thanks for working on this tiny issue, it definitely looks better than if you had used 01, 02, 03, etc.

**Comment by pyIDM** [comment]
done in new release 2020.3.13

**Comment by smaragdus** [comment]
Thanks for natural sorting order of themes, excellent!
