### ISSUE TITLE
Using the StatusBar element!

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#54]
I saw a screenshot in another issue.  When I looked at the bottom it looks like a "status bar".  It reminded me that PySimpleGUI has a `StatusBar` element.  I was thinking about that just this week.

So I did a quick search of this GitHub and I'll be damned, you're USING an actual `StatusBar` element.  I'll have to keep that in mind and not screw it up in the future 😉 Looking at all of GitHub there's only 4 projects that use it.

![image](https://user-images.githubusercontent.com/46163555/75930256-2fbc2a00-5e40-11ea-8779-5474707870d6.png)

Seeing your code reminds me that I need to change that element so that it behaves like the `Text` element and others that take a string parameter.  The way they work now is that a blank string is the default so that you don't need to specify any string at all.  I'll go through them all and fix them up.  It's been nice not having to include them.

So, remember, you can use this `Text` element without any string specified as a valid element:

```python
sg.Text(size=(10,1), key='-OUTPUT-')
```

**Comment by pyIDM** [comment]
> sg.Text(size=(10,1), key='-OUTPUT-')

This is neat and much cleaner :+1:  and would be nice if applied to StatusBar too
