### ISSUE TITLE
Screenshot with many windows disappeared

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#55]
Where did the super-impressive screenshot go that shows a ton of open windows running simultaneously go?  It really demonstrated that you've developed a multi-threaded and thus likely highly efficient program.

**Comment by pyIDM** [comment]
Oh! I removed it from README because I thought it doesn't fit well maybe it is too noisy, and should have less windows, I am not sure

If you think it is ok as it is, i will put it back

![here](https://user-images.githubusercontent.com/37757246/71418548-a2a46a00-2673-11ea-8101-c95d29b6a0e4.png)

**Comment by pyIDM** [comment]
done adding screenshot to readme

**Comment by PySimpleGUI** [comment]
Oh crap, I didn't answer you.

Of course it's a busy screen, but that's the beauty.  Even with all that activity, with all those windows going at the some time, you didn't crash or slow down to a halt.  To me it shows depth and complexity should the user wish to go there.  Most people won't need to or want to, but you could if you wanted.

It demonstrates that you've mastered multi-tasking in this program.   ANY program that's able to manage that many windows with it crippling the system is a well-written program.  It's not at ALL easy to do and is one of the reasons I was so stunned when I saw it.  It speaks volumes to anyone that knows anything about systems.  It more than caught my attention.

And this screen shot seems to quiet any challengers that PySimpleGUI is only good for simple little windows programs.  In ONE image I can dispel that myth and it's coming not from something I made, but from a real user.

I'm still impressed every single time I see it.  I would have never dreamed that this package would be this capable a a year and a half ago.    It was 2 years ago this month that I started writing PySimpleGUI.
