### ISSUE TITLE
[ Marketing ] List yourself on LibHunt

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#56]
This is a really really good thing to get listed on and you can do it yourself.

Every one of these marketing activities adds up.  Some take time to develop, others literally have an impact overnight.

Libhunt is a good thing to be listed on.

Another thing to do is get yourself listed as an "interesting project" in newsletters.

Currated newsletters are constantly on the search for new hot things.  You're new and hot.

I just received in my email a copy of "Awesome Python" newsletter and in it I saw this under the "popular packages":

![image](https://user-images.githubusercontent.com/46163555/76045474-2eb3f700-5f2b-11ea-89c5-51be49c83203.png)

I followed the link and it took me to libhunt:

https://python.libhunt.com/flexget-alternatives

It seems like there are a few "downloaders" out there.  I don't know if these are even the same kind of thing as what your code does, but figured it can't hurt to share a few of these resources and site that I found useful in getting attention.  You've got a great project that users are really enjoying.    Keep telling people about it!

**Comment by pyIDM** [comment]
Well, thanks for this, 
i just added PyIDM to the list, here it is the link
https://python.libhunt.com/pyidm-alternatives

and here
https://python.libhunt.com/categories/201-downloader
