### ISSUE TITLE
How to use Proxy?

### ISSUE THREAD

**Issue by mmshasan** [pyIDM/pyIDM#57]
Hello,
I've tried **username:password@proxyserveraddress** in Proxy field in Settings but seems not working or I am missing the correct format. I want to use NordVPN http/https/shock5 whatever works better.

Thanks in advance.

BR,

**Comment by pyIDM** [comment]
Please try this and let me know if it works
http://username:password@proxyserveraddress:port

You also can try https but socks is not supported yet
and don’t forget port (example 8080) it should be supplied by ptoxy provider

**Comment by mmshasan** [comment]
Thanks for your response. It worked perfectly fine with YouTube. I've tried couple other sites where download are based on m3u8 where it was only able to fetch the header but failed to download. 

YouTube-DL command line work perfectly fine with proxy url and can download.

Hope in future release it'll work. You can add streamlink in pyIDM if possible. Thanks again.

**Comment by pyIDM** [comment]
> You can add streamlink in pyIDM if possible.

once you start download, you can go under downloads tab and right click the item you want then choose copy download url

![image](https://user-images.githubusercontent.com/58998813/76138383-0c67c980-6050-11ea-9f81-ed0763c2eeb3.png)

> I've tried couple other sites where download are based on m3u8 where it was only able to fetch the header but failed to download.

if possible to send the link to check why it failed, and if you can try to download again then send the log file in PyIDM folder

**Comment by mmshasan** [comment]
You can check on **tubitv.com** It's Free. This site has m3u8. Without proxy it can download but with proxy it can't

**Comment by pyIDM** [comment]
done fixing the problem in latest version 2020.3.13
now can download hls with proxy , also added support for socks proxies
commit https://github.com/pyIDM/pyIDM/commit/1d5e84575ccb20f09765dbd6f2baa52436298a54
