### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by yochananmarqos** [pyIDM/pyIDM#60]
I have `python-pillow` 6.2.1-1 installed on Manjaro GNOME, however PyIDM 2020.3.20 is not detecting it:

```
$ pyidm 
require pkgs:  ['PySimpleGUI', 'pyperclip', 'plyer', 'certifi', 'youtube_dl', 'pycurl', 'pillow']
missing pkgs:  ['pillow']
Missing dependencies, quit application
```

**Comment by pyIDM** [comment]
@yochananmarqos 
oh, I see, this is because "pillow" has 2 names
we use pillow with pip but the name actually installed is "PIL"
i will correct this issue and let you know

thanks for reporting

**Comment by pyIDM** [comment]
@yochananmarqos 
fixed this issue and release a new pypi release
if you use pypi, please install new version thru
`python -m pip install pyidm --upgrade --no-cache`

**Comment by yochananmarqos** [comment]
I'm using the `setup.py`, not `pip`.

I received this error running `python setup.py build`:

```
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    with open("requirements.txt", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by pyIDM** [comment]
can you please try this setup.py instead
replace it with old one

link: https://github.com/pyIDM/pyIDM/releases/download/extra/setup.py

**Comment by yochananmarqos** [comment]
That is identical to the `setup.py` in the PyPI archive.

**Comment by pyIDM** [comment]
> 
> 
> That is identical to the `setup.py` in the PyPI archive.

no it has these extra lines
```
# get current directory
path = os.path.realpath(os.path.abspath(__file__))
current_directory = os.path.dirname(path)
```
the issue you have is because setup.py can't locate requirements.txt, and this is because the current directory in your terminal is not set to pyIDM folder
with these lines added i think the problem will be fixed

**Comment by pyIDM** [comment]
also paths of the files is modified in new setup.py file

```
with open(f"{current_directory}/pyidm/version.py") as f:
    exec(f.read(), version) # then we can use it as: version['__version__']

# get long description from readme
with open(f"{current_directory}/README.md", "r") as fh:
    long_description = fh.read()

# get requirements
with open(f"{current_directory}/requirements.txt", "r") as fh:
    requirements = fh.readlines()


```

**Comment by pyIDM** [comment]
> 
> 
> That is identical to the `setup.py` in the PyPI archive.

oh wait!
i've got it now, you've got a copy from pypi not github clone
there is no requirements.txt file there
just as a temporary fix please download the requirement.txt file and put it in same directory with setup.py

https://github.com/pyIDM/pyIDM/blob/master/requirements.txt

until i fix this

**Comment by yochananmarqos** [comment]
Right, the 2020.3.22 release is only available on PyPI.

Using the `requirements.txt` above and the original `setup.py` or the `setup.py` linked above is the same result:

```
error in pyIDM setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'<!DOCTYP'": Expected W:(abcd...)
```

**Comment by pyIDM** [comment]
I think the contents of requirements.txt is wrong since it has html contents instead of text

please delete this file and download it again from this direct link
https://github.com/pyIDM/pyIDM/releases/download/extra/requirements.txt

**Comment by pyIDM** [comment]
the contents of requirements.txt should looks like below:

PySimpleGUI
pyperclip
plyer
certifi
youtube_dl
pycurl
pillow

**Comment by yochananmarqos** [comment]
I don't think the `requirements.txt` is the issue, it appears to be the `setup.py`. The `install_requires` section is all commented out:

```
    install_requires=requirements, #['PySimpleGUI', 'pyperclip', 'plyer', 'certifi', 'youtube_dl', 'pycurl'],
    # py_modules=[],
    # data_files=[(os.path.join(sys.prefix, 'Lib/site-packages/pyidm'),['requirements.txt'])],
    # package_data={
    #     # can include only files inside the package:
    #     "": ["*.txt"]
    # },
    # include_package_data=True,  # if plan to use MANIFEST.in
    entry_points={
    	# our executable "exe file on windows for example"
        'console_scripts': [
            'pyidm = pyidm.pyIDM:main',
```

**Comment by pyIDM** [comment]
can you post the contents of requirements.txt because from the error you posted it shows file started with '<!DOCTYP'

**Comment by pyIDM** [comment]
> I don't think the requirements.txt is the issue, it appears to be the setup.py. The install_requires section is all commented out:

i think this will be the permanent fix is to include the requirements inside setup.py

**Comment by yochananmarqos** [comment]
Oh, duh. `curl` was trying to download the `requirements.txt` as a webpage. I had to use https://raw.githubusercontent.com/pyIDM/pyIDM/master/requirements.txt. It's working now, thanks.

**Comment by pyIDM** [comment]
> It's working now, thanks.

glad it works for you, 

I will modify setup.py to work with or without requirements.txt with next pypi release

thanks for your feedback
