### ISSUE TITLE
Download button not centered

### ISSUE THREAD

**Issue by smaragdus** [pyIDM/pyIDM#62]
I have not used a screen ruler but I think that the download button is not centered, screen:

![pyIDM 2020 03 20 - 2020-03-25 - error - 002](https://user-images.githubusercontent.com/9025757/77493949-1c9fe700-6e4d-11ea-8956-74d23e851742.png)

I think that it should be moved a bit to the right in order to be exactly in the center of the main tab.

**Comment by pyIDM** [comment]
Thanks for spotting this glitch
I will adjust it with the next release

**Comment by pyIDM** [comment]
Done with new release 2020.3.31, I believe it is centered now
https://github.com/pyIDM/pyIDM/issues/13#issuecomment-607633667

**Comment by smaragdus** [comment]
@pyIDM 

Version [2020.3.31](https://github.com/pyIDM/pyIDM/releases/tag/2020.3.31) is a great update, thanks!

The GUI is hugely improved, I like the new icon buttons much than the old text buttons:

![PyIDM 2020 03 31 - 2020-04-02 - 014](https://user-images.githubusercontent.com/9025757/78237629-3e037180-74e4-11ea-8477-17736d6f19f1.png)

Actually I was thinking of suggesting that you replace the text buttons with icon buttons but I was afraid that I would be asking too much. And you did it, excellent!

I also like the new tabbed settings very much:

![PyIDM 2020 03 31 - 2020-04-02 - 003](https://user-images.githubusercontent.com/9025757/78237856-8c187500-74e4-11ea-9ff1-1343b292cc55.png)

Overall, the GUI is improved a lot!

I am closing this issue.

Best regards

**Comment by pyIDM** [comment]
@smaragdus 
Thanks 
I’m happy you like the new design
