### ISSUE TITLE
Video and audio streams

### ISSUE THREAD

**Issue by nero1st** [pyIDM/pyIDM#64]
Hi pyIDM dev and everyone.

I was wondering if it would be possible to add the ability to manually choose video and audio separately, if available, and after downloading be merged. That would be amazing.

Also thanks for this fantastic tool. 😁

**Comment by pyIDM** [comment]
@nero1st 
you can choose to download audio only from quality menu, 
however there is no current option to select video only stream "without audio", 

we can add option in settings to keep both video and audio files after merging, and you will end up with 3 files "audio file", "video file", and a normal "video with merged audio" file, and you still can disable this option in settings 
if this is what you want, will add it to this coming release

**Comment by nero1st** [comment]
My point is to be able to freely choose audio and video quality from the available options.

From what I've noticed, after choosing the video stream, pyIDM automatically determines what audio is best for it, not letting you choose. Or am I forgetting something?

**Comment by pyIDM** [comment]
> From what I've noticed, after choosing the video stream, pyIDM automatically determines what audio is the best for it, not letting you choose. Or did I miss something?

yes, this is correct, it will choose audio file with the same format, example "m4a audio" will be chosen with mp4 videos, and webm audio for webm video and so on, this way merging video with audio will be fast, otherwise it will take ffmpeg several minutes to merge different formats,

> My point is to be able to freely choose audio and video quality from the available options.


i understand your point now, will think of something to do this without disturbing the workflow of the application

**Comment by nero1st** [comment]
Sounds good, thank you! 😄

**Comment by pyIDM** [comment]
done with new release 2020.3.31

first you should enable "Manually select audio format for dash videos" option in settings :
![settings](https://user-images.githubusercontent.com/58998813/78213884-28765380-74b4-11ea-8f06-57c007f5e217.png)

then if there is a dash video, once you click download a window will show up to choose an audio format from a drop down menu

![audio](https://user-images.githubusercontent.com/58998813/78213994-6bd0c200-74b4-11ea-9ba9-144a006d6580.png)

**Comment by nero1st** [comment]
I just tested it and it's working like a charm! Thank you very much for implementing this. 😁 

If I can suggest something else, how do you feel about supporting authentication on pyIDM? Some sites need you to login in order for youtube-dl to be able to download the webpage, such as Crunchyroll for example. You could put an option in settings to this, if necessary.

So thanks for reading and for your support. 😉

**Comment by pyIDM** [comment]
> how do you feel about supporting authentication on pyIDM? 

No problem, will add support for it and hope login is enough because In some cases website needs to use cookies files,

**Comment by nero1st** [comment]
Yes, in some situations cookies are necessary to deal with reCaptcha. But in most cases only the login is enough. In any case, thank you for your attention when listening to my requests.

I'll keep an eye on the next releases to see how that goes! 😄

**Comment by pyIDM** [comment]
website authentication issue #65
done release version 2020.4.8
