### ISSUE TITLE
Alternative stream options

### ISSUE THREAD

**Issue by nero1st** [pyIDM/pyIDM#68]
Hi all.

So, as can be seen below for some sites youtube-dl provides many options that can be considered "redundant" in terms of resolution, compression methods, codecs, etc.
But there are cases where they can be differentiated by non-technical means, such as burnt-in subtitles.

See:
![Terminal](https://user-images.githubusercontent.com/42862510/78504517-32ae8100-7744-11ea-804a-5af09158ea50.png)
Redundant options, except for the difference in subtitle language.

However, it seems that pyIDM identifies this and only offers the "best" download options, for each of the available resolutions.

See:
![PyIDM](https://user-images.githubusercontent.com/42862510/78504518-3510db00-7744-11ea-8c67-2ed52825be01.png)

**Conclusion:**
I would like to suggest a category below the audio streams, for the other options that are not the "best", in case of "redundancy".

What do you think?

Thanks for reading! :)

**Comment by pyIDM** [comment]
@nero1st 
please send the link you used or any example link that contains hardsubs and will see how can this feature will be implemented in PyIDM

**Comment by nero1st** [comment]
It's just a crunchyroll link. [This](https://www.crunchyroll.com/the-world-is-still-beautiful/episode-1-the-sun-kingdom-652189) is what I used, but anyone who doesn't require a premium subscription will do. But I think you could always consider making redundant options available, not just in cases of hardsubs, if in fact IDM works by ignoring them. Maybe you can tell me better.

Best regards.

**Comment by pyIDM** [comment]
@nero1st 
Let's think together,
the fact is, all streams will be listed with 3 properties (type-quality-size) example (mp4-1080-50MB), and most of the time size is not available and will end up with something like (mp4-1080-...), so, if I added the redundant options it will have the same values, "however they are internally different"
imagine if you have 3 redundant options like this:
(mp4-1080-...)
(mp4-1080-...)
(mp4-1080-...)
as a user how can you tell the difference, 

my own suggestion:
I think if we need to add extra streams we need to add extra property, for example 
(mp4-1080-...-en_sub)

the final will be something like:
```
video streams:
    > (mp4-1080-...)
audio streams:
    > (mp3-128-...)
    > (m4a-128-...)
extra streams:
    > (mp4-1080-..._en_sub)
    > (mp4-1080-..._fr_sub)
```

what do you think?
can you suggest a different idea on how to list these redundant streams

**Comment by pyIDM** [comment]
@nero1st 
I found a better way
I will include all the redundant / extra streams and add a description for them in separate text widget
will submit a screenshot once finished

**Comment by nero1st** [comment]
Sounds pretty good to me. Adding some of the information provided by youtube-dl in the format code field will be good to guide you on what is in that stream.

I think your suggestion is based on that? I like it.

If you can implement this it would be so nice. 😄

**Comment by nero1st** [comment]
> I found a better way
I will include all the redundant / extra streams and add a description for them in separate text widget
will submit a screenshot once finished

@pyIDM 
Wow sounds good. Can't wait to see that

**Comment by pyIDM** [comment]
This is a screenshot of proposed extra links, with "format code" shown on different widget

![Capture3](https://user-images.githubusercontent.com/58998813/78615390-a8fcd180-7871-11ea-8b94-e533795efe3a.png)

**Comment by nero1st** [comment]
Awesome! But is there any way to highlight the text so it looks a little more intuitive?
No problem if not, but I think it would be more evident that it refers to a description of the "extra flow" when you hover the mouse over it.

What do you think?

**Comment by pyIDM** [comment]
> I think it would be more evident that it refers to a description of the "extra streams" when you hover the mouse over it.

this would be great if it can be done, i am not sure if i can set a tooltip for every item in a combo box, anyhow will check, but I think as a functionality it does work, and will add more enhancement later on

**Comment by nero1st** [comment]
You're right. It's great for now, thanks.

**Comment by pyIDM** [comment]
done release version 2020.4.8

**Comment by nero1st** [comment]
Good start, but it doesn't seem to work as expected...

When you place the desired link and youtube-dl downloads the web page, pyIDM does not return all "alternative" streams. Apparently, it selects some randomly and delivers them to you.

In this case below, he provides me with five extra streams only, one per quality. However, they are all with hardsubs in French (frFR) and in Spanish (esLA/esES):
![PyIDM_1](https://user-images.githubusercontent.com/42862510/78991645-c77ff880-7b0f-11ea-8dca-edb08b14b956.png)
Also, all "standard" ('video strems') streams alternate between these languages.

So, as a workaround, perhaps you could put an option to enter the format code manually. Or maybe even a way to do this whole process by command line (inside pyIDM), and in the end, let it handle the download and merge part.

What do you think? 😃 

Regards.

**Comment by pyIDM** [comment]
@nero1st 
I think I know why there is missing streams, the extra streams names are stored in a dictionary with a unique keys, that's why there is no repeated entries. 
will work on a fix for it soon :)

**Comment by nero1st** [comment]
Nice! Thanks

**Comment by pyIDM** [comment]
@nero1st 
fixed, all streams now included with format id in the list
new release 2020.4.17

![format_id](https://user-images.githubusercontent.com/58998813/79640790-c6943a00-8193-11ea-8937-38e3883b381d.png)

**Comment by nero1st** [comment]
I can confirm. Everything is running smoothly now! 😄 
Thank you a lot for the improvements. Be sure that your efforts are appreciated. 
So If I find any future problems, I'll let you know.

Best regards.

Closing.

**Comment by pyIDM** [comment]
Great :+1:
