### ISSUE TITLE
Readme has bad links / missing images

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#69]
When I come to this repo, I see this as the homepage/readme:

![image](https://user-images.githubusercontent.com/46163555/78563589-3b0cc780-77e9-11ea-811e-5e98bcf2ed0b.png)

I don't think it's something with my browser, but maybe it is.  I'm running Chrome on Win 10.

**Comment by pyIDM** [comment]
Thanks for reporting this,
I believe something wrong with "https://img.shields.io" stats
I have same broken urls

![image](https://user-images.githubusercontent.com/58998813/78577736-ceb4b700-782e-11ea-8550-e0ad5ae1aa41.png)

**Comment by PySimpleGUI** [comment]
Left messages in the Column issue, but I guess you don't see those unless you opened it.  Can you give the latest a try?  Managed to get Comboboxes to behave during the scrolls.

**Comment by smaragdus** [comment]
This is what I see:

[Cent Browser](https://www.centbrowser.com/) (**Chromium**-based):

![PyIDM - Cent Browser - 2020-04-08 - 004](https://user-images.githubusercontent.com/9025757/78774786-d777cb00-799d-11ea-910c-90242983803a.png)

[Iceweasel](https://sourceforge.net/projects/libportable/) (**Firefox**-based):

![PyIDM - Iceweasel - 2020-04-08 - 002](https://user-images.githubusercontent.com/9025757/78774501-6fc18000-799d-11ea-84d8-ae69fd63642b.png)

Emptying cache does not help.

**Comment by PySimpleGUI** [comment]
It's been working for me for a few days following the reply.  

![image](https://user-images.githubusercontent.com/46163555/78781322-070edf00-796e-11ea-8420-db052524f37d.png)

**Comment by pyIDM** [comment]
> Managed to get Comboboxes to behave during the scrolls.

@PySimpleGUI 
just tried version "4.18.0.19" and it does work, scrolling columns by mouse wheel without changing combo boxes, thanks!
