### ISSUE TITLE
Custom Artwork

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#71]
What did you use to create the custom buttons and other art assets?  Do you have any advice on how to make user interfaces look better?

**Comment by pyIDM** [comment]
@PySimpleGUI 
I am using inkscape, it is a great tool to get high quality icon without too much prior knowledge, also GIMP could be used but it is too much for icon work, and i think inkscape fits this slot better.

> Do you have any advice on how to make user interfaces look better?

I am not good at design, so really i haven't much to say, just believe that beautiful gui is the one that doesn't confuse you, simple and minimalist.

**Comment by PySimpleGUI** [comment]
Thanks!  Not used inkscape but will certainly check it out now.  Always looking for things people can use to not think tkinter sucks. 

 You **are** good at design, have a great eye for it.  What you did with strings and symbols was brilliant and I'll be stealing your idea for sure in the Cookbook.   pyIDM has been a fabulous project to point to as a success story.  Wow, your stars have gone nuts.  Congrats!
