### ISSUE TITLE
clickable links in "about window"

### ISSUE THREAD

**Issue by pyIDM** [pyIDM/pyIDM#72]
reference comment by @smaragdus, 
comment: https://github.com/pyIDM/pyIDM/issues/49#issuecomment-611989318

A further improvement of the 'About' window would be clickable links:

    Clicking on URL link opens default web browser:
    Clicking on mail link opens default mail client;

screen:

![pyIDM 2020 04 08](https://user-images.githubusercontent.com/9025757/78987220-0e80e480-7b36-11ea-8a95-77052859425d.png)

This would be useful for quick access to project page via 'About' window.

**Comment by pyIDM** [comment]
@smaragdus
fixed in release 2020.4.17

![image](https://user-images.githubusercontent.com/58998813/79640905-9e590b00-8194-11ea-99dc-1aafcf230e57.png)

**Comment by smaragdus** [comment]
@pyIDM 

Thanks. The links open just right and `email copied to clipboard` is fine:

![PyIDM 2020 04 17 - 2020-04-18 - 001](https://user-images.githubusercontent.com/9025757/79643530-049d5800-81ac-11ea-9bf3-f546890bce46.png)

Just a question- wouldn't it be better to place a link to [Issues](https://github.com/pyIDM/pyIDM/issues) in stead of a link to [New Issue](https://github.com/pyIDM/pyIDM/issues/new) as not everyone has GitHub account?

Anyway, excellent work.

Best regards

**Comment by pyIDM** [comment]
> Just a question- wouldn't it be better to place a link to Issues in stead of a link to New Issue as not everyone has GitHub account?

I can add it to the list like below

![image](https://user-images.githubusercontent.com/58998813/79644118-23e5b680-81a7-11ea-84bd-00135136b1dc.png)

**Comment by smaragdus** [comment]
@pyIDM 

> I can add it to the list like below

It looks fine.

What about aligning all the links to the right? I mean moving `Email` address precisely below the links.

**Comment by pyIDM** [comment]
you are right it looks better with email aligned with other links

![image](https://user-images.githubusercontent.com/58998813/79662808-fb64b900-81b4-11ea-92b1-d96acc13b975.png)

**Comment by smaragdus** [comment]
@pyIDM 

Excellent!
