### ISSUE TITLE
Create a container (with Flatpak for example or Snap ) for linux!

### ISSUE THREAD

**Issue by wada3n** [pyIDM/PyIDM#79]
My greetings.
Why not Create a container (with _Flatpak_ for example or _Snap_) to facilitate the installation process in linux world.
Thanks a lot for the this great work.

**Comment by pyIDM** [comment]
@wada3n 
nice suggestion
will add more installation options for linux

**Comment by wada3n** [comment]
@pyIDM 
بارك الله فيك أخي محمود وفقك الله ورمضان كريم 
والعمل تحفة صراحة جزاك الله خيرا

**Comment by pyIDM** [comment]
@wada3n 
الف شكر لحضرتك 
رمضان كريم

**Comment by pyIDM** [comment]
Created an AppImage [a portable linux version]
working version is available at https://github.com/pyIDM/PyIDM/releases/download/2021.1.7/PyIDM-2021.1.7-x86_64.AppImage

currently there is no plan to work on a snap or flatpak, closing issue
