### ISSUE TITLE
Can you add cookies to the software?

### ISSUE THREAD

**Issue by phongchot** [pyIDM/PyIDM#80]
I hope you can add the Cookies option.
Some pages require such an option.
Sincere thanks

**Comment by pyIDM** [comment]
@phongchot 
Good suggestion 
Will consider to add this option in future releases

**Comment by phongchot** [comment]
Thank you. I will try.

**Comment by pyIDM** [comment]
@phongchot 
I still didn't make a stable PyPI release yet, but you can try by running from github source code

**Comment by pyIDM** [comment]
@phongchot 
just released new version 2020.5.3 on PyPi and windows portable

**Comment by phongchot** [comment]
Thanks for providing such an awesome software. Thanks a lot.
