### ISSUE TITLE
Select All and analysing problem

### ISSUE THREAD

**Issue by quamt** [pyIDM/PyIDM#81]
When copying an URL that consists of many video links and the option Select All is selected the analysing will crash with error to many connections.
Suggestion to be able to limit the analying to a certain amount of video links at the same time. To avoid this problem.

**Comment by pyIDM** [comment]
@quamt 
Can you post an example link/url to reproduce the problem

**Comment by quamt** [comment]
> @quamt
> Can you post an example link/url to reproduce the problem

Hello, 
Unfortunately links will only work whee I live. 
I noticed that each video link has more than one video resolution and several audio languages. 
To avoid the problem I select only a few of the links, wait for them to be analysed and select the next ones. 
The error only occurs if Select All is selected.
That's why the suggestion to have an option that only a limited amount of links get analysed at the same time, and proceed to the next amount of links once the first ones have been analysed and so on.

**Comment by pyIDM** [comment]
So, to make sure I understand what you mean, 
you copied a playlist link, then clicked on playlist button and when you "select all" something went wrong.

For sure limiting the simultaneous fetching for videos info is the right thing to do

i just need to know:
- how many items in playlist ?
- Does the Application stop working or just analyzing fails?

**Comment by quamt** [comment]
Correct.

I tested with a playlist containing 1 video link but the video has roughly 100 video audio combinations and it will produce error message:

>> Unable to download XML: HTTP Error 429: Too Many Requests

The Application continues to work only the analysing seems to fail.

**Comment by quamt** [comment]
Thanks for fixing.
No more error messages.
