### ISSUE TITLE
Download only one subtitle? 

### ISSUE THREAD

**Issue by quamt** [pyIDM/PyIDM#82]
When copying an URL that consists of many video links which have subtitles it is only possible to download one at a time.
It would be great to have an option do download the subtitles together with the video that has been selected. 
Depending on the side the subtitle language to download could be chosen as it is in the single download.
E. G. enUS if selected it will download all this subtitles together with the selected video. If possible multiple language selection of subtitle.

**Comment by quamt** [comment]
To download missing subtitle from playlist the current workaround is:
youtube-dl - - write-sub - - sub-format FORMAT - - sub-lang LANGUAGE - -skip-download PLAYLIST

**Comment by pyIDM** [comment]
@quamt 
I will try to add a subtitle selection option in playlist window

**Comment by quamt** [comment]
Thank you for adding this.
Works great.
