### ISSUE TITLE
Filename cut off

### ISSUE THREAD

**Issue by quamt** [pyIDM/PyIDM#83]
When filename of video has more than 100 characters, the filename will be cut off and the extension for example mp4 is missing or truncated.

**Comment by pyIDM** [comment]
@quamt 
do you mean the name field in main tab? as below

![image](https://user-images.githubusercontent.com/58998813/81142508-24849800-8f70-11ea-858a-64c54653f7de.png)

**Comment by quamt** [comment]
The output file that gets written in the folder for example:


The Long Winter Night a fictional story by anonymous for all kind of people at every age - Chapter 0001.mp4

Becomes:

The Long Winter Night a fictional story by anonymous for all kind of people at every age - Chapter 00

**Comment by pyIDM** [comment]
Thanks for reporting this issue i will do some investigation and let you know once it get fixed

**Comment by quamt** [comment]
Works like a charm.
Thank you.
