### ISSUE TITLE
How are you communicating to users / archiving your releases?

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/PyIDM#84]
I get messages about your releases, etc.

I don't see anything in your Wiki but I get the impression you're communicating well to your users.   My Wiki is empty, your's goes to the homepage?

The reason I'm asking is that I want a place to highlight "Awesome PySimpleGUI Applications".  This one belongs at the top.  Running a close second is the async chat app I posted in the Announcements this morning.  There are number of others that would be good to show.

Maybe if there was something at the top of my readme that got people over to the Wiki then it would be used?

Looking for any ideas or suggestions you might have.

-----------

I like your releases page, but the only way I find it is via the link down in  your readme.

I see that it's on the "Code" tab in GitHub, but if you just click on that tab, I don't see anything to get me to that "Releases" page.  Am I missing something obvious in the user interface?

Trying to learn from you a few things :-)  I can't wait to have a good place to spotlight your application, and some others too.  Lots of cool things being built!!  And, because lots of people seem to be following the "Coding guidelines" we're able to understand each other's code quickly.

**Comment by smaragdus** [comment]
@PySimpleGUI 

A bit off-topic. The only other [PySimpleGUI](https://github.com/PySimpleGUI) program I have tested is [Python Easy Chess GUI](https://github.com/fsmosca/Python-Easy-Chess-GUI) which is promising but still rough. Can you recommend other good **PySimpleGUI** programs?

**Comment by PySimpleGUI** [comment]
If the chess program is "rough", then I don't know what I would suggest.  It's one of the most polished and functional PySimpleGUI programs I've seen to day.  It's fully integrated with an AI back-end.  Has not only a menu-bar but uses right click menus. It would be probably 3rd on my list.

There are numerous PySimpleGUI programs under the PySimpleGUI account (https://github.com/PySimpleGUI?tab=repositories).  I assume you've already looked through the demo programs.

The quick way to find PySimpleGUI programs is to click the "used by" badge at the top of the GitHub.
https://github.com/PySimpleGUI/PySimpleGUI/network/dependents?package_id=UGFja2FnZS05MjkyNDU5MA%3D%3D

Not sure what you're looking for, but those should give you plenty of code to examine.

**Comment by smaragdus** [comment]
@PySimpleGUI 

Thanks for the links. I will have a look when I have time.

About Python Easy Chess GUI- I did a brief testing and my impression was that it needed some polishing- for example- last used color and theme were not saved on exit. When I have time I may re-test it and open several mainly GUI-related issues. What I liked about it is that the program is natively portable.

**Comment by PySimpleGUI** [comment]
I think you'll find that outside of pyIDM very few PySimpleGUI program have settings that are saved from one session to another.  

PySimpleGUI doesn't tend to draw the kind of developers looking to create highly polished, good enough to sell, programs.  You've found the two best in terms of complex and robust UIs.  My COVID19 program saves the theme upon exit for example, but it's still not something I would think will pass your "rough" test.  Same with programs made by Israel Dryer, who I think makes some excellent little GUIs.  I don't know anyone that's trying to make the next Excel with PySimpleGUI.

Let me know if you find some exceptional PySimpleGUI programs out there.

**Comment by pyIDM** [comment]
@PySimpleGUI 
This would be a good idea to have a list of good PySimpleGUI Application, which will help users to see live examples

> I see that it's on the "Code" tab in GitHub, but if you just click on that tab, I don't see anything to get me to that "Releases" page. Am I missing something obvious in the user interface?

it is strange that github didn't include release tab with main tabs (i.e. next to code tab), instead it is a sub tab under code

I believe the best place to put a link for "Awesome PySimpleGUI Applications" would be in readme file at the beginning

for example : "before you jump right in check users awesome work here"
the link will direct to wiki page

this is just an idea, not sure if it is good or bad,

**Comment by PySimpleGUI** [comment]
@pyIDM 

Thank you SO much for all this!
Is there a way to get to the releases tab when you are sitting on the project's main page?  I see the code tab, but even with it clicked, I don't see a way to see the releases sub-tab.

----------------------
# spotlighting

Readme use for spotlighting apps.... great idea... I think this is what I'll do.

I had a little section before.  Maybe I'll put one back and still also consider moving the actual implementation to a Wiki area.  OR, maybe another tab in read the dosc!  Oh, yea, wait, that may work really well.  

I am about to split up the readme, finally, into a couple sections because it gets cutoff on the main page.

The way I'm going to do it is to simple move chuncks from the single readme.md, into another one like "call reference.md".  When placed with other md files in a folder on GitHub called docs, the read the docs is combining them into a single doc http://www.PySimpleGUI.org and placing a tab at the top, one for each .md file that it finds.

Each .md here in my github is made into a tab:
https://github.com/PySimpleGUI/PySimpleGUI/tree/master/docs

![image](https://user-images.githubusercontent.com/46163555/81790987-23a1b800-94d4-11ea-9b9b-87f6182a3595.png)

--------------------------------

# release 4.19.0

Is the new release in use in pyIDM yet???

I'm scared to death it'll break your code, so please let me know if it works out for you.

I found a bug with a tab being cutoff while make a youtube video.  Hope it's nothing new nor impacts you.

-----------------------

Thank you for the help / support.... it's all appreciated.

**Comment by pyIDM** [comment]
> Is there a way to get to the releases tab when you are sitting on the project's main page? I see the code tab, but even with it clicked, I don't see a way to see the releases sub-tab.

using my smartphone or tablet, i can't see the release tab too, but on my laptop "desktop view", I can see it as below


![image](https://user-images.githubusercontent.com/58998813/81801847-53bd7b00-9515-11ea-9161-d7909a061b7b.png)


> Is the new release in use in pyIDM yet???

really didn't try it yet, it was short time to try it before last release

Sorry if this is not the proper place for this but I have a question regarding tabs,
is there a way to define tab size "tab header width", if you look at "Advanced" tab below you will find it bigger than other tabs, i use spaces with tab names to control its width but it doesn't work well enough

![image](https://user-images.githubusercontent.com/58998813/81802693-d5fa6f00-9516-11ea-9325-eaa588a19b50.png)

**Comment by PySimpleGUI** [comment]
I opened an issue on my github this morning about tabs and the text being cutoff as a bug.

For your specific need, I would use a fixed width font.  I was going to suggest setting a size parameter, but I don't think there is one.

Tabs are a ttk widget and it wasn't that long ago that I cracked the ttk code and figured out how to properly style them.

You can do your own styling if you don't find the settings good.  There's an Issue about Button Focus that describes how to modify a ttk button. https://github.com/PySimpleGUI/PySimpleGUI/issues/2758

I posted this code that showed how to modify a ttk button's style:

```python
import PySimpleGUI as sg
from tkinter import ttk

button_key = '-B-'

layout = [  [sg.Text('My Window')],
            [sg.Input(key='-IN-'), sg.Text(size=(12,1), key='-OUT-')],
            [sg.Button('Go', key=button_key), sg.Button('Exit')]  ]

window = sg.Window('Window Title', layout, use_ttk_buttons=True)

while True:             # Event Loop
    event, values = window.read()
    if event in (None, 'Exit'):
        break
    if event == '-B-':
        style_name = button_key + 'custombutton.TButton'
        button_style = ttk.Style()
        button_style.theme_use(window.TtkTheme)
        button_style.configure(style_name, focuscolor='red')
window.close()
```

A TabGroup uses a ttk.Notebook widget.

The style name for this will be in same format as the button above, but for notebooks.
```python
        style_name = tabgroup_key + 'custombutton.TButton'
```

The short answer though is to us a font like tkfixedsys and then make the text the same size of all of them.

**Comment by pyIDM** [comment]
@PySimpleGUI 
thanks
