### ISSUE TITLE
The far slower download speed observed by PyIDM than using curl directly via the same local socks5 proxy.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#93]
Hi,

On my Ubuntu 20.04, I cloned this repo and run the pyidm.py within a py 3.8.3 virtualenv. Then do the following testings for comparison:

1. Download with curl:

```
$ curl -x socks5://127.0.0.1:18887 http://muug.ca/mirror/ctan/systems/texlive/Images/texlive2020-20200406.iso >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 17 3813M   17  663M    0     0  15.5M      0  0:04:04  0:00:42  0:03:22 17.7M^C
```

2. Download with pyidm using the same socks5 proxy as above with 8 connections per download, but the observed download speed is only around `3.5Mb/s`.  This is far slower than the speed gained by using curl directly.

Any hints for this problem?

Regards,
HY

**Comment by pyIDM** [comment]
@hongyi-zhao 
This is strange because PyIDM is using the same curl engine "Libcurl"
i believe the server or the proxy itself doesn't allow too much connections
can you repeat the test using only 1 connection  from "Settings>Network>Max connections per download"
then if you gained a full speed try to increase connections gradually and see how it goes
also check "Log" Tab and see if there is any errors

**Comment by hongyi-zhao** [comment]
The socks5 proxy allow concurrent connections. I tested it by [flareget](https://flareget.com/) with 8 concurrent connections per download and the speed is around `20 ~ 28 Mb/s` which is basically close to the up limit of my ISP's supplied speed.

Regards

**Comment by pyIDM** [comment]
@hongyi-zhao 
did you test PyIDM with one connection?

**Comment by hongyi-zhao** [comment]
Yes, with the following settings:

```
Max concurrent downloads: 1
Max connections per download: 1
```

The observed speed is about `600 ~ 800 KB/s`.

Some log:

```
>> completed segment:  2200
>> Seg 2201 start, size: 512 KB - range: 1153957888-1154482175  - worker 0
>> downloaded segment:  2201 - worker 0
>> completed segment:  2201
>> Seg 2202 start, size: 512 KB - range: 1154482176-1155006463  - worker 0
>> downloaded segment:  2202 - worker 0
>> completed segment:  2202
>> Seg 2203 start, size: 512 KB - range: 1155006464-1155530751  - worker 0
>> downloaded segment:  2203 - worker 0
>> completed segment:  2203
>> Seg 2204 start, size: 512 KB - range: 1155530752-1156055039  - worker 0
>> downloaded segment:  2204 - worker 0
>> completed segment:  2204
>> Seg 2205 start, size: 512 KB - range: 1156055040-1156579327  - worker 0
>> downloaded segment:  2205 - worker 0
>> completed segment:  2205
>> Seg 2206 start, size: 512 KB - range: 1156579328-1157103615  - worker 0
>> downloaded segment:  2206 - worker 0
>> completed segment:  2206
>> Seg 2207 start, size: 512 KB - range: 1157103616-1157627903  - worker 0
>> downloaded segment:  2207 - worker 0
>> completed segment:  2207
>> Seg 2208 start, size: 512 KB - range: 1157627904-1158152191  - worker 0


```

**Comment by pyIDM** [comment]
I think Segment size is not proper for your high internet speed, can you change "Segment size" to "10 MB" instead of "512 KB" from "Settings>General>Segment size"
when you try again don't resume, choose overwrite if prompt popup, or better delete the previous entry from Downloads Tab and try a fresh one

**Comment by pyIDM** [comment]
it Segment size makes a difference you can increase connections back to 8 connections

**Comment by hongyi-zhao** [comment]
You are right. With the 10 MB segment size and 8 connections per download, I obtained `29 MB/s` download speed. See the log info below for more info:

```
>> Seg 125 start, size: 10.0 MB - range: 1310720000-1321205759  - worker 6
>> downloaded segment:  120 - worker 1
>> Seg 126 start, size: 10.0 MB - range: 1321205760-1331691519  - worker 1
>> downloaded segment:  118 - worker 7
>> completed segment:  118
>> Seg 127 start, size: 10.0 MB - range: 1331691520-1342177279  - worker 7
>> downloaded segment:  119 - worker 4
>> completed segment:  119
>> completed segment:  120
>> downloaded segment:  121 - worker 2
>> Seg 128 start, size: 10.0 MB - range: 1342177280-1352663039  - worker 4
>> completed segment:  121
>> Seg 129 start, size: 10.0 MB - range: 1352663040-1363148799  - worker 2
>> brain 1: Cancelled download
```

So how we can let pyidm set segment size dynamically according to the user's internet net connection quality in order to obtain the optimized download speed?

Regards

**Comment by pyIDM** [comment]
> So how we can let pyidm set segment size dynamically according to the user's internet net connection quality in order to obtain the optimized download speed?

Well, I am not sure if this can be done without things getting over complicated
i will try to find a simple way to implement this feature

**Comment by pyIDM** [comment]
Already opened new issue for this feature
set segment size dynamically #97

will close this issue as problem solved
