### ISSUE TITLE
Socks5 and socks5h for pyidm.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#95]
Hi,

It's well known that ` curl | libcurl | pycurl ` support both socks5 and socks5h protocol methods. The former will use the local DNS server for host name resolving while the latter relying on the remote server to do the DNS query.

How can I let pyidm differentiate these two different proxy methods?

Regards

**Comment by pyIDM** [comment]
I believe we can either add an extra choices in proxy type, like "http, https, socks4, socks4a, socks5, and socks5h which i think will be confusing or better
add extra checkbox option like "resolve hostname Localy" 

from Libcurl docs: here is the supported types of proxies,
```
http://
HTTP Proxy. Default when no scheme or proxy type is specified.

https://
HTTPS Proxy. (Added in 7.52.0 for OpenSSL, GnuTLS and NSS)

socks4://
SOCKS4 Proxy.

socks4a://
SOCKS4a Proxy. Proxy resolves URL hostname.

socks5://
SOCKS5 Proxy.

socks5h://
SOCKS5 Proxy. Proxy resolves URL hostname.  
```

**Comment by hongyi-zhao** [comment]
They both have pros and cons:

The former will keep the GUI more concise without so intuitive descriptions. The latter is more clear in meaning but you must replan the GUI panel entries.

Regards
